// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: columns.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countColumnsByBoard = `-- name: CountColumnsByBoard :one
SELECT count(*)::integer AS count
FROM columns
WHERE board_id = $1
`

func (q *Queries) CountColumnsByBoard(ctx context.Context, boardID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countColumnsByBoard, boardID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createColumn = `-- name: CreateColumn :one
INSERT INTO columns (id, board_id, name, color, "order")
VALUES ($1, $2, $3, $4, $5)
RETURNING id, board_id, name, color, "order"
`

type CreateColumnParams struct {
	ID      uuid.UUID   `json:"id"`
	BoardID uuid.UUID   `json:"board_id"`
	Name    string      `json:"name"`
	Color   pgtype.Text `json:"color"`
	Order   int32       `json:"order"`
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (Column, error) {
	row := q.db.QueryRow(ctx, createColumn,
		arg.ID,
		arg.BoardID,
		arg.Name,
		arg.Color,
		arg.Order,
	)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Color,
		&i.Order,
	)
	return i, err
}

const getColumn = `-- name: GetColumn :one
SELECT c.id, c.board_id, c.name, c.color, c."order", b.company_id
FROM columns c
JOIN boards b ON b.id = c.board_id
WHERE b.company_id = $1 AND c.id = $2
`

type GetColumnParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

type GetColumnRow struct {
	ID        uuid.UUID   `json:"id"`
	BoardID   uuid.UUID   `json:"board_id"`
	Name      string      `json:"name"`
	Color     pgtype.Text `json:"color"`
	Order     int32       `json:"order"`
	CompanyID uuid.UUID   `json:"company_id"`
}

func (q *Queries) GetColumn(ctx context.Context, arg GetColumnParams) (GetColumnRow, error) {
	row := q.db.QueryRow(ctx, getColumn, arg.CompanyID, arg.ID)
	var i GetColumnRow
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Color,
		&i.Order,
		&i.CompanyID,
	)
	return i, err
}

const listColumnsByBoard = `-- name: ListColumnsByBoard :many
SELECT id, board_id, name, color, "order"
FROM columns
WHERE board_id = $1
ORDER BY "order"
`

func (q *Queries) ListColumnsByBoard(ctx context.Context, boardID uuid.UUID) ([]Column, error) {
	rows, err := q.db.Query(ctx, listColumnsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Column{}
	for rows.Next() {
		var i Column
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Color,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateColumn = `-- name: UpdateColumn :one
UPDATE columns
SET
    name = COALESCE($2, name),
    color = COALESCE($3, color)
WHERE id = $1
RETURNING id, board_id, name, color, "order"
`

type UpdateColumnParams struct {
	ID    uuid.UUID   `json:"id"`
	Name  pgtype.Text `json:"name"`
	Color pgtype.Text `json:"color"`
}

func (q *Queries) UpdateColumn(ctx context.Context, arg UpdateColumnParams) (Column, error) {
	row := q.db.QueryRow(ctx, updateColumn, arg.ID, arg.Name, arg.Color)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Color,
		&i.Order,
	)
	return i, err
}
