// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listLabels = `-- name: ListLabels :many
SELECT id, company_id, name, color
FROM labels
WHERE company_id = $1
ORDER BY name
`

func (q *Queries) ListLabels(ctx context.Context, companyID uuid.UUID) ([]Label, error) {
	rows, err := q.db.Query(ctx, listLabels, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
