// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox (id, company_id, aggregate_id, subject, payload, headers, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_id, aggregate_id, event_order, subject, payload, headers, occurred_at,
          next_attempt_at, published_at, attempts, last_error
`

type CreateOutboxEventParams struct {
	ID          uuid.UUID `json:"id"`
	CompanyID   uuid.UUID `json:"company_id"`
	AggregateID uuid.UUID `json:"aggregate_id"`
	Subject     string    `json:"subject"`
	Payload     []byte    `json:"payload"`
	Headers     []byte    `json:"headers"`
	OccurredAt  time.Time `json:"occurred_at"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.ID,
		arg.CompanyID,
		arg.AggregateID,
		arg.Subject,
		arg.Payload,
		arg.Headers,
		arg.OccurredAt,
	)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.AggregateID,
		&i.EventOrder,
		&i.Subject,
		&i.Payload,
		&i.Headers,
		&i.OccurredAt,
		&i.NextAttemptAt,
		&i.PublishedAt,
		&i.Attempts,
		&i.LastError,
	)
	return i, err
}
