// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountColumnsByBoard(ctx context.Context, boardID uuid.UUID) (int32, error)
	CountTasksInColumn(ctx context.Context, columnID uuid.UUID) (int32, error)
	CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error)
	CreateColumn(ctx context.Context, arg CreateColumnParams) (Column, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (Outbox, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	GetBoard(ctx context.Context, arg GetBoardParams) (Board, error)
	GetColumn(ctx context.Context, arg GetColumnParams) (GetColumnRow, error)
	GetTask(ctx context.Context, arg GetTaskParams) (Task, error)
	GetTaskForUpdate(ctx context.Context, arg GetTaskForUpdateParams) (Task, error)
	IsRecurrenceGenerated(ctx context.Context, arg IsRecurrenceGeneratedParams) (bool, error)
	ListBoards(ctx context.Context, companyID uuid.UUID) ([]Board, error)
	ListColumnsByBoard(ctx context.Context, boardID uuid.UUID) ([]Column, error)
	ListCommentsByTask(ctx context.Context, taskID uuid.UUID) ([]Comment, error)
	ListLabels(ctx context.Context, companyID uuid.UUID) ([]Label, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	ListTasksDueSoon(ctx context.Context, companyID uuid.UUID) ([]Task, error)
	ListTasksInColumnsForUpdate(ctx context.Context, arg ListTasksInColumnsForUpdateParams) ([]ListTasksInColumnsForUpdateRow, error)
	LockBoardOrder(ctx context.Context, boardID uuid.UUID) error
	LockCompanyBoardBootstrap(ctx context.Context, companyID uuid.UUID) error
	MarkDueSoonSent(ctx context.Context, arg MarkDueSoonSentParams) error
	MarkRecurrenceGenerated(ctx context.Context, arg MarkRecurrenceGeneratedParams) error
	UpdateColumn(ctx context.Context, arg UpdateColumnParams) (Column, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateTaskOrder(ctx context.Context, arg UpdateTaskOrderParams) error
	UpdateTaskPosition(ctx context.Context, arg UpdateTaskPositionParams) error
}

var _ Querier = (*Queries)(nil)
