// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ArticleExists(ctx context.Context, arg ArticleExistsParams) (bool, error)
	CountChildSections(ctx context.Context, arg CountChildSectionsParams) (int64, error)
	CountSectionArticles(ctx context.Context, arg CountSectionArticlesParams) (int64, error)
	CountSectionSiblings(ctx context.Context, arg CountSectionSiblingsParams) (int32, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (CreateArticleRow, error)
	CreateArticlePartnerAccessGrants(ctx context.Context, arg CreateArticlePartnerAccessGrantsParams) ([]ArticlePartnerAccessGrant, error)
	CreateArticleSnapshotReuseGrant(ctx context.Context, arg CreateArticleSnapshotReuseGrantParams) (ArticleSnapshotReuseGrant, error)
	CreateArticleVersion(ctx context.Context, arg CreateArticleVersionParams) (ArticleVersion, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (Outbox, error)
	CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error)
	DeleteArticlePartnerAccessGrants(ctx context.Context, arg DeleteArticlePartnerAccessGrantsParams) (int64, error)
	DeleteSection(ctx context.Context, arg DeleteSectionParams) error
	EnsureCurrentArticleVersion(ctx context.Context, arg EnsureCurrentArticleVersionParams) error
	GetArticle(ctx context.Context, arg GetArticleParams) (GetArticleRow, error)
	GetArticleForUpdate(ctx context.Context, arg GetArticleForUpdateParams) (GetArticleForUpdateRow, error)
	GetArticleSnapshotForCourseCopy(ctx context.Context, arg GetArticleSnapshotForCourseCopyParams) (GetArticleSnapshotForCourseCopyRow, error)
	GetArticleSnapshotReuseGrant(ctx context.Context, arg GetArticleSnapshotReuseGrantParams) (ArticleSnapshotReuseGrant, error)
	GetArticleVersion(ctx context.Context, arg GetArticleVersionParams) (ArticleVersion, error)
	GetArticlesByIDs(ctx context.Context, arg GetArticlesByIDsParams) ([]GetArticlesByIDsRow, error)
	GetPartnerArticle(ctx context.Context, arg GetPartnerArticleParams) (GetPartnerArticleRow, error)
	GetPublicArticle(ctx context.Context, id uuid.UUID) (GetPublicArticleRow, error)
	GetSection(ctx context.Context, arg GetSectionParams) (Section, error)
	ListAcknowledgements(ctx context.Context, arg ListAcknowledgementsParams) ([]ListAcknowledgementsRow, error)
	ListArticlePartnerAccessGrants(ctx context.Context, arg ListArticlePartnerAccessGrantsParams) ([]ArticlePartnerAccessGrant, error)
	ListArticleVersions(ctx context.Context, arg ListArticleVersionsParams) ([]ArticleVersion, error)
	ListArticles(ctx context.Context, arg ListArticlesParams) ([]ListArticlesRow, error)
	ListPartnerArticles(ctx context.Context, arg ListPartnerArticlesParams) ([]ListPartnerArticlesRow, error)
	ListPartnerVisibleSections(ctx context.Context, arg ListPartnerVisibleSectionsParams) ([]ListPartnerVisibleSectionsRow, error)
	ListSections(ctx context.Context, companyID uuid.UUID) ([]Section, error)
	SearchArticles(ctx context.Context, arg SearchArticlesParams) ([]SearchArticlesRow, error)
	SearchPartnerArticles(ctx context.Context, arg SearchPartnerArticlesParams) ([]SearchPartnerArticlesRow, error)
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (UpdateArticleRow, error)
	UpdateArticlePartnerAccessMode(ctx context.Context, arg UpdateArticlePartnerAccessModeParams) (UpdateArticlePartnerAccessModeRow, error)
	UpdateArticlePartnerReusePolicy(ctx context.Context, arg UpdateArticlePartnerReusePolicyParams) (UpdateArticlePartnerReusePolicyRow, error)
	UpdateSection(ctx context.Context, arg UpdateSectionParams) (Section, error)
	UpsertAcknowledgement(ctx context.Context, arg UpsertAcknowledgementParams) error
}

var _ Querier = (*Queries)(nil)
