// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: versions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createArticleVersion = `-- name: CreateArticleVersion :one
INSERT INTO article_versions (id, company_id, article_id, version, title, content, author_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, company_id, article_id, version, title, content, author_id, created_at
`

type CreateArticleVersionParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	ArticleID uuid.UUID `json:"article_id"`
	Version   int32     `json:"version"`
	Title     string    `json:"title"`
	Content   []byte    `json:"content"`
	AuthorID  uuid.UUID `json:"author_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateArticleVersion(ctx context.Context, arg CreateArticleVersionParams) (ArticleVersion, error) {
	row := q.db.QueryRow(ctx, createArticleVersion,
		arg.ID,
		arg.CompanyID,
		arg.ArticleID,
		arg.Version,
		arg.Title,
		arg.Content,
		arg.AuthorID,
		arg.CreatedAt,
	)
	var i ArticleVersion
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ArticleID,
		&i.Version,
		&i.Title,
		&i.Content,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}

const getArticleVersion = `-- name: GetArticleVersion :one
SELECT id, company_id, article_id, version, title, content, author_id, created_at
FROM article_versions
WHERE company_id = $1 AND id = $2
`

type GetArticleVersionParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetArticleVersion(ctx context.Context, arg GetArticleVersionParams) (ArticleVersion, error) {
	row := q.db.QueryRow(ctx, getArticleVersion, arg.CompanyID, arg.ID)
	var i ArticleVersion
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ArticleID,
		&i.Version,
		&i.Title,
		&i.Content,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}

const listArticleVersions = `-- name: ListArticleVersions :many
SELECT id, company_id, article_id, version, title, content, author_id, created_at
FROM article_versions
WHERE company_id = $1 AND article_id = $2
ORDER BY version DESC, created_at DESC
`

type ListArticleVersionsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ArticleID uuid.UUID `json:"article_id"`
}

func (q *Queries) ListArticleVersions(ctx context.Context, arg ListArticleVersionsParams) ([]ArticleVersion, error) {
	rows, err := q.db.Query(ctx, listArticleVersions, arg.CompanyID, arg.ArticleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArticleVersion{}
	for rows.Next() {
		var i ArticleVersion
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ArticleID,
			&i.Version,
			&i.Title,
			&i.Content,
			&i.AuthorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
