// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (id, company_id, uploaded_by, object_key, name, content_type, size, purpose)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, company_id, uploaded_by, object_key, name, content_type, size, purpose, created_at
`

type CreateFileParams struct {
	ID          uuid.UUID `json:"id"`
	CompanyID   uuid.UUID `json:"company_id"`
	UploadedBy  uuid.UUID `json:"uploaded_by"`
	ObjectKey   string    `json:"object_key"`
	Name        string    `json:"name"`
	ContentType string    `json:"content_type"`
	Size        int64     `json:"size"`
	Purpose     string    `json:"purpose"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.ID,
		arg.CompanyID,
		arg.UploadedBy,
		arg.ObjectKey,
		arg.Name,
		arg.ContentType,
		arg.Size,
		arg.Purpose,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UploadedBy,
		&i.ObjectKey,
		&i.Name,
		&i.ContentType,
		&i.Size,
		&i.Purpose,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :one
DELETE FROM files WHERE id = $1 AND company_id = $2 RETURNING object_key
`

type DeleteFileParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteFile, arg.ID, arg.CompanyID)
	var object_key string
	err := row.Scan(&object_key)
	return object_key, err
}

const getFile = `-- name: GetFile :one
SELECT id, company_id, uploaded_by, object_key, name, content_type, size, purpose, created_at FROM files WHERE id = $1 AND company_id = $2
`

type GetFileParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) GetFile(ctx context.Context, arg GetFileParams) (File, error) {
	row := q.db.QueryRow(ctx, getFile, arg.ID, arg.CompanyID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UploadedBy,
		&i.ObjectKey,
		&i.Name,
		&i.ContentType,
		&i.Size,
		&i.Purpose,
		&i.CreatedAt,
	)
	return i, err
}
