// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	DeleteFile(ctx context.Context, arg DeleteFileParams) (string, error)
	GetFile(ctx context.Context, arg GetFileParams) (File, error)
}

var _ Querier = (*Queries)(nil)
