ALTER TABLE distribution_observed_entries ADD COLUMN source_received_at timestamptz, ADD COLUMN source_occurred_at timestamptz;
CREATE TABLE distribution_settings(company_id uuid PRIMARY KEY REFERENCES companies(id),timezone text NOT NULL,revision bigint NOT NULL DEFAULT 1 CHECK(revision BETWEEN 1 AND 9007199254740991));
ALTER TABLE distribution_groups ADD CONSTRAINT distribution_group_company_key UNIQUE(company_id,id);
CREATE TABLE distribution_rules(id uuid PRIMARY KEY,company_id uuid NOT NULL REFERENCES companies(id),binding_id uuid NOT NULL,binding_revision bigint NOT NULL,account_id text NOT NULL,pipeline_id text NOT NULL,status_id text NOT NULL,group_id uuid NOT NULL,active boolean NOT NULL DEFAULT false,keep_current boolean NOT NULL DEFAULT true,first_activation_at timestamptz,revision bigint NOT NULL DEFAULT 1 CHECK(revision BETWEEN 1 AND 9007199254740991),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),FOREIGN KEY(company_id,group_id) REFERENCES distribution_groups(company_id,id),FOREIGN KEY(company_id,binding_id,binding_revision) REFERENCES distribution_binding_versions(company_id,binding_id,revision));
CREATE UNIQUE INDEX distribution_rule_active_point ON distribution_rules(account_id,pipeline_id,status_id) WHERE active;
CREATE TABLE distribution_queue(id uuid PRIMARY KEY,company_id uuid NOT NULL,entry_id uuid NOT NULL UNIQUE REFERENCES distribution_observed_entries(id),rule_id uuid NOT NULL REFERENCES distribution_rules(id),group_id uuid NOT NULL,account_id text NOT NULL,lead_id text NOT NULL,state text NOT NULL DEFAULT 'waiting' CHECK(state IN('waiting','requires_configuration','dispatching','uncertain','confirmed','kept','cancelled','failed')),reason text NOT NULL DEFAULT 'checking',next_attempt_at timestamptz NOT NULL DEFAULT clock_timestamp(),lease_token uuid,lease_until timestamptz,operation_id uuid UNIQUE,decision_id uuid UNIQUE,command jsonb,idempotency_key uuid,cancel_key uuid,reconcile_key uuid,cancel_requested boolean NOT NULL DEFAULT false,settled boolean NOT NULL DEFAULT false,availability_hash bytea,wake_revision bigint NOT NULL DEFAULT 0,claim_revision bigint NOT NULL DEFAULT 1,selection_order uuid[] NOT NULL DEFAULT '{}',planned_employee_id uuid,planned_at timestamptz,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),CHECK((lease_token IS NULL)=(lease_until IS NULL)),CHECK(claim_revision BETWEEN 1 AND 9007199254740991),CHECK((operation_id IS NULL)=(command IS NULL)),CHECK((operation_id IS NULL)=(decision_id IS NULL)),CHECK((operation_id IS NULL)=(idempotency_key IS NULL)),CHECK((operation_id IS NULL)=(cancel_key IS NULL)),CHECK((operation_id IS NULL)=(reconcile_key IS NULL)),CHECK((operation_id IS NULL)=(availability_hash IS NULL)),CHECK((operation_id IS NULL)=(planned_employee_id IS NULL)),CHECK(availability_hash IS NULL OR octet_length(availability_hash)=32));
CREATE INDEX distribution_queue_due ON distribution_queue(next_attempt_at,created_at,id) WHERE state NOT IN('confirmed','kept','cancelled','failed');
CREATE TABLE distribution_group_claims(company_id uuid NOT NULL,group_id uuid NOT NULL,queue_id uuid UNIQUE,cursor_order uuid[] NOT NULL DEFAULT '{}',cursor_next integer NOT NULL DEFAULT 0 CHECK(cursor_next>=0),revision bigint NOT NULL DEFAULT 1 CHECK(revision BETWEEN 1 AND 9007199254740991),PRIMARY KEY(company_id,group_id));
CREATE TABLE distribution_lead_claims(account_id text NOT NULL,lead_id text NOT NULL,queue_id uuid NOT NULL UNIQUE REFERENCES distribution_queue(id),PRIMARY KEY(account_id,lead_id));
CREATE TABLE distribution_queue_history(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,queue_id uuid NOT NULL REFERENCES distribution_queue(id),state text NOT NULL,reason text NOT NULL,payload jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE FUNCTION distribution_history_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'distribution history is immutable'; END $$;
CREATE TRIGGER distribution_history_nochange BEFORE UPDATE OR DELETE ON distribution_queue_history FOR EACH ROW EXECUTE FUNCTION distribution_history_immutable();
-- Any authoritative input edit wakes queued rows. No network and no owner locks
-- are held in the application mutation; database execution cannot lose a wake.
CREATE TABLE distribution_availability_versions(company_id uuid PRIMARY KEY REFERENCES companies(id),revision bigint NOT NULL DEFAULT 1 CHECK(revision BETWEEN 1 AND 9007199254740991),processed_revision bigint NOT NULL DEFAULT 0);
CREATE FUNCTION distribution_queue_wake() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 INSERT INTO distribution_availability_versions(company_id) VALUES(COALESCE(NEW.company_id,OLD.company_id)) ON CONFLICT(company_id) DO UPDATE SET revision=distribution_availability_versions.revision+1; RETURN COALESCE(NEW,OLD); END $$;
CREATE TRIGGER distribution_schedule_wake AFTER INSERT OR UPDATE OR DELETE ON user_schedules FOR EACH ROW EXECUTE FUNCTION distribution_queue_wake();
CREATE TRIGGER distribution_exception_wake AFTER INSERT OR UPDATE OR DELETE ON shift_exceptions FOR EACH ROW EXECUTE FUNCTION distribution_queue_wake();
CREATE TRIGGER distribution_user_wake AFTER UPDATE OR DELETE ON users FOR EACH ROW EXECUTE FUNCTION distribution_queue_wake();
CREATE TRIGGER distribution_group_wake AFTER UPDATE OR DELETE ON distribution_groups FOR EACH ROW EXECUTE FUNCTION distribution_queue_wake();
CREATE TRIGGER distribution_mapping_wake AFTER INSERT OR UPDATE OR DELETE ON distribution_employee_mappings FOR EACH ROW EXECUTE FUNCTION distribution_queue_wake();
CREATE TRIGGER distribution_rule_wake AFTER INSERT OR UPDATE OR DELETE ON distribution_rules FOR EACH ROW EXECUTE FUNCTION distribution_queue_wake();
CREATE TRIGGER distribution_setting_wake AFTER INSERT OR UPDATE ON distribution_settings FOR EACH ROW EXECUTE FUNCTION distribution_queue_wake();


CREATE TRIGGER distribution_binding_wake AFTER UPDATE ON distribution_bindings FOR EACH ROW EXECUTE FUNCTION distribution_queue_wake();
CREATE FUNCTION distribution_company_wake() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN INSERT INTO distribution_availability_versions(company_id) VALUES(NEW.id) ON CONFLICT(company_id) DO UPDATE SET revision=distribution_availability_versions.revision+1; RETURN NEW; END $$;
CREATE TRIGGER distribution_company_status_wake AFTER UPDATE OF status ON companies FOR EACH ROW EXECUTE FUNCTION distribution_company_wake();

CREATE TABLE distribution_control_requests(key uuid PRIMARY KEY,queue_id uuid NOT NULL REFERENCES distribution_queue(id),operation_id uuid NOT NULL,action text NOT NULL CHECK(action IN('cancel','reconcile')),expected_result_version bigint NOT NULL CHECK(expected_result_version BETWEEN 1 AND 9007199254740991),payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),UNIQUE(operation_id,action,expected_result_version));
CREATE TRIGGER distribution_controls_nochange BEFORE UPDATE OR DELETE ON distribution_control_requests FOR EACH ROW EXECUTE FUNCTION distribution_history_immutable();
