// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: amo_widget_sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateAmoWidgetIdentity = `-- name: ActivateAmoWidgetIdentity :one
UPDATE user_external_identities
SET status = 'active',
    last_verified_at = $1,
    updated_at = $1
WHERE company_id = $2
  AND id = $3
RETURNING id, company_id, integration_id, user_id, provider, external_account_id, external_user_id, status, last_verified_at, created_at, updated_at
`

type ActivateAmoWidgetIdentityParams struct {
	VerifiedAt time.Time `json:"verified_at"`
	CompanyID  uuid.UUID `json:"company_id"`
	IdentityID uuid.UUID `json:"identity_id"`
}

func (q *Queries) ActivateAmoWidgetIdentity(ctx context.Context, arg ActivateAmoWidgetIdentityParams) (UserExternalIdentity, error) {
	row := q.db.QueryRow(ctx, activateAmoWidgetIdentity, arg.VerifiedAt, arg.CompanyID, arg.IdentityID)
	var i UserExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.IntegrationID,
		&i.UserID,
		&i.Provider,
		&i.ExternalAccountID,
		&i.ExternalUserID,
		&i.Status,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const amoWidgetUserHasPassword = `-- name: AmoWidgetUserHasPassword :one
SELECT EXISTS (
    SELECT 1
    FROM credentials
    WHERE company_id = $1
      AND user_id = $2
)::boolean
`

type AmoWidgetUserHasPasswordParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) AmoWidgetUserHasPassword(ctx context.Context, arg AmoWidgetUserHasPasswordParams) (bool, error) {
	row := q.db.QueryRow(ctx, amoWidgetUserHasPassword, arg.CompanyID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const consumeAmoWidgetContinuation = `-- name: ConsumeAmoWidgetContinuation :one
UPDATE sso_tokens
SET consumed_at = $1
WHERE id = $2
  AND consumed_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > $1
RETURNING id, company_id, user_id, external_identity_id, purpose, token_hash, expires_at, consumed_at, revoked_at, created_at
`

type ConsumeAmoWidgetContinuationParams struct {
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	TokenID    uuid.UUID          `json:"token_id"`
}

func (q *Queries) ConsumeAmoWidgetContinuation(ctx context.Context, arg ConsumeAmoWidgetContinuationParams) (SsoToken, error) {
	row := q.db.QueryRow(ctx, consumeAmoWidgetContinuation, arg.ConsumedAt, arg.TokenID)
	var i SsoToken
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.ExternalIdentityID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAmoWidgetContinuation = `-- name: CreateAmoWidgetContinuation :one
INSERT INTO sso_tokens (
    id, company_id, user_id, external_identity_id, token_hash, expires_at, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_id, user_id, external_identity_id, purpose, token_hash, expires_at, consumed_at, revoked_at, created_at
`

type CreateAmoWidgetContinuationParams struct {
	ID                 uuid.UUID `json:"id"`
	CompanyID          uuid.UUID `json:"company_id"`
	UserID             uuid.UUID `json:"user_id"`
	ExternalIdentityID uuid.UUID `json:"external_identity_id"`
	TokenHash          []byte    `json:"token_hash"`
	ExpiresAt          time.Time `json:"expires_at"`
	CreatedAt          time.Time `json:"created_at"`
}

func (q *Queries) CreateAmoWidgetContinuation(ctx context.Context, arg CreateAmoWidgetContinuationParams) (SsoToken, error) {
	row := q.db.QueryRow(ctx, createAmoWidgetContinuation,
		arg.ID,
		arg.CompanyID,
		arg.UserID,
		arg.ExternalIdentityID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i SsoToken
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.ExternalIdentityID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAmoWidgetIdentity = `-- name: CreateAmoWidgetIdentity :one
INSERT INTO user_external_identities (
    id, company_id, integration_id, user_id, provider, external_account_id,
    external_user_id, status, last_verified_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'active', $8)
RETURNING id, company_id, integration_id, user_id, provider, external_account_id, external_user_id, status, last_verified_at, created_at, updated_at
`

type CreateAmoWidgetIdentityParams struct {
	ID                uuid.UUID `json:"id"`
	CompanyID         uuid.UUID `json:"company_id"`
	IntegrationID     uuid.UUID `json:"integration_id"`
	UserID            uuid.UUID `json:"user_id"`
	Provider          string    `json:"provider"`
	ExternalAccountID string    `json:"external_account_id"`
	ExternalUserID    string    `json:"external_user_id"`
	LastVerifiedAt    time.Time `json:"last_verified_at"`
}

func (q *Queries) CreateAmoWidgetIdentity(ctx context.Context, arg CreateAmoWidgetIdentityParams) (UserExternalIdentity, error) {
	row := q.db.QueryRow(ctx, createAmoWidgetIdentity,
		arg.ID,
		arg.CompanyID,
		arg.IntegrationID,
		arg.UserID,
		arg.Provider,
		arg.ExternalAccountID,
		arg.ExternalUserID,
		arg.LastVerifiedAt,
	)
	var i UserExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.IntegrationID,
		&i.UserID,
		&i.Provider,
		&i.ExternalAccountID,
		&i.ExternalUserID,
		&i.Status,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredAmoWidgetContinuations = `-- name: DeleteExpiredAmoWidgetContinuations :execrows
DELETE FROM sso_tokens
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredAmoWidgetContinuations(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAmoWidgetContinuations, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAmoWidgetUserForUpdate = `-- name: FindAmoWidgetUserForUpdate :one
SELECT id, company_id, email, first_name, last_name, phone, avatar_url, role, status, birth_date, hired_at, vacation_allowance, created_at, updated_at, source, external_id, external_group_id, external_group_name, avatar_source, external_deleted_at, show_in_schedule
FROM users
WHERE company_id = $1
  AND external_deleted_at IS NULL
  AND external_id = $2
LIMIT 1
FOR UPDATE
`

type FindAmoWidgetUserForUpdateParams struct {
	CompanyID  uuid.UUID   `json:"company_id"`
	ExternalID pgtype.Text `json:"external_id"`
}

func (q *Queries) FindAmoWidgetUserForUpdate(ctx context.Context, arg FindAmoWidgetUserForUpdateParams) (User, error) {
	row := q.db.QueryRow(ctx, findAmoWidgetUserForUpdate, arg.CompanyID, arg.ExternalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.BirthDate,
		&i.HiredAt,
		&i.VacationAllowance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ExternalID,
		&i.ExternalGroupID,
		&i.ExternalGroupName,
		&i.AvatarSource,
		&i.ExternalDeletedAt,
		&i.ShowInSchedule,
	)
	return i, err
}

const getAmoWidgetContinuation = `-- name: GetAmoWidgetContinuation :one
SELECT token.id AS token_id,
       token.expires_at,
       token.consumed_at,
       token.revoked_at,
       u.email,
       company.name AS company_name,
       EXISTS (
           SELECT 1 FROM credentials AS credential
           WHERE credential.company_id = token.company_id
             AND credential.user_id = token.user_id
       )::boolean AS has_password,
       u.status AS user_status,
       u.external_deleted_at,
       identity.status AS identity_status,
       integration.status AS integration_status,
       company.status AS company_status
FROM sso_tokens AS token
JOIN user_external_identities AS identity
  ON identity.company_id = token.company_id
 AND identity.user_id = token.user_id
 AND identity.id = token.external_identity_id
JOIN company_integrations AS integration
  ON integration.company_id = identity.company_id
 AND integration.id = identity.integration_id
JOIN users AS u
  ON u.company_id = token.company_id
 AND u.id = token.user_id
JOIN companies AS company ON company.id = token.company_id
WHERE token.token_hash = $1
`

type GetAmoWidgetContinuationRow struct {
	TokenID           uuid.UUID          `json:"token_id"`
	ExpiresAt         time.Time          `json:"expires_at"`
	ConsumedAt        pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	Email             string             `json:"email"`
	CompanyName       string             `json:"company_name"`
	HasPassword       bool               `json:"has_password"`
	UserStatus        string             `json:"user_status"`
	ExternalDeletedAt pgtype.Timestamptz `json:"external_deleted_at"`
	IdentityStatus    string             `json:"identity_status"`
	IntegrationStatus string             `json:"integration_status"`
	CompanyStatus     string             `json:"company_status"`
}

func (q *Queries) GetAmoWidgetContinuation(ctx context.Context, tokenHash []byte) (GetAmoWidgetContinuationRow, error) {
	row := q.db.QueryRow(ctx, getAmoWidgetContinuation, tokenHash)
	var i GetAmoWidgetContinuationRow
	err := row.Scan(
		&i.TokenID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.Email,
		&i.CompanyName,
		&i.HasPassword,
		&i.UserStatus,
		&i.ExternalDeletedAt,
		&i.IdentityStatus,
		&i.IntegrationStatus,
		&i.CompanyStatus,
	)
	return i, err
}

const getAmoWidgetContinuationForUpdate = `-- name: GetAmoWidgetContinuationForUpdate :one
SELECT token.id AS token_id,
       token.expires_at,
       token.consumed_at,
       token.revoked_at,
       u.id, u.company_id, u.email, u.first_name, u.last_name, u.phone, u.avatar_url, u.role, u.status, u.birth_date, u.hired_at, u.vacation_allowance, u.created_at, u.updated_at, u.source, u.external_id, u.external_group_id, u.external_group_name, u.avatar_source, u.external_deleted_at, u.show_in_schedule,
       COALESCE(credential.password_hash, '')::text AS password_hash,
       identity.status AS identity_status,
       integration.provider,
       integration.external_account_id,
       identity.external_user_id,
       integration.status AS integration_status,
       company.status AS company_status
FROM sso_tokens AS token
JOIN user_external_identities AS identity
  ON identity.company_id = token.company_id
 AND identity.user_id = token.user_id
 AND identity.id = token.external_identity_id
JOIN company_integrations AS integration
  ON integration.company_id = identity.company_id
 AND integration.id = identity.integration_id
JOIN users AS u
  ON u.company_id = token.company_id
 AND u.id = token.user_id
JOIN companies AS company ON company.id = token.company_id
LEFT JOIN credentials AS credential
  ON credential.company_id = token.company_id
 AND credential.user_id = token.user_id
WHERE token.token_hash = $1
FOR UPDATE OF token, identity, integration, u, company
`

type GetAmoWidgetContinuationForUpdateRow struct {
	TokenID           uuid.UUID          `json:"token_id"`
	ExpiresAt         time.Time          `json:"expires_at"`
	ConsumedAt        pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	User              User               `json:"user"`
	PasswordHash      string             `json:"password_hash"`
	IdentityStatus    string             `json:"identity_status"`
	Provider          string             `json:"provider"`
	ExternalAccountID string             `json:"external_account_id"`
	ExternalUserID    string             `json:"external_user_id"`
	IntegrationStatus string             `json:"integration_status"`
	CompanyStatus     string             `json:"company_status"`
}

func (q *Queries) GetAmoWidgetContinuationForUpdate(ctx context.Context, tokenHash []byte) (GetAmoWidgetContinuationForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAmoWidgetContinuationForUpdate, tokenHash)
	var i GetAmoWidgetContinuationForUpdateRow
	err := row.Scan(
		&i.TokenID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.User.ID,
		&i.User.CompanyID,
		&i.User.Email,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.Phone,
		&i.User.AvatarUrl,
		&i.User.Role,
		&i.User.Status,
		&i.User.BirthDate,
		&i.User.HiredAt,
		&i.User.VacationAllowance,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.Source,
		&i.User.ExternalID,
		&i.User.ExternalGroupID,
		&i.User.ExternalGroupName,
		&i.User.AvatarSource,
		&i.User.ExternalDeletedAt,
		&i.User.ShowInSchedule,
		&i.PasswordHash,
		&i.IdentityStatus,
		&i.Provider,
		&i.ExternalAccountID,
		&i.ExternalUserID,
		&i.IntegrationStatus,
		&i.CompanyStatus,
	)
	return i, err
}

const getAmoWidgetIntegrationForUpdate = `-- name: GetAmoWidgetIntegrationForUpdate :one
SELECT integration.id, integration.company_id, integration.provider, integration.external_account_id, integration.app_name, integration.entitlements, integration.status, integration.last_verified_at, integration.frozen_at, integration.metadata, integration.created_at, integration.updated_at, company.id, company.name, company.logo_url, company.owner_id, company.created_at, company.updated_at, company.amo_account_id, company.status, company.onboarding_completed_at
FROM company_integrations AS integration
JOIN companies AS company ON company.id = integration.company_id
WHERE integration.provider = $1
  AND integration.external_account_id = $2
FOR UPDATE OF integration, company
`

type GetAmoWidgetIntegrationForUpdateParams struct {
	Provider          string `json:"provider"`
	ExternalAccountID string `json:"external_account_id"`
}

type GetAmoWidgetIntegrationForUpdateRow struct {
	CompanyIntegration CompanyIntegration `json:"company_integration"`
	Company            Company            `json:"company"`
}

func (q *Queries) GetAmoWidgetIntegrationForUpdate(ctx context.Context, arg GetAmoWidgetIntegrationForUpdateParams) (GetAmoWidgetIntegrationForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAmoWidgetIntegrationForUpdate, arg.Provider, arg.ExternalAccountID)
	var i GetAmoWidgetIntegrationForUpdateRow
	err := row.Scan(
		&i.CompanyIntegration.ID,
		&i.CompanyIntegration.CompanyID,
		&i.CompanyIntegration.Provider,
		&i.CompanyIntegration.ExternalAccountID,
		&i.CompanyIntegration.AppName,
		&i.CompanyIntegration.Entitlements,
		&i.CompanyIntegration.Status,
		&i.CompanyIntegration.LastVerifiedAt,
		&i.CompanyIntegration.FrozenAt,
		&i.CompanyIntegration.Metadata,
		&i.CompanyIntegration.CreatedAt,
		&i.CompanyIntegration.UpdatedAt,
		&i.Company.ID,
		&i.Company.Name,
		&i.Company.LogoUrl,
		&i.Company.OwnerID,
		&i.Company.CreatedAt,
		&i.Company.UpdatedAt,
		&i.Company.AmoAccountID,
		&i.Company.Status,
		&i.Company.OnboardingCompletedAt,
	)
	return i, err
}

const getAmoWidgetUserByIdentity = `-- name: GetAmoWidgetUserByIdentity :one
SELECT u.id, u.company_id, u.email, u.first_name, u.last_name, u.phone, u.avatar_url, u.role, u.status, u.birth_date, u.hired_at, u.vacation_allowance, u.created_at, u.updated_at, u.source, u.external_id, u.external_group_id, u.external_group_name, u.avatar_source, u.external_deleted_at, u.show_in_schedule, identity.id, identity.company_id, identity.integration_id, identity.user_id, identity.provider, identity.external_account_id, identity.external_user_id, identity.status, identity.last_verified_at, identity.created_at, identity.updated_at
FROM user_external_identities AS identity
JOIN users AS u
  ON u.company_id = identity.company_id
 AND u.id = identity.user_id
WHERE identity.company_id = $1
  AND identity.integration_id = $2
  AND identity.provider = $3
  AND identity.external_user_id = $4
FOR UPDATE OF identity, u
`

type GetAmoWidgetUserByIdentityParams struct {
	CompanyID      uuid.UUID `json:"company_id"`
	IntegrationID  uuid.UUID `json:"integration_id"`
	Provider       string    `json:"provider"`
	ExternalUserID string    `json:"external_user_id"`
}

type GetAmoWidgetUserByIdentityRow struct {
	User                 User                 `json:"user"`
	UserExternalIdentity UserExternalIdentity `json:"user_external_identity"`
}

func (q *Queries) GetAmoWidgetUserByIdentity(ctx context.Context, arg GetAmoWidgetUserByIdentityParams) (GetAmoWidgetUserByIdentityRow, error) {
	row := q.db.QueryRow(ctx, getAmoWidgetUserByIdentity,
		arg.CompanyID,
		arg.IntegrationID,
		arg.Provider,
		arg.ExternalUserID,
	)
	var i GetAmoWidgetUserByIdentityRow
	err := row.Scan(
		&i.User.ID,
		&i.User.CompanyID,
		&i.User.Email,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.Phone,
		&i.User.AvatarUrl,
		&i.User.Role,
		&i.User.Status,
		&i.User.BirthDate,
		&i.User.HiredAt,
		&i.User.VacationAllowance,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.Source,
		&i.User.ExternalID,
		&i.User.ExternalGroupID,
		&i.User.ExternalGroupName,
		&i.User.AvatarSource,
		&i.User.ExternalDeletedAt,
		&i.User.ShowInSchedule,
		&i.UserExternalIdentity.ID,
		&i.UserExternalIdentity.CompanyID,
		&i.UserExternalIdentity.IntegrationID,
		&i.UserExternalIdentity.UserID,
		&i.UserExternalIdentity.Provider,
		&i.UserExternalIdentity.ExternalAccountID,
		&i.UserExternalIdentity.ExternalUserID,
		&i.UserExternalIdentity.Status,
		&i.UserExternalIdentity.LastVerifiedAt,
		&i.UserExternalIdentity.CreatedAt,
		&i.UserExternalIdentity.UpdatedAt,
	)
	return i, err
}

const listLegacyAmoWidgetCompaniesForUpdate = `-- name: ListLegacyAmoWidgetCompaniesForUpdate :many
SELECT id, name, logo_url, owner_id, created_at, updated_at, amo_account_id, status, onboarding_completed_at
FROM companies
WHERE amo_account_id = $1
ORDER BY created_at, id
FOR UPDATE
`

func (q *Queries) ListLegacyAmoWidgetCompaniesForUpdate(ctx context.Context, externalAccountID pgtype.Text) ([]Company, error) {
	rows, err := q.db.Query(ctx, listLegacyAmoWidgetCompaniesForUpdate, externalAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LogoUrl,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AmoAccountID,
			&i.Status,
			&i.OnboardingCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteAmoWidgetOwner = `-- name: PromoteAmoWidgetOwner :one
UPDATE users
SET role = 'owner',
    status = 'active',
    show_in_schedule = false,
    updated_at = $1
WHERE company_id = $2
  AND id = $3
  AND external_deleted_at IS NULL
RETURNING id, company_id, email, first_name, last_name, phone, avatar_url, role, status, birth_date, hired_at, vacation_allowance, created_at, updated_at, source, external_id, external_group_id, external_group_name, avatar_source, external_deleted_at, show_in_schedule
`

type PromoteAmoWidgetOwnerParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) PromoteAmoWidgetOwner(ctx context.Context, arg PromoteAmoWidgetOwnerParams) (User, error) {
	row := q.db.QueryRow(ctx, promoteAmoWidgetOwner, arg.UpdatedAt, arg.CompanyID, arg.UserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.BirthDate,
		&i.HiredAt,
		&i.VacationAllowance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ExternalID,
		&i.ExternalGroupID,
		&i.ExternalGroupName,
		&i.AvatarSource,
		&i.ExternalDeletedAt,
		&i.ShowInSchedule,
	)
	return i, err
}

const revokeActiveAmoWidgetContinuations = `-- name: RevokeActiveAmoWidgetContinuations :execrows
UPDATE sso_tokens
SET revoked_at = $1
WHERE external_identity_id = $2
  AND consumed_at IS NULL
  AND revoked_at IS NULL
`

type RevokeActiveAmoWidgetContinuationsParams struct {
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
	ExternalIdentityID uuid.UUID          `json:"external_identity_id"`
}

func (q *Queries) RevokeActiveAmoWidgetContinuations(ctx context.Context, arg RevokeActiveAmoWidgetContinuationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeActiveAmoWidgetContinuations, arg.RevokedAt, arg.ExternalIdentityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
