// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvite = `-- name: AcceptInvite :one
UPDATE invites
SET status = 'accepted', updated_at = now()
WHERE id = $1 AND status = 'pending' AND expires_at > now()
RETURNING id, company_id, email, token, role, position_id, department_id, invited_by_id, status, expires_at, created_at, updated_at
`

func (q *Queries) AcceptInvite(ctx context.Context, id uuid.UUID) (Invite, error) {
	row := q.db.QueryRow(ctx, acceptInvite, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.PositionID,
		&i.DepartmentID,
		&i.InvitedByID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const activateInvitedUser = `-- name: ActivateInvitedUser :one
UPDATE users
SET first_name = $2,
    last_name = $3,
    role = $4,
    status = 'active',
    updated_at = now()
WHERE id = $1 AND company_id = $5
RETURNING id, company_id, email, first_name, last_name, phone, avatar_url, role, status, birth_date, hired_at, vacation_allowance, created_at, updated_at
`

type ActivateInvitedUserParams struct {
	ID        uuid.UUID `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Role      string    `json:"role"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) ActivateInvitedUser(ctx context.Context, arg ActivateInvitedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, activateInvitedUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.CompanyID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.BirthDate,
		&i.HiredAt,
		&i.VacationAllowance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (id, name, logo_url)
VALUES ($1, $2, $3)
RETURNING id, name, logo_url, owner_id, created_at, updated_at
`

type CreateCompanyParams struct {
	ID      uuid.UUID   `json:"id"`
	Name    string      `json:"name"`
	LogoUrl pgtype.Text `json:"logo_url"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany, arg.ID, arg.Name, arg.LogoUrl)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LogoUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox (id, company_id, subject, payload, headers, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, subject, payload, headers, occurred_at, next_attempt_at, published_at, attempts, last_error
`

type CreateOutboxEventParams struct {
	ID         uuid.UUID `json:"id"`
	CompanyID  uuid.UUID `json:"company_id"`
	Subject    string    `json:"subject"`
	Payload    []byte    `json:"payload"`
	Headers    []byte    `json:"headers"`
	OccurredAt time.Time `json:"occurred_at"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.ID,
		arg.CompanyID,
		arg.Subject,
		arg.Payload,
		arg.Headers,
		arg.OccurredAt,
	)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Subject,
		&i.Payload,
		&i.Headers,
		&i.OccurredAt,
		&i.NextAttemptAt,
		&i.PublishedAt,
		&i.Attempts,
		&i.LastError,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id, company_id, user_id, refresh_hash, expires_at, rotated_from, user_agent, ip_address
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, company_id, user_id, refresh_hash, expires_at, created_at, last_used_at, revoked_at, rotated_from, replaced_by, user_agent, ip_address
`

type CreateSessionParams struct {
	ID          uuid.UUID     `json:"id"`
	CompanyID   uuid.UUID     `json:"company_id"`
	UserID      uuid.UUID     `json:"user_id"`
	RefreshHash []byte        `json:"refresh_hash"`
	ExpiresAt   time.Time     `json:"expires_at"`
	RotatedFrom uuid.NullUUID `json:"rotated_from"`
	UserAgent   pgtype.Text   `json:"user_agent"`
	IpAddress   *netip.Addr   `json:"ip_address"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.CompanyID,
		arg.UserID,
		arg.RefreshHash,
		arg.ExpiresAt,
		arg.RotatedFrom,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.RefreshHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RotatedFrom,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.IpAddress,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, company_id, email, first_name, last_name, phone, avatar_url,
    role, status, birth_date, hired_at, vacation_allowance
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, company_id, email, first_name, last_name, phone, avatar_url, role, status, birth_date, hired_at, vacation_allowance, created_at, updated_at
`

type CreateUserParams struct {
	ID                uuid.UUID   `json:"id"`
	CompanyID         uuid.UUID   `json:"company_id"`
	Email             string      `json:"email"`
	FirstName         string      `json:"first_name"`
	LastName          string      `json:"last_name"`
	Phone             pgtype.Text `json:"phone"`
	AvatarUrl         pgtype.Text `json:"avatar_url"`
	Role              string      `json:"role"`
	Status            string      `json:"status"`
	BirthDate         pgtype.Date `json:"birth_date"`
	HiredAt           pgtype.Date `json:"hired_at"`
	VacationAllowance pgtype.Int2 `json:"vacation_allowance"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.CompanyID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.AvatarUrl,
		arg.Role,
		arg.Status,
		arg.BirthDate,
		arg.HiredAt,
		arg.VacationAllowance,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.BirthDate,
		&i.HiredAt,
		&i.VacationAllowance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, logo_url, owner_id, created_at, updated_at FROM companies WHERE id = $1
`

func (q *Queries) GetCompany(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LogoUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT id, company_id, email, token, role, position_id, department_id, invited_by_id, status, expires_at, created_at, updated_at FROM invites WHERE token = $1
`

func (q *Queries) GetInviteByToken(ctx context.Context, token string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, token)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.PositionID,
		&i.DepartmentID,
		&i.InvitedByID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInviteByTokenForUpdate = `-- name: GetInviteByTokenForUpdate :one
SELECT id, company_id, email, token, role, position_id, department_id, invited_by_id, status, expires_at, created_at, updated_at FROM invites WHERE token = $1 FOR UPDATE
`

func (q *Queries) GetInviteByTokenForUpdate(ctx context.Context, token string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenForUpdate, token)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.PositionID,
		&i.DepartmentID,
		&i.InvitedByID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByHashForUpdate = `-- name: GetSessionByHashForUpdate :one
SELECT id, company_id, user_id, refresh_hash, expires_at, created_at, last_used_at, revoked_at, rotated_from, replaced_by, user_agent, ip_address FROM sessions
WHERE refresh_hash = $1
FOR UPDATE
`

func (q *Queries) GetSessionByHashForUpdate(ctx context.Context, refreshHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByHashForUpdate, refreshHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.RefreshHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RotatedFrom,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.IpAddress,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, company_id, email, first_name, last_name, phone, avatar_url, role, status, birth_date, hired_at, vacation_allowance, created_at, updated_at FROM users WHERE company_id = $1 AND id = $2
`

type GetUserParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getUser, arg.CompanyID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.BirthDate,
		&i.HiredAt,
		&i.VacationAllowance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailForUpdate = `-- name: GetUserByEmailForUpdate :one
SELECT id, company_id, email, first_name, last_name, phone, avatar_url, role, status, birth_date, hired_at, vacation_allowance, created_at, updated_at FROM users
WHERE email = $1
FOR UPDATE
`

func (q *Queries) GetUserByEmailForUpdate(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailForUpdate, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.BirthDate,
		&i.HiredAt,
		&i.VacationAllowance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserDepartmentClaims = `-- name: GetUserDepartmentClaims :many
WITH RECURSIVE direct_departments AS (
    SELECT DISTINCT p.department_id AS id
    FROM user_positions up
    JOIN positions p ON p.id = up.position_id
    WHERE up.company_id = $1 AND up.user_id = $2
), department_chain AS (
    SELECT d.id, d.parent_id
    FROM departments d
    JOIN direct_departments dd ON dd.id = d.id
    UNION
    SELECT parent.id, parent.parent_id
    FROM departments parent
    JOIN department_chain child ON child.parent_id = parent.id
)
SELECT DISTINCT id FROM department_chain
`

type GetUserDepartmentClaimsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserDepartmentClaims(ctx context.Context, arg GetUserDepartmentClaimsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getUserDepartmentClaims, arg.CompanyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT u.id, u.company_id, u.email, u.first_name, u.last_name, u.phone, u.avatar_url, u.role, u.status, u.birth_date, u.hired_at, u.vacation_allowance, u.created_at, u.updated_at, c.password_hash
FROM users u
JOIN credentials c ON c.user_id = u.id
WHERE u.email = $1
FOR SHARE OF u
`

type GetUserForLoginRow struct {
	User         User   `json:"user"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, email)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.User.ID,
		&i.User.CompanyID,
		&i.User.Email,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.Phone,
		&i.User.AvatarUrl,
		&i.User.Role,
		&i.User.Status,
		&i.User.BirthDate,
		&i.User.HiredAt,
		&i.User.VacationAllowance,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserPositionIDs = `-- name: GetUserPositionIDs :many
SELECT position_id
FROM user_positions
WHERE company_id = $1 AND user_id = $2
`

type GetUserPositionIDsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserPositionIDs(ctx context.Context, arg GetUserPositionIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getUserPositionIDs, arg.CompanyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var position_id uuid.UUID
		if err := rows.Scan(&position_id); err != nil {
			return nil, err
		}
		items = append(items, position_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, $2)
WHERE user_id = $1
`

type RevokeAllUserSessionsParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, arg.UserID, arg.RevokedAt)
	return err
}

const revokeSessionByHash = `-- name: RevokeSessionByHash :execrows
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, $2), last_used_at = $2
WHERE refresh_hash = $1
`

type RevokeSessionByHashParams struct {
	RefreshHash []byte             `json:"refresh_hash"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) RevokeSessionByHash(ctx context.Context, arg RevokeSessionByHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionByHash, arg.RefreshHash, arg.LastUsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateSession = `-- name: RotateSession :execrows
UPDATE sessions
SET revoked_at = $2, last_used_at = $2, replaced_by = $3
WHERE id = $1 AND revoked_at IS NULL
`

type RotateSessionParams struct {
	ID         uuid.UUID          `json:"id"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy uuid.NullUUID      `json:"replaced_by"`
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateSession, arg.ID, arg.RevokedAt, arg.ReplacedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCompanyOwner = `-- name: SetCompanyOwner :one
UPDATE companies
SET owner_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, logo_url, owner_id, created_at, updated_at
`

type SetCompanyOwnerParams struct {
	ID      uuid.UUID     `json:"id"`
	OwnerID uuid.NullUUID `json:"owner_id"`
}

func (q *Queries) SetCompanyOwner(ctx context.Context, arg SetCompanyOwnerParams) (Company, error) {
	row := q.db.QueryRow(ctx, setCompanyOwner, arg.ID, arg.OwnerID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LogoUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCredential = `-- name: SetCredential :exec
INSERT INTO credentials (company_id, user_id, password_hash)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET password_hash = EXCLUDED.password_hash, updated_at = now()
`

type SetCredentialParams struct {
	CompanyID    uuid.UUID `json:"company_id"`
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) SetCredential(ctx context.Context, arg SetCredentialParams) error {
	_, err := q.db.Exec(ctx, setCredential, arg.CompanyID, arg.UserID, arg.PasswordHash)
	return err
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET name = COALESCE($1, name),
    logo_url = CASE WHEN $2::boolean THEN $3 ELSE logo_url END,
    updated_at = now()
WHERE id = $4
RETURNING id, name, logo_url, owner_id, created_at, updated_at
`

type UpdateCompanyParams struct {
	Name    pgtype.Text `json:"name"`
	SetLogo bool        `json:"set_logo"`
	LogoUrl pgtype.Text `json:"logo_url"`
	ID      uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.Name,
		arg.SetLogo,
		arg.LogoUrl,
		arg.ID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LogoUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCurrentUser = `-- name: UpdateCurrentUser :one
UPDATE users
SET first_name = COALESCE($1, first_name),
    last_name = COALESCE($2, last_name),
    phone = CASE WHEN $3::boolean THEN $4 ELSE phone END,
    avatar_url = CASE WHEN $5::boolean THEN $6 ELSE avatar_url END,
    updated_at = now()
WHERE company_id = $7 AND id = $8
RETURNING id, company_id, email, first_name, last_name, phone, avatar_url, role, status, birth_date, hired_at, vacation_allowance, created_at, updated_at
`

type UpdateCurrentUserParams struct {
	FirstName    pgtype.Text `json:"first_name"`
	LastName     pgtype.Text `json:"last_name"`
	SetPhone     bool        `json:"set_phone"`
	Phone        pgtype.Text `json:"phone"`
	SetAvatarUrl bool        `json:"set_avatar_url"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	CompanyID    uuid.UUID   `json:"company_id"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateCurrentUser(ctx context.Context, arg UpdateCurrentUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateCurrentUser,
		arg.FirstName,
		arg.LastName,
		arg.SetPhone,
		arg.Phone,
		arg.SetAvatarUrl,
		arg.AvatarUrl,
		arg.CompanyID,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.BirthDate,
		&i.HiredAt,
		&i.VacationAllowance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
