// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: distribution_connections.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ackDistributionMappingSnapshot = `-- name: AckDistributionMappingSnapshot :execrows
UPDATE distribution_bindings SET mapping_ack_revision=$3 WHERE company_id=$1 AND id=$2 AND mapping_revision=$3 AND state='active'
`

type AckDistributionMappingSnapshotParams struct {
	CompanyID          uuid.UUID `json:"company_id"`
	ID                 uuid.UUID `json:"id"`
	MappingAckRevision int64     `json:"mapping_ack_revision"`
}

func (q *Queries) AckDistributionMappingSnapshot(ctx context.Context, arg AckDistributionMappingSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, ackDistributionMappingSnapshot, arg.CompanyID, arg.ID, arg.MappingAckRevision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const activateDistributionBinding = `-- name: ActivateDistributionBinding :one
UPDATE distribution_bindings SET state='active',updated_at=now() WHERE company_id=$1 AND id=$2 AND revision=$3 AND state IN ('pending','active') RETURNING id, company_id, revision, installation_id, integration_id, account_id, state, mapping_revision, mapping_ack_revision, intent_id, initiated_by, initiator_snapshot, expires_at, created_at, updated_at, account_timezone, timezone_fetched_at, account_domain
`

type ActivateDistributionBindingParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
	Revision  int64     `json:"revision"`
}

func (q *Queries) ActivateDistributionBinding(ctx context.Context, arg ActivateDistributionBindingParams) (DistributionBinding, error) {
	row := q.db.QueryRow(ctx, activateDistributionBinding, arg.CompanyID, arg.ID, arg.Revision)
	var i DistributionBinding
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Revision,
		&i.InstallationID,
		&i.IntegrationID,
		&i.AccountID,
		&i.State,
		&i.MappingRevision,
		&i.MappingAckRevision,
		&i.IntentID,
		&i.InitiatedBy,
		&i.InitiatorSnapshot,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountTimezone,
		&i.TimezoneFetchedAt,
		&i.AccountDomain,
	)
	return i, err
}

const claimDistributionNonce = `-- name: ClaimDistributionNonce :execrows
INSERT INTO distribution_service_nonces(key_id,nonce,expires_at) VALUES($1,$2,$3) ON CONFLICT DO NOTHING
`

type ClaimDistributionNonceParams struct {
	KeyID     string    `json:"key_id"`
	Nonce     uuid.UUID `json:"nonce"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) ClaimDistributionNonce(ctx context.Context, arg ClaimDistributionNonceParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimDistributionNonce, arg.KeyID, arg.Nonce, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanupDistributionNonces = `-- name: CleanupDistributionNonces :exec
DELETE FROM distribution_service_nonces WHERE expires_at < now()
`

func (q *Queries) CleanupDistributionNonces(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupDistributionNonces)
	return err
}

const createDistributionBinding = `-- name: CreateDistributionBinding :one
INSERT INTO distribution_bindings(id,company_id,installation_id,integration_id,account_id,state,intent_id,initiated_by,initiator_snapshot,expires_at)
VALUES($1,$2,$3,$4,$5,'pending',$6,$7,$7,$8) RETURNING id, company_id, revision, installation_id, integration_id, account_id, state, mapping_revision, mapping_ack_revision, intent_id, initiated_by, initiator_snapshot, expires_at, created_at, updated_at, account_timezone, timezone_fetched_at, account_domain
`

type CreateDistributionBindingParams struct {
	ID             uuid.UUID     `json:"id"`
	CompanyID      uuid.UUID     `json:"company_id"`
	InstallationID uuid.UUID     `json:"installation_id"`
	IntegrationID  uuid.UUID     `json:"integration_id"`
	AccountID      string        `json:"account_id"`
	IntentID       uuid.UUID     `json:"intent_id"`
	InitiatedBy    uuid.NullUUID `json:"initiated_by"`
	ExpiresAt      time.Time     `json:"expires_at"`
}

func (q *Queries) CreateDistributionBinding(ctx context.Context, arg CreateDistributionBindingParams) (DistributionBinding, error) {
	row := q.db.QueryRow(ctx, createDistributionBinding,
		arg.ID,
		arg.CompanyID,
		arg.InstallationID,
		arg.IntegrationID,
		arg.AccountID,
		arg.IntentID,
		arg.InitiatedBy,
		arg.ExpiresAt,
	)
	var i DistributionBinding
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Revision,
		&i.InstallationID,
		&i.IntegrationID,
		&i.AccountID,
		&i.State,
		&i.MappingRevision,
		&i.MappingAckRevision,
		&i.IntentID,
		&i.InitiatedBy,
		&i.InitiatorSnapshot,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountTimezone,
		&i.TimezoneFetchedAt,
		&i.AccountDomain,
	)
	return i, err
}

const currentDistributionBinding = `-- name: CurrentDistributionBinding :one
SELECT id, company_id, revision, installation_id, integration_id, account_id, state, mapping_revision, mapping_ack_revision, intent_id, initiated_by, initiator_snapshot, expires_at, created_at, updated_at, account_timezone, timezone_fetched_at, account_domain FROM distribution_bindings WHERE company_id=$1 AND state <> 'revoked' FOR UPDATE
`

func (q *Queries) CurrentDistributionBinding(ctx context.Context, companyID uuid.UUID) (DistributionBinding, error) {
	row := q.db.QueryRow(ctx, currentDistributionBinding, companyID)
	var i DistributionBinding
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Revision,
		&i.InstallationID,
		&i.IntegrationID,
		&i.AccountID,
		&i.State,
		&i.MappingRevision,
		&i.MappingAckRevision,
		&i.IntentID,
		&i.InitiatedBy,
		&i.InitiatorSnapshot,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountTimezone,
		&i.TimezoneFetchedAt,
		&i.AccountDomain,
	)
	return i, err
}

const getDistributionBinding = `-- name: GetDistributionBinding :one
SELECT id, company_id, revision, installation_id, integration_id, account_id, state, mapping_revision, mapping_ack_revision, intent_id, initiated_by, initiator_snapshot, expires_at, created_at, updated_at, account_timezone, timezone_fetched_at, account_domain FROM distribution_bindings WHERE company_id=$1 AND id=$2
`

type GetDistributionBindingParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetDistributionBinding(ctx context.Context, arg GetDistributionBindingParams) (DistributionBinding, error) {
	row := q.db.QueryRow(ctx, getDistributionBinding, arg.CompanyID, arg.ID)
	var i DistributionBinding
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Revision,
		&i.InstallationID,
		&i.IntegrationID,
		&i.AccountID,
		&i.State,
		&i.MappingRevision,
		&i.MappingAckRevision,
		&i.IntentID,
		&i.InitiatedBy,
		&i.InitiatorSnapshot,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountTimezone,
		&i.TimezoneFetchedAt,
		&i.AccountDomain,
	)
	return i, err
}

const getDistributionMappingByCRM = `-- name: GetDistributionMappingByCRM :one
SELECT m.id, m.company_id, m.binding_id, m.user_id, m.user_id_snapshot, m.crm_user_id, m.state, m.revision, m.verified_at,u.status AS user_status,u.role AS user_role,ARRAY(SELECT a.section FROM employee_section_access a WHERE a.company_id=u.company_id AND a.user_id=u.id)::text[] AS section_access FROM distribution_employee_mappings m
JOIN users u ON u.company_id=m.company_id AND u.id=m.user_id WHERE m.company_id=$1 AND m.binding_id=$2 AND m.crm_user_id=$3 AND u.external_deleted_at IS NULL
`

type GetDistributionMappingByCRMParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	BindingID uuid.UUID `json:"binding_id"`
	CrmUserID string    `json:"crm_user_id"`
}

type GetDistributionMappingByCRMRow struct {
	ID             uuid.UUID     `json:"id"`
	CompanyID      uuid.UUID     `json:"company_id"`
	BindingID      uuid.UUID     `json:"binding_id"`
	UserID         uuid.NullUUID `json:"user_id"`
	UserIDSnapshot uuid.UUID     `json:"user_id_snapshot"`
	CrmUserID      string        `json:"crm_user_id"`
	State          string        `json:"state"`
	Revision       int64         `json:"revision"`
	VerifiedAt     time.Time     `json:"verified_at"`
	UserStatus     string        `json:"user_status"`
	UserRole       string        `json:"user_role"`
	SectionAccess  []string      `json:"section_access"`
}

func (q *Queries) GetDistributionMappingByCRM(ctx context.Context, arg GetDistributionMappingByCRMParams) (GetDistributionMappingByCRMRow, error) {
	row := q.db.QueryRow(ctx, getDistributionMappingByCRM, arg.CompanyID, arg.BindingID, arg.CrmUserID)
	var i GetDistributionMappingByCRMRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BindingID,
		&i.UserID,
		&i.UserIDSnapshot,
		&i.CrmUserID,
		&i.State,
		&i.Revision,
		&i.VerifiedAt,
		&i.UserStatus,
		&i.UserRole,
		&i.SectionAccess,
	)
	return i, err
}

const getDistributionMappingSnapshot = `-- name: GetDistributionMappingSnapshot :one
SELECT payload FROM distribution_mapping_snapshots WHERE company_id=$1 AND binding_id=$2 AND revision=$3
`

type GetDistributionMappingSnapshotParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	BindingID uuid.UUID `json:"binding_id"`
	Revision  int64     `json:"revision"`
}

func (q *Queries) GetDistributionMappingSnapshot(ctx context.Context, arg GetDistributionMappingSnapshotParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDistributionMappingSnapshot, arg.CompanyID, arg.BindingID, arg.Revision)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}

const getDistributionServiceGrant = `-- name: GetDistributionServiceGrant :one
SELECT active FROM distribution_service_grants WHERE key_id=$1 AND company_id=$2 AND installation_id=$3 AND capability=$4
`

type GetDistributionServiceGrantParams struct {
	KeyID          string    `json:"key_id"`
	CompanyID      uuid.UUID `json:"company_id"`
	InstallationID uuid.UUID `json:"installation_id"`
	Capability     string    `json:"capability"`
}

func (q *Queries) GetDistributionServiceGrant(ctx context.Context, arg GetDistributionServiceGrantParams) (bool, error) {
	row := q.db.QueryRow(ctx, getDistributionServiceGrant,
		arg.KeyID,
		arg.CompanyID,
		arg.InstallationID,
		arg.Capability,
	)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const listDistributionBindings = `-- name: ListDistributionBindings :many
SELECT id, company_id, revision, installation_id, integration_id, account_id, state, mapping_revision, mapping_ack_revision, intent_id, initiated_by, initiator_snapshot, expires_at, created_at, updated_at, account_timezone, timezone_fetched_at, account_domain FROM distribution_bindings WHERE company_id=$1 ORDER BY created_at,id
`

func (q *Queries) ListDistributionBindings(ctx context.Context, companyID uuid.UUID) ([]DistributionBinding, error) {
	rows, err := q.db.Query(ctx, listDistributionBindings, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DistributionBinding{}
	for rows.Next() {
		var i DistributionBinding
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Revision,
			&i.InstallationID,
			&i.IntegrationID,
			&i.AccountID,
			&i.State,
			&i.MappingRevision,
			&i.MappingAckRevision,
			&i.IntentID,
			&i.InitiatedBy,
			&i.InitiatorSnapshot,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountTimezone,
			&i.TimezoneFetchedAt,
			&i.AccountDomain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistributionIdentityCandidates = `-- name: ListDistributionIdentityCandidates :many
SELECT u.id AS user_id,u.status,legacy.crm_user_id FROM users u
JOIN (
 SELECT lu.id AS user_id,lu.external_id AS crm_user_id FROM users lu WHERE lu.company_id=$1 AND lu.source='amo' AND lu.external_id IS NOT NULL
 AND EXISTS(SELECT 1 FROM companies lc WHERE lc.id=$1 AND lc.amo_account_id=$2)
 UNION
 SELECT xi.user_id,xi.external_user_id AS crm_user_id FROM user_external_identities xi
 WHERE xi.company_id=$1 AND xi.external_account_id=$2 AND xi.provider IN ('rakurs','amocrm')
) legacy ON legacy.user_id=u.id
WHERE u.company_id=$1 AND u.external_deleted_at IS NULL ORDER BY u.id,legacy.crm_user_id
`

type ListDistributionIdentityCandidatesParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	AccountID pgtype.Text `json:"account_id"`
}

type ListDistributionIdentityCandidatesRow struct {
	UserID    uuid.UUID   `json:"user_id"`
	Status    string      `json:"status"`
	CrmUserID pgtype.Text `json:"crm_user_id"`
}

func (q *Queries) ListDistributionIdentityCandidates(ctx context.Context, arg ListDistributionIdentityCandidatesParams) ([]ListDistributionIdentityCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listDistributionIdentityCandidates, arg.CompanyID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistributionIdentityCandidatesRow{}
	for rows.Next() {
		var i ListDistributionIdentityCandidatesRow
		if err := rows.Scan(&i.UserID, &i.Status, &i.CrmUserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistributionMappings = `-- name: ListDistributionMappings :many
SELECT m.id, m.company_id, m.binding_id, m.user_id, m.user_id_snapshot, m.crm_user_id, m.state, m.revision, m.verified_at FROM distribution_employee_mappings m WHERE m.company_id=$1 AND m.binding_id=$2 ORDER BY m.user_id
`

type ListDistributionMappingsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	BindingID uuid.UUID `json:"binding_id"`
}

func (q *Queries) ListDistributionMappings(ctx context.Context, arg ListDistributionMappingsParams) ([]DistributionEmployeeMapping, error) {
	rows, err := q.db.Query(ctx, listDistributionMappings, arg.CompanyID, arg.BindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DistributionEmployeeMapping{}
	for rows.Next() {
		var i DistributionEmployeeMapping
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.BindingID,
			&i.UserID,
			&i.UserIDSnapshot,
			&i.CrmUserID,
			&i.State,
			&i.Revision,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDistributionCompany = `-- name: LockDistributionCompany :one
SELECT id FROM companies WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockDistributionCompany(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockDistributionCompany, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const nextDistributionMappingRevision = `-- name: NextDistributionMappingRevision :one
UPDATE distribution_bindings SET mapping_revision=mapping_revision+1 WHERE company_id=$1 AND id=$2 AND state='active' RETURNING mapping_revision
`

type NextDistributionMappingRevisionParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) NextDistributionMappingRevision(ctx context.Context, arg NextDistributionMappingRevisionParams) (int64, error) {
	row := q.db.QueryRow(ctx, nextDistributionMappingRevision, arg.CompanyID, arg.ID)
	var mapping_revision int64
	err := row.Scan(&mapping_revision)
	return mapping_revision, err
}

const recordDistributionBindingVersion = `-- name: RecordDistributionBindingVersion :exec
INSERT INTO distribution_binding_versions(company_id,binding_id,revision,installation_id,integration_id,account_id,state)
SELECT company_id,id,revision,installation_id,integration_id,account_id,state FROM distribution_bindings WHERE distribution_bindings.company_id=$1 AND distribution_bindings.id=$2
ON CONFLICT DO NOTHING
`

type RecordDistributionBindingVersionParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) RecordDistributionBindingVersion(ctx context.Context, arg RecordDistributionBindingVersionParams) error {
	_, err := q.db.Exec(ctx, recordDistributionBindingVersion, arg.CompanyID, arg.ID)
	return err
}

const revokeDistributionBinding = `-- name: RevokeDistributionBinding :one
UPDATE distribution_bindings SET state='revoked',revision=revision+1,updated_at=now() WHERE company_id=$1 AND id=$2 AND state <> 'revoked' RETURNING id, company_id, revision, installation_id, integration_id, account_id, state, mapping_revision, mapping_ack_revision, intent_id, initiated_by, initiator_snapshot, expires_at, created_at, updated_at, account_timezone, timezone_fetched_at, account_domain
`

type RevokeDistributionBindingParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) RevokeDistributionBinding(ctx context.Context, arg RevokeDistributionBindingParams) (DistributionBinding, error) {
	row := q.db.QueryRow(ctx, revokeDistributionBinding, arg.CompanyID, arg.ID)
	var i DistributionBinding
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Revision,
		&i.InstallationID,
		&i.IntegrationID,
		&i.AccountID,
		&i.State,
		&i.MappingRevision,
		&i.MappingAckRevision,
		&i.IntentID,
		&i.InitiatedBy,
		&i.InitiatorSnapshot,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountTimezone,
		&i.TimezoneFetchedAt,
		&i.AccountDomain,
	)
	return i, err
}

const setDistributionMappingState = `-- name: SetDistributionMappingState :exec
UPDATE distribution_employee_mappings SET state=$4,revision=revision+1,verified_at=$5 WHERE company_id=$1 AND binding_id=$2 AND id=$3 AND state <> $4
`

type SetDistributionMappingStateParams struct {
	CompanyID  uuid.UUID `json:"company_id"`
	BindingID  uuid.UUID `json:"binding_id"`
	ID         uuid.UUID `json:"id"`
	State      string    `json:"state"`
	VerifiedAt time.Time `json:"verified_at"`
}

func (q *Queries) SetDistributionMappingState(ctx context.Context, arg SetDistributionMappingStateParams) error {
	_, err := q.db.Exec(ctx, setDistributionMappingState,
		arg.CompanyID,
		arg.BindingID,
		arg.ID,
		arg.State,
		arg.VerifiedAt,
	)
	return err
}

const storeDistributionMappingSnapshot = `-- name: StoreDistributionMappingSnapshot :exec
INSERT INTO distribution_mapping_snapshots(company_id,binding_id,revision,payload) VALUES($1,$2,$3,$4)
`

type StoreDistributionMappingSnapshotParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	BindingID uuid.UUID `json:"binding_id"`
	Revision  int64     `json:"revision"`
	Payload   []byte    `json:"payload"`
}

func (q *Queries) StoreDistributionMappingSnapshot(ctx context.Context, arg StoreDistributionMappingSnapshotParams) error {
	_, err := q.db.Exec(ctx, storeDistributionMappingSnapshot,
		arg.CompanyID,
		arg.BindingID,
		arg.Revision,
		arg.Payload,
	)
	return err
}

const upsertDistributionMapping = `-- name: UpsertDistributionMapping :one
INSERT INTO distribution_employee_mappings(id,company_id,binding_id,user_id,user_id_snapshot,crm_user_id,state,verified_at)
VALUES($1,$2,$3,$4,$4,$5,$6,$7)
ON CONFLICT(company_id,binding_id,user_id) DO UPDATE SET crm_user_id=EXCLUDED.crm_user_id,state=EXCLUDED.state,revision=distribution_employee_mappings.revision+1,verified_at=EXCLUDED.verified_at
RETURNING id, company_id, binding_id, user_id, user_id_snapshot, crm_user_id, state, revision, verified_at
`

type UpsertDistributionMappingParams struct {
	ID         uuid.UUID     `json:"id"`
	CompanyID  uuid.UUID     `json:"company_id"`
	BindingID  uuid.UUID     `json:"binding_id"`
	UserID     uuid.NullUUID `json:"user_id"`
	CrmUserID  string        `json:"crm_user_id"`
	State      string        `json:"state"`
	VerifiedAt time.Time     `json:"verified_at"`
}

func (q *Queries) UpsertDistributionMapping(ctx context.Context, arg UpsertDistributionMappingParams) (DistributionEmployeeMapping, error) {
	row := q.db.QueryRow(ctx, upsertDistributionMapping,
		arg.ID,
		arg.CompanyID,
		arg.BindingID,
		arg.UserID,
		arg.CrmUserID,
		arg.State,
		arg.VerifiedAt,
	)
	var i DistributionEmployeeMapping
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BindingID,
		&i.UserID,
		&i.UserIDSnapshot,
		&i.CrmUserID,
		&i.State,
		&i.Revision,
		&i.VerifiedAt,
	)
	return i, err
}
