// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: distribution.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDistributionEvent = `-- name: CreateDistributionEvent :one
INSERT INTO distribution_events (
    id, company_id, group_id, deal_number, user_id, status
)
VALUES ($1, $2, $3, nextval('distribution_deal_numbers'), $4, 'accepted')
RETURNING id, company_id, group_id, deal_number, user_id, status, created_at
`

type CreateDistributionEventParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	GroupID   uuid.UUID `json:"group_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateDistributionEvent(ctx context.Context, arg CreateDistributionEventParams) (DistributionEvent, error) {
	row := q.db.QueryRow(ctx, createDistributionEvent,
		arg.ID,
		arg.CompanyID,
		arg.GroupID,
		arg.UserID,
	)
	var i DistributionEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.GroupID,
		&i.DealNumber,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createDistributionGroup = `-- name: CreateDistributionGroup :one
INSERT INTO distribution_groups (
    id, company_id, name, description, member_ids
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, company_id, name, description, active, algorithm, member_ids, disabled_member_ids, source, deal_limit, unclaimed_minutes, created_at, updated_at
`

type CreateDistributionGroupParams struct {
	ID          uuid.UUID   `json:"id"`
	CompanyID   uuid.UUID   `json:"company_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	MemberIds   []uuid.UUID `json:"member_ids"`
}

func (q *Queries) CreateDistributionGroup(ctx context.Context, arg CreateDistributionGroupParams) (DistributionGroup, error) {
	row := q.db.QueryRow(ctx, createDistributionGroup,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.Description,
		arg.MemberIds,
	)
	var i DistributionGroup
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.Algorithm,
		&i.MemberIds,
		&i.DisabledMemberIds,
		&i.Source,
		&i.DealLimit,
		&i.UnclaimedMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDistributionGroup = `-- name: DeleteDistributionGroup :execrows
DELETE FROM distribution_groups WHERE company_id = $1 AND id = $2
`

type DeleteDistributionGroupParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) DeleteDistributionGroup(ctx context.Context, arg DeleteDistributionGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDistributionGroup, arg.CompanyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDistributionGroup = `-- name: GetDistributionGroup :one
SELECT id, company_id, name, description, active, algorithm, member_ids, disabled_member_ids, source, deal_limit, unclaimed_minutes, created_at, updated_at FROM distribution_groups WHERE company_id = $1 AND id = $2
`

type GetDistributionGroupParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetDistributionGroup(ctx context.Context, arg GetDistributionGroupParams) (DistributionGroup, error) {
	row := q.db.QueryRow(ctx, getDistributionGroup, arg.CompanyID, arg.ID)
	var i DistributionGroup
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.Algorithm,
		&i.MemberIds,
		&i.DisabledMemberIds,
		&i.Source,
		&i.DealLimit,
		&i.UnclaimedMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDistributionGroupForUpdate = `-- name: GetDistributionGroupForUpdate :one
SELECT id, company_id, name, description, active, algorithm, member_ids, disabled_member_ids, source, deal_limit, unclaimed_minutes, created_at, updated_at FROM distribution_groups WHERE company_id = $1 AND id = $2 FOR UPDATE
`

type GetDistributionGroupForUpdateParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetDistributionGroupForUpdate(ctx context.Context, arg GetDistributionGroupForUpdateParams) (DistributionGroup, error) {
	row := q.db.QueryRow(ctx, getDistributionGroupForUpdate, arg.CompanyID, arg.ID)
	var i DistributionGroup
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.Algorithm,
		&i.MemberIds,
		&i.DisabledMemberIds,
		&i.Source,
		&i.DealLimit,
		&i.UnclaimedMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDistributionEvents = `-- name: ListDistributionEvents :many
SELECT id, company_id, group_id, deal_number, user_id, status, created_at FROM distribution_events WHERE company_id = $1 AND group_id = $2 ORDER BY created_at DESC, id DESC
`

type ListDistributionEventsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	GroupID   uuid.UUID `json:"group_id"`
}

func (q *Queries) ListDistributionEvents(ctx context.Context, arg ListDistributionEventsParams) ([]DistributionEvent, error) {
	rows, err := q.db.Query(ctx, listDistributionEvents, arg.CompanyID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DistributionEvent{}
	for rows.Next() {
		var i DistributionEvent
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.GroupID,
			&i.DealNumber,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistributionGroups = `-- name: ListDistributionGroups :many
SELECT id, company_id, name, description, active, algorithm, member_ids, disabled_member_ids, source, deal_limit, unclaimed_minutes, created_at, updated_at FROM distribution_groups WHERE company_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListDistributionGroups(ctx context.Context, companyID uuid.UUID) ([]DistributionGroup, error) {
	rows, err := q.db.Query(ctx, listDistributionGroups, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DistributionGroup{}
	for rows.Next() {
		var i DistributionGroup
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.Active,
			&i.Algorithm,
			&i.MemberIds,
			&i.DisabledMemberIds,
			&i.Source,
			&i.DealLimit,
			&i.UnclaimedMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetDistributionEvents = `-- name: ResetDistributionEvents :execrows
DELETE FROM distribution_events WHERE company_id = $1 AND group_id = $2
`

type ResetDistributionEventsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	GroupID   uuid.UUID `json:"group_id"`
}

func (q *Queries) ResetDistributionEvents(ctx context.Context, arg ResetDistributionEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetDistributionEvents, arg.CompanyID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDistributionGroup = `-- name: UpdateDistributionGroup :one
UPDATE distribution_groups
SET name = CASE WHEN $1::boolean THEN $2 ELSE name END,
    description = CASE WHEN $3::boolean THEN $4 ELSE description END,
    active = CASE WHEN $5::boolean THEN $6 ELSE active END,
    algorithm = CASE WHEN $7::boolean THEN $8 ELSE algorithm END,
    member_ids = CASE WHEN $9::boolean THEN $10 ELSE member_ids END,
    disabled_member_ids = CASE WHEN $11::boolean THEN $12 ELSE disabled_member_ids END,
    source = CASE WHEN $13::boolean THEN $14 ELSE source END,
    deal_limit = CASE WHEN $15::boolean THEN $16 ELSE deal_limit END,
    unclaimed_minutes = CASE WHEN $17::boolean THEN $18 ELSE unclaimed_minutes END,
    updated_at = now()
WHERE company_id = $19 AND id = $20
RETURNING id, company_id, name, description, active, algorithm, member_ids, disabled_member_ids, source, deal_limit, unclaimed_minutes, created_at, updated_at
`

type UpdateDistributionGroupParams struct {
	SetName              bool        `json:"set_name"`
	Name                 string      `json:"name"`
	SetDescription       bool        `json:"set_description"`
	Description          pgtype.Text `json:"description"`
	SetActive            bool        `json:"set_active"`
	Active               bool        `json:"active"`
	SetAlgorithm         bool        `json:"set_algorithm"`
	Algorithm            string      `json:"algorithm"`
	SetMemberIds         bool        `json:"set_member_ids"`
	MemberIds            []uuid.UUID `json:"member_ids"`
	SetDisabledMemberIds bool        `json:"set_disabled_member_ids"`
	DisabledMemberIds    []uuid.UUID `json:"disabled_member_ids"`
	SetSource            bool        `json:"set_source"`
	Source               string      `json:"source"`
	SetDealLimit         bool        `json:"set_deal_limit"`
	DealLimit            int32       `json:"deal_limit"`
	SetUnclaimedMinutes  bool        `json:"set_unclaimed_minutes"`
	UnclaimedMinutes     int32       `json:"unclaimed_minutes"`
	CompanyID            uuid.UUID   `json:"company_id"`
	ID                   uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateDistributionGroup(ctx context.Context, arg UpdateDistributionGroupParams) (DistributionGroup, error) {
	row := q.db.QueryRow(ctx, updateDistributionGroup,
		arg.SetName,
		arg.Name,
		arg.SetDescription,
		arg.Description,
		arg.SetActive,
		arg.Active,
		arg.SetAlgorithm,
		arg.Algorithm,
		arg.SetMemberIds,
		arg.MemberIds,
		arg.SetDisabledMemberIds,
		arg.DisabledMemberIds,
		arg.SetSource,
		arg.Source,
		arg.SetDealLimit,
		arg.DealLimit,
		arg.SetUnclaimedMinutes,
		arg.UnclaimedMinutes,
		arg.CompanyID,
		arg.ID,
	)
	var i DistributionGroup
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.Algorithm,
		&i.MemberIds,
		&i.DisabledMemberIds,
		&i.Source,
		&i.DealLimit,
		&i.UnclaimedMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
