// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignAmoUserDepartment = `-- name: AssignAmoUserDepartment :execrows
INSERT INTO user_departments (company_id, user_id, department_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id)
DO UPDATE SET
    company_id = EXCLUDED.company_id,
    department_id = EXCLUDED.department_id
WHERE user_departments.company_id = EXCLUDED.company_id
  AND user_departments.department_id IS DISTINCT FROM EXCLUDED.department_id
`

type AssignAmoUserDepartmentParams struct {
	CompanyID    uuid.UUID `json:"company_id"`
	UserID       uuid.UUID `json:"user_id"`
	DepartmentID uuid.UUID `json:"department_id"`
}

func (q *Queries) AssignAmoUserDepartment(ctx context.Context, arg AssignAmoUserDepartmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignAmoUserDepartment, arg.CompanyID, arg.UserID, arg.DepartmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const assignUserPosition = `-- name: AssignUserPosition :exec
INSERT INTO user_positions (company_id, user_id, position_id)
VALUES ($1, $2, $3)
`

type AssignUserPositionParams struct {
	CompanyID  uuid.UUID `json:"company_id"`
	UserID     uuid.UUID `json:"user_id"`
	PositionID uuid.UUID `json:"position_id"`
}

func (q *Queries) AssignUserPosition(ctx context.Context, arg AssignUserPositionParams) error {
	_, err := q.db.Exec(ctx, assignUserPosition, arg.CompanyID, arg.UserID, arg.PositionID)
	return err
}

const clearAmoUserDepartment = `-- name: ClearAmoUserDepartment :execrows
DELETE FROM user_departments AS assignment
USING departments AS department
WHERE assignment.company_id = $1
  AND assignment.user_id = $2
  AND department.company_id = assignment.company_id
  AND department.id = assignment.department_id
  AND department.source = 'amo'
`

type ClearAmoUserDepartmentParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) ClearAmoUserDepartment(ctx context.Context, arg ClearAmoUserDepartmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearAmoUserDepartment, arg.CompanyID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearAmoUserTombstone = `-- name: ClearAmoUserTombstone :one
UPDATE users
SET external_deleted_at = NULL,
    updated_at = now()
WHERE company_id = $1
  AND id = $2
  AND source = 'amo'
  AND external_deleted_at IS NOT NULL
RETURNING id, company_id, email, first_name, last_name, phone, avatar_url, role, status, birth_date, hired_at, vacation_allowance, created_at, updated_at, source, external_id, external_group_id, external_group_name, avatar_source, external_deleted_at, show_in_schedule
`

type ClearAmoUserTombstoneParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) ClearAmoUserTombstone(ctx context.Context, arg ClearAmoUserTombstoneParams) (User, error) {
	row := q.db.QueryRow(ctx, clearAmoUserTombstone, arg.CompanyID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.BirthDate,
		&i.HiredAt,
		&i.VacationAllowance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ExternalID,
		&i.ExternalGroupID,
		&i.ExternalGroupName,
		&i.AvatarSource,
		&i.ExternalDeletedAt,
		&i.ShowInSchedule,
	)
	return i, err
}

const countDepartmentChildren = `-- name: CountDepartmentChildren :one
SELECT count(*) FROM departments WHERE company_id = $1 AND parent_id = $2
`

type CountDepartmentChildrenParams struct {
	CompanyID uuid.UUID     `json:"company_id"`
	ParentID  uuid.NullUUID `json:"parent_id"`
}

func (q *Queries) CountDepartmentChildren(ctx context.Context, arg CountDepartmentChildrenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDepartmentChildren, arg.CompanyID, arg.ParentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDepartmentPositions = `-- name: CountDepartmentPositions :one
SELECT count(*) FROM positions WHERE company_id = $1 AND department_id = $2
`

type CountDepartmentPositionsParams struct {
	CompanyID    uuid.UUID `json:"company_id"`
	DepartmentID uuid.UUID `json:"department_id"`
}

func (q *Queries) CountDepartmentPositions(ctx context.Context, arg CountDepartmentPositionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDepartmentPositions, arg.CompanyID, arg.DepartmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAmoUser = `-- name: CreateAmoUser :one
INSERT INTO users (
    id, company_id, email, first_name, last_name, avatar_url, avatar_source,
    role, status, source, external_id, external_group_id, external_group_name
)
VALUES ($1, $2, $3, $4, $5, $6, $10,
    'employee', 'active', 'amo', $7, $8, $9)
RETURNING id, company_id, email, first_name, last_name, phone, avatar_url, role, status, birth_date, hired_at, vacation_allowance, created_at, updated_at, source, external_id, external_group_id, external_group_name, avatar_source, external_deleted_at, show_in_schedule
`

type CreateAmoUserParams struct {
	ID                uuid.UUID   `json:"id"`
	CompanyID         uuid.UUID   `json:"company_id"`
	Email             string      `json:"email"`
	FirstName         string      `json:"first_name"`
	LastName          pgtype.Text `json:"last_name"`
	AvatarUrl         pgtype.Text `json:"avatar_url"`
	ExternalID        pgtype.Text `json:"external_id"`
	ExternalGroupID   pgtype.Text `json:"external_group_id"`
	ExternalGroupName pgtype.Text `json:"external_group_name"`
	AvatarSource      pgtype.Text `json:"avatar_source"`
}

func (q *Queries) CreateAmoUser(ctx context.Context, arg CreateAmoUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createAmoUser,
		arg.ID,
		arg.CompanyID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
		arg.ExternalID,
		arg.ExternalGroupID,
		arg.ExternalGroupName,
		arg.AvatarSource,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.BirthDate,
		&i.HiredAt,
		&i.VacationAllowance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ExternalID,
		&i.ExternalGroupID,
		&i.ExternalGroupName,
		&i.AvatarSource,
		&i.ExternalDeletedAt,
		&i.ShowInSchedule,
	)
	return i, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (
    id, company_id, name, parent_id, head_user_id, valuable_final_product, "order"
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    (SELECT count(*) FROM departments WHERE company_id = $2 AND parent_id IS NOT DISTINCT FROM $4)
)
RETURNING id, company_id, name, parent_id, head_user_id, valuable_final_product, "order", created_at, updated_at, source, external_id
`

type CreateDepartmentParams struct {
	ID                   uuid.UUID     `json:"id"`
	CompanyID            uuid.UUID     `json:"company_id"`
	Name                 string        `json:"name"`
	ParentID             uuid.NullUUID `json:"parent_id"`
	HeadUserID           uuid.NullUUID `json:"head_user_id"`
	ValuableFinalProduct pgtype.Text   `json:"valuable_final_product"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.ParentID,
		arg.HeadUserID,
		arg.ValuableFinalProduct,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ParentID,
		&i.HeadUserID,
		&i.ValuableFinalProduct,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ExternalID,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (
    id, company_id, email, token, role, position_id, department_id, invited_by_id, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, company_id, email, token, role, position_id, department_id, invited_by_id, status, expires_at, created_at, updated_at
`

type CreateInviteParams struct {
	ID           uuid.UUID     `json:"id"`
	CompanyID    uuid.UUID     `json:"company_id"`
	Email        pgtype.Text   `json:"email"`
	Token        string        `json:"token"`
	Role         string        `json:"role"`
	PositionID   uuid.NullUUID `json:"position_id"`
	DepartmentID uuid.NullUUID `json:"department_id"`
	InvitedByID  uuid.UUID     `json:"invited_by_id"`
	ExpiresAt    time.Time     `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.ID,
		arg.CompanyID,
		arg.Email,
		arg.Token,
		arg.Role,
		arg.PositionID,
		arg.DepartmentID,
		arg.InvitedByID,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.PositionID,
		&i.DepartmentID,
		&i.InvitedByID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (id, company_id, name, department_id, level, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, name, department_id, level, description, article_ids, required_course_ids, created_at, updated_at
`

type CreatePositionParams struct {
	ID           uuid.UUID   `json:"id"`
	CompanyID    uuid.UUID   `json:"company_id"`
	Name         string      `json:"name"`
	DepartmentID uuid.UUID   `json:"department_id"`
	Level        int16       `json:"level"`
	Description  pgtype.Text `json:"description"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, createPosition,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.DepartmentID,
		arg.Level,
		arg.Description,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.DepartmentID,
		&i.Level,
		&i.Description,
		&i.ArticleIds,
		&i.RequiredCourseIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserAdminAudit = `-- name: CreateUserAdminAudit :exec
INSERT INTO user_admin_audit (
    id, company_id, target_user_id, actor_user_id, actor_kind, action,
    before_state, after_state, request_id, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateUserAdminAuditParams struct {
	ID           uuid.UUID     `json:"id"`
	CompanyID    uuid.UUID     `json:"company_id"`
	TargetUserID uuid.NullUUID `json:"target_user_id"`
	ActorUserID  uuid.NullUUID `json:"actor_user_id"`
	ActorKind    string        `json:"actor_kind"`
	Action       string        `json:"action"`
	BeforeState  []byte        `json:"before_state"`
	AfterState   []byte        `json:"after_state"`
	RequestID    pgtype.Text   `json:"request_id"`
	CreatedAt    time.Time     `json:"created_at"`
}

func (q *Queries) CreateUserAdminAudit(ctx context.Context, arg CreateUserAdminAuditParams) error {
	_, err := q.db.Exec(ctx, createUserAdminAudit,
		arg.ID,
		arg.CompanyID,
		arg.TargetUserID,
		arg.ActorUserID,
		arg.ActorKind,
		arg.Action,
		arg.BeforeState,
		arg.AfterState,
		arg.RequestID,
		arg.CreatedAt,
	)
	return err
}

const deleteDepartment = `-- name: DeleteDepartment :execrows
DELETE FROM departments WHERE company_id = $1 AND id = $2
`

type DeleteDepartmentParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) DeleteDepartment(ctx context.Context, arg DeleteDepartmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDepartment, arg.CompanyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEmployeeSectionAccess = `-- name: DeleteEmployeeSectionAccess :exec
DELETE FROM employee_section_access
WHERE company_id = $1 AND user_id = $2
`

type DeleteEmployeeSectionAccessParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteEmployeeSectionAccess(ctx context.Context, arg DeleteEmployeeSectionAccessParams) error {
	_, err := q.db.Exec(ctx, deleteEmployeeSectionAccess, arg.CompanyID, arg.UserID)
	return err
}

const deleteLocalUser = `-- name: DeleteLocalUser :execrows
DELETE FROM users
WHERE company_id = $1
  AND id = $2
  AND source = 'local'
`

type DeleteLocalUserParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) DeleteLocalUser(ctx context.Context, arg DeleteLocalUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLocalUser, arg.CompanyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePosition = `-- name: DeletePosition :execrows
DELETE FROM positions WHERE company_id = $1 AND id = $2
`

type DeletePositionParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) DeletePosition(ctx context.Context, arg DeletePositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePosition, arg.CompanyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserPositions = `-- name: DeleteUserPositions :exec
DELETE FROM user_positions WHERE company_id = $1 AND user_id = $2
`

type DeleteUserPositionsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteUserPositions(ctx context.Context, arg DeleteUserPositionsParams) error {
	_, err := q.db.Exec(ctx, deleteUserPositions, arg.CompanyID, arg.UserID)
	return err
}

const findUserForAmoSync = `-- name: FindUserForAmoSync :one
SELECT id, company_id, email, first_name, last_name, phone, avatar_url, role, status, birth_date, hired_at, vacation_allowance, created_at, updated_at, source, external_id, external_group_id, external_group_name, avatar_source, external_deleted_at, show_in_schedule
FROM users
WHERE company_id = $1
  AND (external_id = $2 OR email = $3)
ORDER BY (external_id = $2) DESC
LIMIT 1
`

type FindUserForAmoSyncParams struct {
	CompanyID  uuid.UUID   `json:"company_id"`
	ExternalID pgtype.Text `json:"external_id"`
	Email      string      `json:"email"`
}

func (q *Queries) FindUserForAmoSync(ctx context.Context, arg FindUserForAmoSyncParams) (User, error) {
	row := q.db.QueryRow(ctx, findUserForAmoSync, arg.CompanyID, arg.ExternalID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.BirthDate,
		&i.HiredAt,
		&i.VacationAllowance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ExternalID,
		&i.ExternalGroupID,
		&i.ExternalGroupName,
		&i.AvatarSource,
		&i.ExternalDeletedAt,
		&i.ShowInSchedule,
	)
	return i, err
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, company_id, name, parent_id, head_user_id, valuable_final_product, "order", created_at, updated_at, source, external_id FROM departments WHERE company_id = $1 AND id = $2
`

type GetDepartmentParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetDepartment(ctx context.Context, arg GetDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartment, arg.CompanyID, arg.ID)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ParentID,
		&i.HeadUserID,
		&i.ValuableFinalProduct,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ExternalID,
	)
	return i, err
}

const getInvite = `-- name: GetInvite :one
SELECT id, company_id, email, token, role, position_id, department_id, invited_by_id, status, expires_at, created_at, updated_at FROM invites WHERE company_id = $1 AND id = $2
`

type GetInviteParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetInvite(ctx context.Context, arg GetInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, getInvite, arg.CompanyID, arg.ID)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.PositionID,
		&i.DepartmentID,
		&i.InvitedByID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPosition = `-- name: GetPosition :one
SELECT id, company_id, name, department_id, level, description, article_ids, required_course_ids, created_at, updated_at FROM positions WHERE company_id = $1 AND id = $2
`

type GetPositionParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetPosition(ctx context.Context, arg GetPositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, getPosition, arg.CompanyID, arg.ID)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.DepartmentID,
		&i.Level,
		&i.Description,
		&i.ArticleIds,
		&i.RequiredCourseIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPositionUserIDs = `-- name: GetPositionUserIDs :many
SELECT up.user_id
FROM user_positions up
JOIN users u ON u.id = up.user_id AND u.company_id = up.company_id
WHERE up.company_id = $1 AND up.position_id = $2
  AND u.status = 'active' AND u.external_deleted_at IS NULL
ORDER BY up.user_id
`

type GetPositionUserIDsParams struct {
	CompanyID  uuid.UUID `json:"company_id"`
	PositionID uuid.UUID `json:"position_id"`
}

func (q *Queries) GetPositionUserIDs(ctx context.Context, arg GetPositionUserIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getPositionUserIDs, arg.CompanyID, arg.PositionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSystemDepartment = `-- name: GetSystemDepartment :one
SELECT id, company_id, name, parent_id, head_user_id, valuable_final_product, "order", created_at, updated_at, source, external_id FROM departments WHERE company_id = $1 AND source = 'system'
`

func (q *Queries) GetSystemDepartment(ctx context.Context, companyID uuid.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, getSystemDepartment, companyID)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ParentID,
		&i.HeadUserID,
		&i.ValuableFinalProduct,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ExternalID,
	)
	return i, err
}

const getUserWithPositions = `-- name: GetUserWithPositions :one
SELECT u.id, u.company_id, u.email, u.first_name, u.last_name, u.phone, u.avatar_url, u.role, u.status, u.birth_date, u.hired_at, u.vacation_allowance, u.created_at, u.updated_at, u.source, u.external_id, u.external_group_id, u.external_group_name, u.avatar_source, u.external_deleted_at, u.show_in_schedule,
       COALESCE(array_agg(up.position_id) FILTER (WHERE up.position_id IS NOT NULL), '{}')::uuid[] AS position_ids,
       ARRAY(
           SELECT assignment.department_id
           FROM user_departments AS assignment
           WHERE assignment.company_id = u.company_id AND assignment.user_id = u.id
       )::uuid[] AS department_ids,
       ARRAY(
           SELECT access.section
           FROM employee_section_access access
           WHERE access.company_id = u.company_id AND access.user_id = u.id
           ORDER BY access.section
       )::text[] AS section_access,
       CASE
           WHEN EXISTS (SELECT 1 FROM access_links access WHERE access.company_id = u.company_id AND access.user_id = u.id) THEN 'link'
           WHEN EXISTS (SELECT 1 FROM credentials credential WHERE credential.company_id = u.company_id AND credential.user_id = u.id) THEN 'password'
           ELSE 'none'
       END::text AS access_mode
FROM users u
LEFT JOIN user_positions up ON up.user_id = u.id
WHERE u.company_id = $1 AND u.id = $2 AND u.external_deleted_at IS NULL
GROUP BY u.id
`

type GetUserWithPositionsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

type GetUserWithPositionsRow struct {
	ID                uuid.UUID          `json:"id"`
	CompanyID         uuid.UUID          `json:"company_id"`
	Email             string             `json:"email"`
	FirstName         string             `json:"first_name"`
	LastName          pgtype.Text        `json:"last_name"`
	Phone             pgtype.Text        `json:"phone"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Role              string             `json:"role"`
	Status            string             `json:"status"`
	BirthDate         pgtype.Date        `json:"birth_date"`
	HiredAt           pgtype.Date        `json:"hired_at"`
	VacationAllowance pgtype.Int2        `json:"vacation_allowance"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	Source            string             `json:"source"`
	ExternalID        pgtype.Text        `json:"external_id"`
	ExternalGroupID   pgtype.Text        `json:"external_group_id"`
	ExternalGroupName pgtype.Text        `json:"external_group_name"`
	AvatarSource      pgtype.Text        `json:"avatar_source"`
	ExternalDeletedAt pgtype.Timestamptz `json:"external_deleted_at"`
	ShowInSchedule    bool               `json:"show_in_schedule"`
	PositionIds       []uuid.UUID        `json:"position_ids"`
	DepartmentIds     []uuid.UUID        `json:"department_ids"`
	SectionAccess     []string           `json:"section_access"`
	AccessMode        string             `json:"access_mode"`
}

func (q *Queries) GetUserWithPositions(ctx context.Context, arg GetUserWithPositionsParams) (GetUserWithPositionsRow, error) {
	row := q.db.QueryRow(ctx, getUserWithPositions, arg.CompanyID, arg.ID)
	var i GetUserWithPositionsRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.BirthDate,
		&i.HiredAt,
		&i.VacationAllowance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ExternalID,
		&i.ExternalGroupID,
		&i.ExternalGroupName,
		&i.AvatarSource,
		&i.ExternalDeletedAt,
		&i.ShowInSchedule,
		&i.PositionIds,
		&i.DepartmentIds,
		&i.SectionAccess,
		&i.AccessMode,
	)
	return i, err
}

const grantEmployeeSectionAccess = `-- name: GrantEmployeeSectionAccess :exec
INSERT INTO employee_section_access (company_id, user_id, section, granted_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, section) DO NOTHING
`

type GrantEmployeeSectionAccessParams struct {
	CompanyID uuid.UUID     `json:"company_id"`
	UserID    uuid.UUID     `json:"user_id"`
	Section   string        `json:"section"`
	GrantedBy uuid.NullUUID `json:"granted_by"`
}

func (q *Queries) GrantEmployeeSectionAccess(ctx context.Context, arg GrantEmployeeSectionAccessParams) error {
	_, err := q.db.Exec(ctx, grantEmployeeSectionAccess,
		arg.CompanyID,
		arg.UserID,
		arg.Section,
		arg.GrantedBy,
	)
	return err
}

const listAmoUsersForReconciliation = `-- name: ListAmoUsersForReconciliation :many
SELECT id, company_id, email, first_name, last_name, phone, avatar_url, role, status, birth_date, hired_at, vacation_allowance, created_at, updated_at, source, external_id, external_group_id, external_group_name, avatar_source, external_deleted_at, show_in_schedule
FROM users
WHERE company_id = $1
  AND source = 'amo'
  AND external_id IS NOT NULL
FOR UPDATE
`

func (q *Queries) ListAmoUsersForReconciliation(ctx context.Context, companyID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listAmoUsersForReconciliation, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.AvatarUrl,
			&i.Role,
			&i.Status,
			&i.BirthDate,
			&i.HiredAt,
			&i.VacationAllowance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.ExternalID,
			&i.ExternalGroupID,
			&i.ExternalGroupName,
			&i.AvatarSource,
			&i.ExternalDeletedAt,
			&i.ShowInSchedule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, company_id, name, parent_id, head_user_id, valuable_final_product, "order", created_at, updated_at, source, external_id FROM departments
WHERE company_id = $1
ORDER BY parent_id NULLS FIRST, "order", name
`

func (q *Queries) ListDepartments(ctx context.Context, companyID uuid.UUID) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Department{}
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.ParentID,
			&i.HeadUserID,
			&i.ValuableFinalProduct,
			&i.Order,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeSectionAccess = `-- name: ListEmployeeSectionAccess :many
SELECT section
FROM employee_section_access
WHERE company_id = $1 AND user_id = $2
ORDER BY section
`

type ListEmployeeSectionAccessParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) ListEmployeeSectionAccess(ctx context.Context, arg ListEmployeeSectionAccessParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listEmployeeSectionAccess, arg.CompanyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var section string
		if err := rows.Scan(&section); err != nil {
			return nil, err
		}
		items = append(items, section)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvites = `-- name: ListInvites :many
SELECT id, company_id, email, token, role, position_id, department_id, invited_by_id, status, expires_at, created_at, updated_at FROM invites WHERE company_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInvites(ctx context.Context, companyID uuid.UUID) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvites, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Email,
			&i.Token,
			&i.Role,
			&i.PositionID,
			&i.DepartmentID,
			&i.InvitedByID,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositions = `-- name: ListPositions :many
SELECT id, company_id, name, department_id, level, description, article_ids, required_course_ids, created_at, updated_at FROM positions WHERE company_id = $1 ORDER BY name
`

func (q *Queries) ListPositions(ctx context.Context, companyID uuid.UUID) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositions, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.DepartmentID,
			&i.Level,
			&i.Description,
			&i.ArticleIds,
			&i.RequiredCourseIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.company_id, u.email, u.first_name, u.last_name, u.phone, u.avatar_url, u.role, u.status, u.birth_date, u.hired_at, u.vacation_allowance, u.created_at, u.updated_at, u.source, u.external_id, u.external_group_id, u.external_group_name, u.avatar_source, u.external_deleted_at, u.show_in_schedule,
       COALESCE(array_agg(up.position_id) FILTER (WHERE up.position_id IS NOT NULL), '{}')::uuid[] AS position_ids,
       ARRAY(
           SELECT assignment.department_id
           FROM user_departments AS assignment
           WHERE assignment.company_id = u.company_id AND assignment.user_id = u.id
       )::uuid[] AS department_ids,
       ARRAY(
           SELECT access.section
           FROM employee_section_access access
           WHERE access.company_id = u.company_id AND access.user_id = u.id
           ORDER BY access.section
       )::text[] AS section_access,
       CASE
           WHEN EXISTS (SELECT 1 FROM access_links access WHERE access.company_id = u.company_id AND access.user_id = u.id) THEN 'link'
           WHEN EXISTS (SELECT 1 FROM credentials credential WHERE credential.company_id = u.company_id AND credential.user_id = u.id) THEN 'password'
           ELSE 'none'
       END::text AS access_mode
FROM users u
LEFT JOIN user_positions up ON up.user_id = u.id
WHERE u.company_id = $1 AND u.external_deleted_at IS NULL
GROUP BY u.id
ORDER BY u.created_at, u.id
`

type ListUsersRow struct {
	ID                uuid.UUID          `json:"id"`
	CompanyID         uuid.UUID          `json:"company_id"`
	Email             string             `json:"email"`
	FirstName         string             `json:"first_name"`
	LastName          pgtype.Text        `json:"last_name"`
	Phone             pgtype.Text        `json:"phone"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Role              string             `json:"role"`
	Status            string             `json:"status"`
	BirthDate         pgtype.Date        `json:"birth_date"`
	HiredAt           pgtype.Date        `json:"hired_at"`
	VacationAllowance pgtype.Int2        `json:"vacation_allowance"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	Source            string             `json:"source"`
	ExternalID        pgtype.Text        `json:"external_id"`
	ExternalGroupID   pgtype.Text        `json:"external_group_id"`
	ExternalGroupName pgtype.Text        `json:"external_group_name"`
	AvatarSource      pgtype.Text        `json:"avatar_source"`
	ExternalDeletedAt pgtype.Timestamptz `json:"external_deleted_at"`
	ShowInSchedule    bool               `json:"show_in_schedule"`
	PositionIds       []uuid.UUID        `json:"position_ids"`
	DepartmentIds     []uuid.UUID        `json:"department_ids"`
	SectionAccess     []string           `json:"section_access"`
	AccessMode        string             `json:"access_mode"`
}

func (q *Queries) ListUsers(ctx context.Context, companyID uuid.UUID) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.AvatarUrl,
			&i.Role,
			&i.Status,
			&i.BirthDate,
			&i.HiredAt,
			&i.VacationAllowance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.ExternalID,
			&i.ExternalGroupID,
			&i.ExternalGroupName,
			&i.AvatarSource,
			&i.ExternalDeletedAt,
			&i.ShowInSchedule,
			&i.PositionIds,
			&i.DepartmentIds,
			&i.SectionAccess,
			&i.AccessMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAmoUserSync = `-- name: LockAmoUserSync :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::uuid::text, 0))
`

func (q *Queries) LockAmoUserSync(ctx context.Context, companyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockAmoUserSync, companyID)
	return err
}

const markAmoUserExternallyDeleted = `-- name: MarkAmoUserExternallyDeleted :one
UPDATE users
SET external_deleted_at = $1,
    updated_at = now()
WHERE company_id = $2
  AND id = $3
  AND source = 'amo'
  AND external_deleted_at IS NULL
RETURNING id, company_id, email, first_name, last_name, phone, avatar_url, role, status, birth_date, hired_at, vacation_allowance, created_at, updated_at, source, external_id, external_group_id, external_group_name, avatar_source, external_deleted_at, show_in_schedule
`

type MarkAmoUserExternallyDeletedParams struct {
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CompanyID uuid.UUID          `json:"company_id"`
	ID        uuid.UUID          `json:"id"`
}

func (q *Queries) MarkAmoUserExternallyDeleted(ctx context.Context, arg MarkAmoUserExternallyDeletedParams) (User, error) {
	row := q.db.QueryRow(ctx, markAmoUserExternallyDeleted, arg.DeletedAt, arg.CompanyID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.BirthDate,
		&i.HiredAt,
		&i.VacationAllowance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ExternalID,
		&i.ExternalGroupID,
		&i.ExternalGroupName,
		&i.AvatarSource,
		&i.ExternalDeletedAt,
		&i.ShowInSchedule,
	)
	return i, err
}

const moveDepartment = `-- name: MoveDepartment :one
UPDATE departments AS moving
SET parent_id = $3,
    "order" = (
        SELECT count(*)
        FROM departments AS sibling
        WHERE sibling.company_id = $1
          AND sibling.parent_id IS NOT DISTINCT FROM $3
          AND sibling.id <> $2
    ),
    updated_at = now()
WHERE moving.company_id = $1 AND moving.id = $2
RETURNING moving.id, moving.company_id, moving.name, moving.parent_id, moving.head_user_id, moving.valuable_final_product, moving."order", moving.created_at, moving.updated_at, moving.source, moving.external_id
`

type MoveDepartmentParams struct {
	CompanyID uuid.UUID     `json:"company_id"`
	ID        uuid.UUID     `json:"id"`
	ParentID  uuid.NullUUID `json:"parent_id"`
}

func (q *Queries) MoveDepartment(ctx context.Context, arg MoveDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, moveDepartment, arg.CompanyID, arg.ID, arg.ParentID)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ParentID,
		&i.HeadUserID,
		&i.ValuableFinalProduct,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ExternalID,
	)
	return i, err
}

const reassignUserInvites = `-- name: ReassignUserInvites :exec
UPDATE invites
SET invited_by_id = $1, updated_at = now()
WHERE company_id = $2 AND invited_by_id = $3
`

type ReassignUserInvitesParams struct {
	ReplacementUserID uuid.UUID `json:"replacement_user_id"`
	CompanyID         uuid.UUID `json:"company_id"`
	DeletedUserID     uuid.UUID `json:"deleted_user_id"`
}

func (q *Queries) ReassignUserInvites(ctx context.Context, arg ReassignUserInvitesParams) error {
	_, err := q.db.Exec(ctx, reassignUserInvites, arg.ReplacementUserID, arg.CompanyID, arg.DeletedUserID)
	return err
}

const resendInvite = `-- name: ResendInvite :one
UPDATE invites
SET created_at = $3, expires_at = $4, updated_at = $3
WHERE company_id = $1 AND id = $2 AND status = 'pending'
RETURNING id, company_id, email, token, role, position_id, department_id, invited_by_id, status, expires_at, created_at, updated_at
`

type ResendInviteParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) ResendInvite(ctx context.Context, arg ResendInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, resendInvite,
		arg.CompanyID,
		arg.ID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.PositionID,
		&i.DepartmentID,
		&i.InvitedByID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeInvite = `-- name: RevokeInvite :one
UPDATE invites
SET status = 'expired', updated_at = now()
WHERE company_id = $1 AND id = $2 AND status <> 'accepted'
RETURNING id, company_id, email, token, role, position_id, department_id, invited_by_id, status, expires_at, created_at, updated_at
`

type RevokeInviteParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, revokeInvite, arg.CompanyID, arg.ID)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.PositionID,
		&i.DepartmentID,
		&i.InvitedByID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAmoUserGroup = `-- name: UpdateAmoUserGroup :execrows
UPDATE users
SET external_group_id = $1,
    external_group_name = $2,
    updated_at = now()
WHERE company_id = $3
  AND id = $4
  AND source = 'amo'
  AND (
      external_group_id IS DISTINCT FROM $1
      OR external_group_name IS DISTINCT FROM $2
  )
`

type UpdateAmoUserGroupParams struct {
	ExternalGroupID   pgtype.Text `json:"external_group_id"`
	ExternalGroupName pgtype.Text `json:"external_group_name"`
	CompanyID         uuid.UUID   `json:"company_id"`
	ID                uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateAmoUserGroup(ctx context.Context, arg UpdateAmoUserGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAmoUserGroup,
		arg.ExternalGroupID,
		arg.ExternalGroupName,
		arg.CompanyID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments
SET name = COALESCE($1, name),
    head_user_id = CASE WHEN $2::boolean THEN $3 ELSE head_user_id END,
    valuable_final_product = CASE WHEN $4::boolean THEN $5 ELSE valuable_final_product END,
    updated_at = now()
WHERE company_id = $6 AND id = $7
RETURNING id, company_id, name, parent_id, head_user_id, valuable_final_product, "order", created_at, updated_at, source, external_id
`

type UpdateDepartmentParams struct {
	Name                 pgtype.Text   `json:"name"`
	SetHead              bool          `json:"set_head"`
	HeadUserID           uuid.NullUUID `json:"head_user_id"`
	SetVfp               bool          `json:"set_vfp"`
	ValuableFinalProduct pgtype.Text   `json:"valuable_final_product"`
	CompanyID            uuid.UUID     `json:"company_id"`
	ID                   uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment,
		arg.Name,
		arg.SetHead,
		arg.HeadUserID,
		arg.SetVfp,
		arg.ValuableFinalProduct,
		arg.CompanyID,
		arg.ID,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ParentID,
		&i.HeadUserID,
		&i.ValuableFinalProduct,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ExternalID,
	)
	return i, err
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE positions
SET name = COALESCE($1, name),
    department_id = COALESCE($2, department_id),
    level = COALESCE($3, level),
    description = CASE WHEN $4::boolean THEN $5 ELSE description END,
    updated_at = now()
WHERE company_id = $6 AND id = $7
RETURNING id, company_id, name, department_id, level, description, article_ids, required_course_ids, created_at, updated_at
`

type UpdatePositionParams struct {
	Name           pgtype.Text   `json:"name"`
	DepartmentID   uuid.NullUUID `json:"department_id"`
	Level          pgtype.Int2   `json:"level"`
	SetDescription bool          `json:"set_description"`
	Description    pgtype.Text   `json:"description"`
	CompanyID      uuid.UUID     `json:"company_id"`
	ID             uuid.UUID     `json:"id"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, updatePosition,
		arg.Name,
		arg.DepartmentID,
		arg.Level,
		arg.SetDescription,
		arg.Description,
		arg.CompanyID,
		arg.ID,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.DepartmentID,
		&i.Level,
		&i.Description,
		&i.ArticleIds,
		&i.RequiredCourseIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name = COALESCE($1, first_name),
    last_name = COALESCE($2, last_name),
    phone = CASE WHEN $3::boolean THEN $4 ELSE phone END,
    birth_date = CASE WHEN $5::boolean THEN $6 ELSE birth_date END,
    hired_at = CASE WHEN $7::boolean THEN $8 ELSE hired_at END,
    vacation_allowance = CASE WHEN $9::boolean THEN $10 ELSE vacation_allowance END,
    show_in_schedule = CASE
        WHEN COALESCE($11, role) = 'owner' THEN false
        WHEN $12::boolean THEN $13::boolean
        ELSE show_in_schedule
    END,
    role = COALESCE($11, role),
    status = COALESCE($14, status),
    updated_at = now()
WHERE company_id = $15 AND id = $16
RETURNING id, company_id, email, first_name, last_name, phone, avatar_url, role, status, birth_date, hired_at, vacation_allowance, created_at, updated_at, source, external_id, external_group_id, external_group_name, avatar_source, external_deleted_at, show_in_schedule
`

type UpdateUserParams struct {
	FirstName         pgtype.Text `json:"first_name"`
	LastName          pgtype.Text `json:"last_name"`
	SetPhone          bool        `json:"set_phone"`
	Phone             pgtype.Text `json:"phone"`
	SetBirthDate      bool        `json:"set_birth_date"`
	BirthDate         pgtype.Date `json:"birth_date"`
	SetHiredAt        bool        `json:"set_hired_at"`
	HiredAt           pgtype.Date `json:"hired_at"`
	SetVacation       bool        `json:"set_vacation"`
	VacationAllowance pgtype.Int2 `json:"vacation_allowance"`
	Role              pgtype.Text `json:"role"`
	SetShowInSchedule bool        `json:"set_show_in_schedule"`
	ShowInSchedule    bool        `json:"show_in_schedule"`
	Status            pgtype.Text `json:"status"`
	CompanyID         uuid.UUID   `json:"company_id"`
	ID                uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.SetPhone,
		arg.Phone,
		arg.SetBirthDate,
		arg.BirthDate,
		arg.SetHiredAt,
		arg.HiredAt,
		arg.SetVacation,
		arg.VacationAllowance,
		arg.Role,
		arg.SetShowInSchedule,
		arg.ShowInSchedule,
		arg.Status,
		arg.CompanyID,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.BirthDate,
		&i.HiredAt,
		&i.VacationAllowance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ExternalID,
		&i.ExternalGroupID,
		&i.ExternalGroupName,
		&i.AvatarSource,
		&i.ExternalDeletedAt,
		&i.ShowInSchedule,
	)
	return i, err
}

const upsertAmoDepartment = `-- name: UpsertAmoDepartment :one
INSERT INTO departments (
    id, company_id, name, parent_id, "order", source, external_id
)
VALUES (
    $1, $2, $3,
    (
        SELECT root.id
        FROM departments AS root
        WHERE root.company_id = $2
          AND root.source = 'system'
    ),
    (
        SELECT COALESCE(max(department."order"), -1) + 1
        FROM departments AS department
        WHERE department.company_id = $2
          AND department.parent_id = (
              SELECT root.id
              FROM departments AS root
              WHERE root.company_id = $2
                AND root.source = 'system'
          )
    ),
    'amo', $4
)
ON CONFLICT (company_id, external_id) WHERE source = 'amo'
DO UPDATE SET
    name = EXCLUDED.name,
    updated_at = now()
RETURNING id, company_id, name, parent_id, head_user_id, valuable_final_product, "order", created_at, updated_at, source, external_id
`

type UpsertAmoDepartmentParams struct {
	ID         uuid.UUID   `json:"id"`
	CompanyID  uuid.UUID   `json:"company_id"`
	Name       string      `json:"name"`
	ExternalID pgtype.Text `json:"external_id"`
}

func (q *Queries) UpsertAmoDepartment(ctx context.Context, arg UpsertAmoDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, upsertAmoDepartment,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.ExternalID,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ParentID,
		&i.HeadUserID,
		&i.ValuableFinalProduct,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ExternalID,
	)
	return i, err
}
