// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provisioning.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateBootstrapUser = `-- name: ActivateBootstrapUser :one
UPDATE users
SET status = 'active', updated_at = $1
WHERE company_id = $2
  AND id = $3
  AND role = $4
  AND status = 'invited'
  AND external_deleted_at IS NULL
RETURNING id, company_id, email, first_name, last_name, phone, avatar_url, role, status, birth_date, hired_at, vacation_allowance, created_at, updated_at, source, external_id, external_group_id, external_group_name, avatar_source, external_deleted_at
`

type ActivateBootstrapUserParams struct {
	ActivatedAt time.Time `json:"activated_at"`
	CompanyID   uuid.UUID `json:"company_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
}

func (q *Queries) ActivateBootstrapUser(ctx context.Context, arg ActivateBootstrapUserParams) (User, error) {
	row := q.db.QueryRow(ctx, activateBootstrapUser,
		arg.ActivatedAt,
		arg.CompanyID,
		arg.UserID,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.BirthDate,
		&i.HiredAt,
		&i.VacationAllowance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ExternalID,
		&i.ExternalGroupID,
		&i.ExternalGroupName,
		&i.AvatarSource,
		&i.ExternalDeletedAt,
	)
	return i, err
}

const completeCompanyOnboarding = `-- name: CompleteCompanyOnboarding :one
UPDATE companies AS company
SET status = 'active', onboarding_completed_at = $1,
    updated_at = $1
WHERE company.id = $2
  AND company.status = 'onboarding'
  AND EXISTS (
      SELECT 1
      FROM users AS owner_user
      JOIN credentials AS owner_credential
        ON owner_credential.company_id = owner_user.company_id
       AND owner_credential.user_id = owner_user.id
      WHERE owner_user.company_id = company.id
        AND owner_user.id = company.owner_id
        AND owner_user.role = 'owner'
        AND owner_user.status = 'active'
        AND owner_user.external_deleted_at IS NULL
  )
  AND EXISTS (
      SELECT 1
      FROM users AS admin_user
      JOIN credentials AS admin_credential
        ON admin_credential.company_id = admin_user.company_id
       AND admin_credential.user_id = admin_user.id
      WHERE admin_user.company_id = company.id
        AND admin_user.role = 'admin'
        AND admin_user.status = 'active'
        AND admin_user.external_deleted_at IS NULL
  )
RETURNING id, name, logo_url, owner_id, created_at, updated_at, amo_account_id, status, onboarding_completed_at
`

type CompleteCompanyOnboardingParams struct {
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CompanyID   uuid.UUID          `json:"company_id"`
}

func (q *Queries) CompleteCompanyOnboarding(ctx context.Context, arg CompleteCompanyOnboardingParams) (Company, error) {
	row := q.db.QueryRow(ctx, completeCompanyOnboarding, arg.CompletedAt, arg.CompanyID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LogoUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AmoAccountID,
		&i.Status,
		&i.OnboardingCompletedAt,
	)
	return i, err
}

const consumeBootstrapActivation = `-- name: ConsumeBootstrapActivation :one
UPDATE bootstrap_activations
SET consumed_at = $1
WHERE id = $2
  AND consumed_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > $1
RETURNING id, company_id, user_id, role, purpose, token_hash, expires_at, consumed_at, revoked_at, revocation_reason, created_at
`

type ConsumeBootstrapActivationParams struct {
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) ConsumeBootstrapActivation(ctx context.Context, arg ConsumeBootstrapActivationParams) (BootstrapActivation, error) {
	row := q.db.QueryRow(ctx, consumeBootstrapActivation, arg.ConsumedAt, arg.ID)
	var i BootstrapActivation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Role,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
	)
	return i, err
}

const consumeSSOToken = `-- name: ConsumeSSOToken :one
UPDATE sso_tokens
SET consumed_at = $1
WHERE id = $2
  AND consumed_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > $1
RETURNING id, company_id, user_id, external_identity_id, purpose, token_hash, expires_at, consumed_at, revoked_at, created_at
`

type ConsumeSSOTokenParams struct {
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) ConsumeSSOToken(ctx context.Context, arg ConsumeSSOTokenParams) (SsoToken, error) {
	row := q.db.QueryRow(ctx, consumeSSOToken, arg.ConsumedAt, arg.ID)
	var i SsoToken
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.ExternalIdentityID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createBootstrapActivation = `-- name: CreateBootstrapActivation :one
INSERT INTO bootstrap_activations (
    id, company_id, user_id, role, purpose, token_hash, expires_at, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, company_id, user_id, role, purpose, token_hash, expires_at, consumed_at, revoked_at, revocation_reason, created_at
`

type CreateBootstrapActivationParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	Purpose   string    `json:"purpose"`
	TokenHash []byte    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateBootstrapActivation(ctx context.Context, arg CreateBootstrapActivationParams) (BootstrapActivation, error) {
	row := q.db.QueryRow(ctx, createBootstrapActivation,
		arg.ID,
		arg.CompanyID,
		arg.UserID,
		arg.Role,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i BootstrapActivation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Role,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
	)
	return i, err
}

const createCompanyIntegration = `-- name: CreateCompanyIntegration :one
INSERT INTO company_integrations (
    id, company_id, provider, external_account_id, app_name, entitlements,
    status, last_verified_at, metadata
)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, 'active', $7,
    $8
)
RETURNING id, company_id, provider, external_account_id, app_name, entitlements, status, last_verified_at, frozen_at, metadata, created_at, updated_at
`

type CreateCompanyIntegrationParams struct {
	ID                uuid.UUID          `json:"id"`
	CompanyID         uuid.UUID          `json:"company_id"`
	Provider          string             `json:"provider"`
	ExternalAccountID string             `json:"external_account_id"`
	AppName           pgtype.Text        `json:"app_name"`
	Entitlements      []string           `json:"entitlements"`
	LastVerifiedAt    pgtype.Timestamptz `json:"last_verified_at"`
	Metadata          []byte             `json:"metadata"`
}

func (q *Queries) CreateCompanyIntegration(ctx context.Context, arg CreateCompanyIntegrationParams) (CompanyIntegration, error) {
	row := q.db.QueryRow(ctx, createCompanyIntegration,
		arg.ID,
		arg.CompanyID,
		arg.Provider,
		arg.ExternalAccountID,
		arg.AppName,
		arg.Entitlements,
		arg.LastVerifiedAt,
		arg.Metadata,
	)
	var i CompanyIntegration
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Provider,
		&i.ExternalAccountID,
		&i.AppName,
		&i.Entitlements,
		&i.Status,
		&i.LastVerifiedAt,
		&i.FrozenAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProvisioningCompany = `-- name: CreateProvisioningCompany :one
INSERT INTO companies (
    id, name, logo_url, amo_account_id, status, onboarding_completed_at
)
VALUES ($1, $2, $3, $4, 'onboarding', NULL)
RETURNING id, name, logo_url, owner_id, created_at, updated_at, amo_account_id, status, onboarding_completed_at
`

type CreateProvisioningCompanyParams struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	LogoUrl      pgtype.Text `json:"logo_url"`
	AmoAccountID pgtype.Text `json:"amo_account_id"`
}

func (q *Queries) CreateProvisioningCompany(ctx context.Context, arg CreateProvisioningCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createProvisioningCompany,
		arg.ID,
		arg.Name,
		arg.LogoUrl,
		arg.AmoAccountID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LogoUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AmoAccountID,
		&i.Status,
		&i.OnboardingCompletedAt,
	)
	return i, err
}

const createProvisioningRequest = `-- name: CreateProvisioningRequest :one
INSERT INTO provisioning_requests (
    provider, idempotency_key, request_hash, external_account_id,
    company_id, integration_id, initiator_user_id, created_at, expires_at
)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9
)
RETURNING provider, idempotency_key, request_hash, external_account_id, company_id, integration_id, initiator_user_id, created_at, expires_at
`

type CreateProvisioningRequestParams struct {
	Provider          string    `json:"provider"`
	IdempotencyKey    string    `json:"idempotency_key"`
	RequestHash       []byte    `json:"request_hash"`
	ExternalAccountID string    `json:"external_account_id"`
	CompanyID         uuid.UUID `json:"company_id"`
	IntegrationID     uuid.UUID `json:"integration_id"`
	InitiatorUserID   uuid.UUID `json:"initiator_user_id"`
	CreatedAt         time.Time `json:"created_at"`
	ExpiresAt         time.Time `json:"expires_at"`
}

func (q *Queries) CreateProvisioningRequest(ctx context.Context, arg CreateProvisioningRequestParams) (ProvisioningRequest, error) {
	row := q.db.QueryRow(ctx, createProvisioningRequest,
		arg.Provider,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ExternalAccountID,
		arg.CompanyID,
		arg.IntegrationID,
		arg.InitiatorUserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i ProvisioningRequest
	err := row.Scan(
		&i.Provider,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ExternalAccountID,
		&i.CompanyID,
		&i.IntegrationID,
		&i.InitiatorUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createProvisioningUser = `-- name: CreateProvisioningUser :one
INSERT INTO users (
    id, company_id, email, first_name, last_name, role, status,
    source, external_id
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    'invited', $7, $8
)
RETURNING id, company_id, email, first_name, last_name, phone, avatar_url, role, status, birth_date, hired_at, vacation_allowance, created_at, updated_at, source, external_id, external_group_id, external_group_name, avatar_source, external_deleted_at
`

type CreateProvisioningUserParams struct {
	ID         uuid.UUID   `json:"id"`
	CompanyID  uuid.UUID   `json:"company_id"`
	Email      string      `json:"email"`
	FirstName  string      `json:"first_name"`
	LastName   pgtype.Text `json:"last_name"`
	Role       string      `json:"role"`
	Source     string      `json:"source"`
	ExternalID pgtype.Text `json:"external_id"`
}

func (q *Queries) CreateProvisioningUser(ctx context.Context, arg CreateProvisioningUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createProvisioningUser,
		arg.ID,
		arg.CompanyID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.Source,
		arg.ExternalID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.BirthDate,
		&i.HiredAt,
		&i.VacationAllowance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ExternalID,
		&i.ExternalGroupID,
		&i.ExternalGroupName,
		&i.AvatarSource,
		&i.ExternalDeletedAt,
	)
	return i, err
}

const createSSOToken = `-- name: CreateSSOToken :one
INSERT INTO sso_tokens (
    id, company_id, user_id, external_identity_id, token_hash, expires_at, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_id, user_id, external_identity_id, purpose, token_hash, expires_at, consumed_at, revoked_at, created_at
`

type CreateSSOTokenParams struct {
	ID                 uuid.UUID `json:"id"`
	CompanyID          uuid.UUID `json:"company_id"`
	UserID             uuid.UUID `json:"user_id"`
	ExternalIdentityID uuid.UUID `json:"external_identity_id"`
	TokenHash          []byte    `json:"token_hash"`
	ExpiresAt          time.Time `json:"expires_at"`
	CreatedAt          time.Time `json:"created_at"`
}

func (q *Queries) CreateSSOToken(ctx context.Context, arg CreateSSOTokenParams) (SsoToken, error) {
	row := q.db.QueryRow(ctx, createSSOToken,
		arg.ID,
		arg.CompanyID,
		arg.UserID,
		arg.ExternalIdentityID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i SsoToken
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.ExternalIdentityID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUserExternalIdentity = `-- name: CreateUserExternalIdentity :one
INSERT INTO user_external_identities (
    id, company_id, integration_id, user_id, provider, external_account_id,
    external_user_id, status, last_verified_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'active', $8)
RETURNING id, company_id, integration_id, user_id, provider, external_account_id, external_user_id, status, last_verified_at, created_at, updated_at
`

type CreateUserExternalIdentityParams struct {
	ID                uuid.UUID `json:"id"`
	CompanyID         uuid.UUID `json:"company_id"`
	IntegrationID     uuid.UUID `json:"integration_id"`
	UserID            uuid.UUID `json:"user_id"`
	Provider          string    `json:"provider"`
	ExternalAccountID string    `json:"external_account_id"`
	ExternalUserID    string    `json:"external_user_id"`
	LastVerifiedAt    time.Time `json:"last_verified_at"`
}

func (q *Queries) CreateUserExternalIdentity(ctx context.Context, arg CreateUserExternalIdentityParams) (UserExternalIdentity, error) {
	row := q.db.QueryRow(ctx, createUserExternalIdentity,
		arg.ID,
		arg.CompanyID,
		arg.IntegrationID,
		arg.UserID,
		arg.Provider,
		arg.ExternalAccountID,
		arg.ExternalUserID,
		arg.LastVerifiedAt,
	)
	var i UserExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.IntegrationID,
		&i.UserID,
		&i.Provider,
		&i.ExternalAccountID,
		&i.ExternalUserID,
		&i.Status,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredBootstrapActivations = `-- name: DeleteExpiredBootstrapActivations :execrows
DELETE FROM bootstrap_activations
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredBootstrapActivations(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredBootstrapActivations, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredProvisioningRequests = `-- name: DeleteExpiredProvisioningRequests :execrows
DELETE FROM provisioning_requests
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredProvisioningRequests(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredProvisioningRequests, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSSOTokens = `-- name: DeleteExpiredSSOTokens :execrows
DELETE FROM sso_tokens
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredSSOTokens(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSSOTokens, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBootstrapActivation = `-- name: GetBootstrapActivation :one
SELECT activation.id, activation.company_id, activation.user_id, activation.role, activation.purpose, activation.token_hash, activation.expires_at, activation.consumed_at, activation.revoked_at, activation.revocation_reason, activation.created_at, u.id, u.company_id, u.email, u.first_name, u.last_name, u.phone, u.avatar_url, u.role, u.status, u.birth_date, u.hired_at, u.vacation_allowance, u.created_at, u.updated_at, u.source, u.external_id, u.external_group_id, u.external_group_name, u.avatar_source, u.external_deleted_at, c.name AS company_name,
       c.status AS company_status, integration.status AS integration_status,
       identity.status AS external_identity_status
FROM bootstrap_activations AS activation
JOIN users AS u
  ON u.company_id = activation.company_id
 AND u.id = activation.user_id
JOIN companies AS c ON c.id = activation.company_id
JOIN user_external_identities AS identity
  ON identity.company_id = activation.company_id
 AND identity.user_id = activation.user_id
JOIN company_integrations AS integration
  ON integration.company_id = identity.company_id
 AND integration.id = identity.integration_id
WHERE activation.token_hash = $1
`

type GetBootstrapActivationRow struct {
	BootstrapActivation    BootstrapActivation `json:"bootstrap_activation"`
	User                   User                `json:"user"`
	CompanyName            string              `json:"company_name"`
	CompanyStatus          string              `json:"company_status"`
	IntegrationStatus      string              `json:"integration_status"`
	ExternalIdentityStatus string              `json:"external_identity_status"`
}

func (q *Queries) GetBootstrapActivation(ctx context.Context, tokenHash []byte) (GetBootstrapActivationRow, error) {
	row := q.db.QueryRow(ctx, getBootstrapActivation, tokenHash)
	var i GetBootstrapActivationRow
	err := row.Scan(
		&i.BootstrapActivation.ID,
		&i.BootstrapActivation.CompanyID,
		&i.BootstrapActivation.UserID,
		&i.BootstrapActivation.Role,
		&i.BootstrapActivation.Purpose,
		&i.BootstrapActivation.TokenHash,
		&i.BootstrapActivation.ExpiresAt,
		&i.BootstrapActivation.ConsumedAt,
		&i.BootstrapActivation.RevokedAt,
		&i.BootstrapActivation.RevocationReason,
		&i.BootstrapActivation.CreatedAt,
		&i.User.ID,
		&i.User.CompanyID,
		&i.User.Email,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.Phone,
		&i.User.AvatarUrl,
		&i.User.Role,
		&i.User.Status,
		&i.User.BirthDate,
		&i.User.HiredAt,
		&i.User.VacationAllowance,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.Source,
		&i.User.ExternalID,
		&i.User.ExternalGroupID,
		&i.User.ExternalGroupName,
		&i.User.AvatarSource,
		&i.User.ExternalDeletedAt,
		&i.CompanyName,
		&i.CompanyStatus,
		&i.IntegrationStatus,
		&i.ExternalIdentityStatus,
	)
	return i, err
}

const getBootstrapActivationForUpdate = `-- name: GetBootstrapActivationForUpdate :one
SELECT activation.id, activation.company_id, activation.user_id, activation.role, activation.purpose, activation.token_hash, activation.expires_at, activation.consumed_at, activation.revoked_at, activation.revocation_reason, activation.created_at, u.id, u.company_id, u.email, u.first_name, u.last_name, u.phone, u.avatar_url, u.role, u.status, u.birth_date, u.hired_at, u.vacation_allowance, u.created_at, u.updated_at, u.source, u.external_id, u.external_group_id, u.external_group_name, u.avatar_source, u.external_deleted_at, c.name AS company_name,
       c.status AS company_status, integration.status AS integration_status,
       identity.status AS external_identity_status
FROM bootstrap_activations AS activation
JOIN users AS u
  ON u.company_id = activation.company_id
 AND u.id = activation.user_id
JOIN companies AS c ON c.id = activation.company_id
JOIN user_external_identities AS identity
  ON identity.company_id = activation.company_id
 AND identity.user_id = activation.user_id
JOIN company_integrations AS integration
  ON integration.company_id = identity.company_id
 AND integration.id = identity.integration_id
WHERE activation.token_hash = $1
FOR UPDATE OF activation, u, c, identity, integration
`

type GetBootstrapActivationForUpdateRow struct {
	BootstrapActivation    BootstrapActivation `json:"bootstrap_activation"`
	User                   User                `json:"user"`
	CompanyName            string              `json:"company_name"`
	CompanyStatus          string              `json:"company_status"`
	IntegrationStatus      string              `json:"integration_status"`
	ExternalIdentityStatus string              `json:"external_identity_status"`
}

func (q *Queries) GetBootstrapActivationForUpdate(ctx context.Context, tokenHash []byte) (GetBootstrapActivationForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getBootstrapActivationForUpdate, tokenHash)
	var i GetBootstrapActivationForUpdateRow
	err := row.Scan(
		&i.BootstrapActivation.ID,
		&i.BootstrapActivation.CompanyID,
		&i.BootstrapActivation.UserID,
		&i.BootstrapActivation.Role,
		&i.BootstrapActivation.Purpose,
		&i.BootstrapActivation.TokenHash,
		&i.BootstrapActivation.ExpiresAt,
		&i.BootstrapActivation.ConsumedAt,
		&i.BootstrapActivation.RevokedAt,
		&i.BootstrapActivation.RevocationReason,
		&i.BootstrapActivation.CreatedAt,
		&i.User.ID,
		&i.User.CompanyID,
		&i.User.Email,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.Phone,
		&i.User.AvatarUrl,
		&i.User.Role,
		&i.User.Status,
		&i.User.BirthDate,
		&i.User.HiredAt,
		&i.User.VacationAllowance,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.Source,
		&i.User.ExternalID,
		&i.User.ExternalGroupID,
		&i.User.ExternalGroupName,
		&i.User.AvatarSource,
		&i.User.ExternalDeletedAt,
		&i.CompanyName,
		&i.CompanyStatus,
		&i.IntegrationStatus,
		&i.ExternalIdentityStatus,
	)
	return i, err
}

const getCompanyForOnboardingUpdate = `-- name: GetCompanyForOnboardingUpdate :one
SELECT id, name, logo_url, owner_id, created_at, updated_at, amo_account_id, status, onboarding_completed_at
FROM companies
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetCompanyForOnboardingUpdate(ctx context.Context, companyID uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyForOnboardingUpdate, companyID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LogoUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AmoAccountID,
		&i.Status,
		&i.OnboardingCompletedAt,
	)
	return i, err
}

const getCompanyIntegrationByExternalAccount = `-- name: GetCompanyIntegrationByExternalAccount :one
SELECT id, company_id, provider, external_account_id, app_name, entitlements, status, last_verified_at, frozen_at, metadata, created_at, updated_at
FROM company_integrations
WHERE provider = $1
  AND external_account_id = $2
`

type GetCompanyIntegrationByExternalAccountParams struct {
	Provider          string `json:"provider"`
	ExternalAccountID string `json:"external_account_id"`
}

func (q *Queries) GetCompanyIntegrationByExternalAccount(ctx context.Context, arg GetCompanyIntegrationByExternalAccountParams) (CompanyIntegration, error) {
	row := q.db.QueryRow(ctx, getCompanyIntegrationByExternalAccount, arg.Provider, arg.ExternalAccountID)
	var i CompanyIntegration
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Provider,
		&i.ExternalAccountID,
		&i.AppName,
		&i.Entitlements,
		&i.Status,
		&i.LastVerifiedAt,
		&i.FrozenAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyIntegrationByExternalAccountForUpdate = `-- name: GetCompanyIntegrationByExternalAccountForUpdate :one
SELECT id, company_id, provider, external_account_id, app_name, entitlements, status, last_verified_at, frozen_at, metadata, created_at, updated_at
FROM company_integrations
WHERE provider = $1
  AND external_account_id = $2
FOR UPDATE
`

type GetCompanyIntegrationByExternalAccountForUpdateParams struct {
	Provider          string `json:"provider"`
	ExternalAccountID string `json:"external_account_id"`
}

func (q *Queries) GetCompanyIntegrationByExternalAccountForUpdate(ctx context.Context, arg GetCompanyIntegrationByExternalAccountForUpdateParams) (CompanyIntegration, error) {
	row := q.db.QueryRow(ctx, getCompanyIntegrationByExternalAccountForUpdate, arg.Provider, arg.ExternalAccountID)
	var i CompanyIntegration
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Provider,
		&i.ExternalAccountID,
		&i.AppName,
		&i.Entitlements,
		&i.Status,
		&i.LastVerifiedAt,
		&i.FrozenAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExternalIdentityForSSO = `-- name: GetExternalIdentityForSSO :one
SELECT identity.id, identity.company_id, identity.integration_id, identity.user_id, identity.provider, identity.external_account_id, identity.external_user_id, identity.status, identity.last_verified_at, identity.created_at, identity.updated_at, integration.id, integration.company_id, integration.provider, integration.external_account_id, integration.app_name, integration.entitlements, integration.status, integration.last_verified_at, integration.frozen_at, integration.metadata, integration.created_at, integration.updated_at, u.id, u.company_id, u.email, u.first_name, u.last_name, u.phone, u.avatar_url, u.role, u.status, u.birth_date, u.hired_at, u.vacation_allowance, u.created_at, u.updated_at, u.source, u.external_id, u.external_group_id, u.external_group_name, u.avatar_source, u.external_deleted_at,
       company.status AS company_status
FROM user_external_identities AS identity
JOIN company_integrations AS integration
  ON integration.company_id = identity.company_id
 AND integration.id = identity.integration_id
JOIN users AS u
  ON u.company_id = identity.company_id
 AND u.id = identity.user_id
JOIN companies AS company ON company.id = identity.company_id
WHERE integration.provider = $1
  AND integration.external_account_id = $2
  AND identity.external_user_id = $3
FOR UPDATE OF identity, integration, u, company
`

type GetExternalIdentityForSSOParams struct {
	Provider          string `json:"provider"`
	ExternalAccountID string `json:"external_account_id"`
	ExternalUserID    string `json:"external_user_id"`
}

type GetExternalIdentityForSSORow struct {
	UserExternalIdentity UserExternalIdentity `json:"user_external_identity"`
	CompanyIntegration   CompanyIntegration   `json:"company_integration"`
	User                 User                 `json:"user"`
	CompanyStatus        string               `json:"company_status"`
}

func (q *Queries) GetExternalIdentityForSSO(ctx context.Context, arg GetExternalIdentityForSSOParams) (GetExternalIdentityForSSORow, error) {
	row := q.db.QueryRow(ctx, getExternalIdentityForSSO, arg.Provider, arg.ExternalAccountID, arg.ExternalUserID)
	var i GetExternalIdentityForSSORow
	err := row.Scan(
		&i.UserExternalIdentity.ID,
		&i.UserExternalIdentity.CompanyID,
		&i.UserExternalIdentity.IntegrationID,
		&i.UserExternalIdentity.UserID,
		&i.UserExternalIdentity.Provider,
		&i.UserExternalIdentity.ExternalAccountID,
		&i.UserExternalIdentity.ExternalUserID,
		&i.UserExternalIdentity.Status,
		&i.UserExternalIdentity.LastVerifiedAt,
		&i.UserExternalIdentity.CreatedAt,
		&i.UserExternalIdentity.UpdatedAt,
		&i.CompanyIntegration.ID,
		&i.CompanyIntegration.CompanyID,
		&i.CompanyIntegration.Provider,
		&i.CompanyIntegration.ExternalAccountID,
		&i.CompanyIntegration.AppName,
		&i.CompanyIntegration.Entitlements,
		&i.CompanyIntegration.Status,
		&i.CompanyIntegration.LastVerifiedAt,
		&i.CompanyIntegration.FrozenAt,
		&i.CompanyIntegration.Metadata,
		&i.CompanyIntegration.CreatedAt,
		&i.CompanyIntegration.UpdatedAt,
		&i.User.ID,
		&i.User.CompanyID,
		&i.User.Email,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.Phone,
		&i.User.AvatarUrl,
		&i.User.Role,
		&i.User.Status,
		&i.User.BirthDate,
		&i.User.HiredAt,
		&i.User.VacationAllowance,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.Source,
		&i.User.ExternalID,
		&i.User.ExternalGroupID,
		&i.User.ExternalGroupName,
		&i.User.AvatarSource,
		&i.User.ExternalDeletedAt,
		&i.CompanyStatus,
	)
	return i, err
}

const getOnboardingIntegration = `-- name: GetOnboardingIntegration :one
SELECT id, company_id, provider, external_account_id, app_name, entitlements, status, last_verified_at, frozen_at, metadata, created_at, updated_at
FROM company_integrations
WHERE company_id = $1
ORDER BY created_at, id
LIMIT 1
`

func (q *Queries) GetOnboardingIntegration(ctx context.Context, companyID uuid.UUID) (CompanyIntegration, error) {
	row := q.db.QueryRow(ctx, getOnboardingIntegration, companyID)
	var i CompanyIntegration
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Provider,
		&i.ExternalAccountID,
		&i.AppName,
		&i.Entitlements,
		&i.Status,
		&i.LastVerifiedAt,
		&i.FrozenAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOnboardingIntegrationForUpdate = `-- name: GetOnboardingIntegrationForUpdate :one
SELECT id, company_id, provider, external_account_id, app_name, entitlements, status, last_verified_at, frozen_at, metadata, created_at, updated_at
FROM company_integrations
WHERE company_id = $1
ORDER BY created_at, id
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetOnboardingIntegrationForUpdate(ctx context.Context, companyID uuid.UUID) (CompanyIntegration, error) {
	row := q.db.QueryRow(ctx, getOnboardingIntegrationForUpdate, companyID)
	var i CompanyIntegration
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Provider,
		&i.ExternalAccountID,
		&i.AppName,
		&i.Entitlements,
		&i.Status,
		&i.LastVerifiedAt,
		&i.FrozenAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenBootstrapActivationForUser = `-- name: GetOpenBootstrapActivationForUser :one
SELECT id, company_id, user_id, role, purpose, token_hash, expires_at, consumed_at, revoked_at, revocation_reason, created_at
FROM bootstrap_activations
WHERE company_id = $1
  AND user_id = $2
  AND consumed_at IS NULL
  AND revoked_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT 1
FOR UPDATE
`

type GetOpenBootstrapActivationForUserParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetOpenBootstrapActivationForUser(ctx context.Context, arg GetOpenBootstrapActivationForUserParams) (BootstrapActivation, error) {
	row := q.db.QueryRow(ctx, getOpenBootstrapActivationForUser, arg.CompanyID, arg.UserID)
	var i BootstrapActivation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Role,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingOnboardingUser = `-- name: GetPendingOnboardingUser :one
SELECT id, company_id, email, first_name, last_name, phone, avatar_url, role, status, birth_date, hired_at, vacation_allowance, created_at, updated_at, source, external_id, external_group_id, external_group_name, avatar_source, external_deleted_at
FROM users
WHERE company_id = $1
  AND id <> $2
  AND source = 'external'
  AND role IN ('owner', 'admin')
  AND status = 'invited'
  AND external_deleted_at IS NULL
ORDER BY CASE role WHEN 'owner' THEN 0 ELSE 1 END, created_at, id
LIMIT 1
FOR UPDATE
`

type GetPendingOnboardingUserParams struct {
	CompanyID       uuid.UUID `json:"company_id"`
	ActivatedUserID uuid.UUID `json:"activated_user_id"`
}

func (q *Queries) GetPendingOnboardingUser(ctx context.Context, arg GetPendingOnboardingUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getPendingOnboardingUser, arg.CompanyID, arg.ActivatedUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.BirthDate,
		&i.HiredAt,
		&i.VacationAllowance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ExternalID,
		&i.ExternalGroupID,
		&i.ExternalGroupName,
		&i.AvatarSource,
		&i.ExternalDeletedAt,
	)
	return i, err
}

const getPendingOnboardingUserForActor = `-- name: GetPendingOnboardingUserForActor :one
SELECT pending.id, pending.company_id, pending.email, pending.first_name, pending.last_name, pending.phone, pending.avatar_url, pending.role, pending.status, pending.birth_date, pending.hired_at, pending.vacation_allowance, pending.created_at, pending.updated_at, pending.source, pending.external_id, pending.external_group_id, pending.external_group_name, pending.avatar_source, pending.external_deleted_at
FROM users AS pending
WHERE pending.company_id = $1
  AND pending.id <> $2
  AND pending.source = 'external'
  AND pending.role IN ('owner', 'admin')
  AND pending.status = 'invited'
  AND pending.external_deleted_at IS NULL
  AND EXISTS (
      SELECT 1 FROM bootstrap_activations AS activation
      WHERE activation.company_id = pending.company_id
        AND activation.user_id = pending.id
  )
ORDER BY CASE pending.role WHEN 'owner' THEN 0 ELSE 1 END, pending.created_at, pending.id
LIMIT 1
FOR UPDATE
`

type GetPendingOnboardingUserForActorParams struct {
	CompanyID   uuid.UUID `json:"company_id"`
	ActorUserID uuid.UUID `json:"actor_user_id"`
}

func (q *Queries) GetPendingOnboardingUserForActor(ctx context.Context, arg GetPendingOnboardingUserForActorParams) (User, error) {
	row := q.db.QueryRow(ctx, getPendingOnboardingUserForActor, arg.CompanyID, arg.ActorUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.BirthDate,
		&i.HiredAt,
		&i.VacationAllowance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.ExternalID,
		&i.ExternalGroupID,
		&i.ExternalGroupName,
		&i.AvatarSource,
		&i.ExternalDeletedAt,
	)
	return i, err
}

const getProvisionedCompanyStatus = `-- name: GetProvisionedCompanyStatus :one
SELECT company.id AS company_id, company.status AS company_status
FROM company_integrations AS integration
JOIN companies AS company ON company.id = integration.company_id
WHERE integration.provider = $1
  AND integration.external_account_id = $2
`

type GetProvisionedCompanyStatusParams struct {
	Provider          string `json:"provider"`
	ExternalAccountID string `json:"external_account_id"`
}

type GetProvisionedCompanyStatusRow struct {
	CompanyID     uuid.UUID `json:"company_id"`
	CompanyStatus string    `json:"company_status"`
}

func (q *Queries) GetProvisionedCompanyStatus(ctx context.Context, arg GetProvisionedCompanyStatusParams) (GetProvisionedCompanyStatusRow, error) {
	row := q.db.QueryRow(ctx, getProvisionedCompanyStatus, arg.Provider, arg.ExternalAccountID)
	var i GetProvisionedCompanyStatusRow
	err := row.Scan(&i.CompanyID, &i.CompanyStatus)
	return i, err
}

const getProvisioningRequestForUpdate = `-- name: GetProvisioningRequestForUpdate :one
SELECT provider, idempotency_key, request_hash, external_account_id, company_id, integration_id, initiator_user_id, created_at, expires_at
FROM provisioning_requests
WHERE provider = $1
  AND idempotency_key = $2
FOR UPDATE
`

type GetProvisioningRequestForUpdateParams struct {
	Provider       string `json:"provider"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetProvisioningRequestForUpdate(ctx context.Context, arg GetProvisioningRequestForUpdateParams) (ProvisioningRequest, error) {
	row := q.db.QueryRow(ctx, getProvisioningRequestForUpdate, arg.Provider, arg.IdempotencyKey)
	var i ProvisioningRequest
	err := row.Scan(
		&i.Provider,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ExternalAccountID,
		&i.CompanyID,
		&i.IntegrationID,
		&i.InitiatorUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getProvisioningUsers = `-- name: GetProvisioningUsers :many
SELECT u.id, u.company_id, u.email, u.first_name, u.last_name, u.phone, u.avatar_url, u.role, u.status, u.birth_date, u.hired_at, u.vacation_allowance, u.created_at, u.updated_at, u.source, u.external_id, u.external_group_id, u.external_group_name, u.avatar_source, u.external_deleted_at, identity.id AS external_identity_id, identity.external_user_id
FROM users AS u
JOIN user_external_identities AS identity
  ON identity.company_id = u.company_id
 AND identity.user_id = u.id
JOIN company_integrations AS integration
  ON integration.company_id = identity.company_id
 AND integration.id = identity.integration_id
WHERE integration.provider = $1
  AND integration.external_account_id = $2
  AND u.role IN ('owner', 'admin')
ORDER BY CASE u.role WHEN 'owner' THEN 0 ELSE 1 END, u.id
`

type GetProvisioningUsersParams struct {
	Provider          string `json:"provider"`
	ExternalAccountID string `json:"external_account_id"`
}

type GetProvisioningUsersRow struct {
	ID                 uuid.UUID          `json:"id"`
	CompanyID          uuid.UUID          `json:"company_id"`
	Email              string             `json:"email"`
	FirstName          string             `json:"first_name"`
	LastName           pgtype.Text        `json:"last_name"`
	Phone              pgtype.Text        `json:"phone"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	Role               string             `json:"role"`
	Status             string             `json:"status"`
	BirthDate          pgtype.Date        `json:"birth_date"`
	HiredAt            pgtype.Date        `json:"hired_at"`
	VacationAllowance  pgtype.Int2        `json:"vacation_allowance"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	Source             string             `json:"source"`
	ExternalID         pgtype.Text        `json:"external_id"`
	ExternalGroupID    pgtype.Text        `json:"external_group_id"`
	ExternalGroupName  pgtype.Text        `json:"external_group_name"`
	AvatarSource       pgtype.Text        `json:"avatar_source"`
	ExternalDeletedAt  pgtype.Timestamptz `json:"external_deleted_at"`
	ExternalIdentityID uuid.UUID          `json:"external_identity_id"`
	ExternalUserID     string             `json:"external_user_id"`
}

func (q *Queries) GetProvisioningUsers(ctx context.Context, arg GetProvisioningUsersParams) ([]GetProvisioningUsersRow, error) {
	rows, err := q.db.Query(ctx, getProvisioningUsers, arg.Provider, arg.ExternalAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProvisioningUsersRow{}
	for rows.Next() {
		var i GetProvisioningUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.AvatarUrl,
			&i.Role,
			&i.Status,
			&i.BirthDate,
			&i.HiredAt,
			&i.VacationAllowance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.ExternalID,
			&i.ExternalGroupID,
			&i.ExternalGroupName,
			&i.AvatarSource,
			&i.ExternalDeletedAt,
			&i.ExternalIdentityID,
			&i.ExternalUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSSOTokenByHashForUpdate = `-- name: GetSSOTokenByHashForUpdate :one
SELECT token.id AS sso_token_id,
       token.company_id,
       token.user_id,
       token.external_identity_id,
       token.expires_at,
       token.consumed_at,
       token.revoked_at,
       u.id, u.company_id, u.email, u.first_name, u.last_name, u.phone, u.avatar_url, u.role, u.status, u.birth_date, u.hired_at, u.vacation_allowance, u.created_at, u.updated_at, u.source, u.external_id, u.external_group_id, u.external_group_name, u.avatar_source, u.external_deleted_at,
       identity.status AS external_identity_status,
       integration.provider,
       integration.external_account_id,
       identity.external_user_id,
       integration.status AS integration_status,
       company.status AS company_status
FROM sso_tokens AS token
JOIN user_external_identities AS identity
  ON identity.company_id = token.company_id
 AND identity.user_id = token.user_id
 AND identity.id = token.external_identity_id
JOIN company_integrations AS integration
  ON integration.company_id = identity.company_id
 AND integration.id = identity.integration_id
JOIN users AS u
  ON u.company_id = token.company_id
 AND u.id = token.user_id
JOIN companies AS company ON company.id = token.company_id
WHERE token.token_hash = $1
FOR UPDATE OF token, identity, integration, u, company
`

type GetSSOTokenByHashForUpdateRow struct {
	SsoTokenID             uuid.UUID          `json:"sso_token_id"`
	CompanyID              uuid.UUID          `json:"company_id"`
	UserID                 uuid.UUID          `json:"user_id"`
	ExternalIdentityID     uuid.UUID          `json:"external_identity_id"`
	ExpiresAt              time.Time          `json:"expires_at"`
	ConsumedAt             pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt              pgtype.Timestamptz `json:"revoked_at"`
	User                   User               `json:"user"`
	ExternalIdentityStatus string             `json:"external_identity_status"`
	Provider               string             `json:"provider"`
	ExternalAccountID      string             `json:"external_account_id"`
	ExternalUserID         string             `json:"external_user_id"`
	IntegrationStatus      string             `json:"integration_status"`
	CompanyStatus          string             `json:"company_status"`
}

func (q *Queries) GetSSOTokenByHashForUpdate(ctx context.Context, tokenHash []byte) (GetSSOTokenByHashForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getSSOTokenByHashForUpdate, tokenHash)
	var i GetSSOTokenByHashForUpdateRow
	err := row.Scan(
		&i.SsoTokenID,
		&i.CompanyID,
		&i.UserID,
		&i.ExternalIdentityID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.User.ID,
		&i.User.CompanyID,
		&i.User.Email,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.Phone,
		&i.User.AvatarUrl,
		&i.User.Role,
		&i.User.Status,
		&i.User.BirthDate,
		&i.User.HiredAt,
		&i.User.VacationAllowance,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.Source,
		&i.User.ExternalID,
		&i.User.ExternalGroupID,
		&i.User.ExternalGroupName,
		&i.User.AvatarSource,
		&i.User.ExternalDeletedAt,
		&i.ExternalIdentityStatus,
		&i.Provider,
		&i.ExternalAccountID,
		&i.ExternalUserID,
		&i.IntegrationStatus,
		&i.CompanyStatus,
	)
	return i, err
}

const isPendingBootstrapUser = `-- name: IsPendingBootstrapUser :one
SELECT EXISTS (
    SELECT 1
    FROM bootstrap_activations AS activation
    WHERE activation.company_id = $1
      AND activation.user_id = $2
      AND activation.consumed_at IS NULL
      AND activation.revoked_at IS NULL
)
`

type IsPendingBootstrapUserParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) IsPendingBootstrapUser(ctx context.Context, arg IsPendingBootstrapUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPendingBootstrapUser, arg.CompanyID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listOnboardingParticipants = `-- name: ListOnboardingParticipants :many
SELECT u.id, u.company_id, u.email, u.first_name, u.last_name, u.phone, u.avatar_url, u.role, u.status, u.birth_date, u.hired_at, u.vacation_allowance, u.created_at, u.updated_at, u.source, u.external_id, u.external_group_id, u.external_group_name, u.avatar_source, u.external_deleted_at,
       current_activation.expires_at IS NOT NULL AS has_open_activation,
       COALESCE(current_activation.expires_at, 'epoch'::timestamptz) AS activation_expires_at
FROM users AS u
JOIN user_external_identities AS identity
  ON identity.company_id = u.company_id AND identity.user_id = u.id
LEFT JOIN LATERAL (
    SELECT activation.expires_at
    FROM bootstrap_activations AS activation
    WHERE activation.company_id = u.company_id
      AND activation.user_id = u.id
      AND activation.consumed_at IS NULL
      AND activation.revoked_at IS NULL
    ORDER BY activation.created_at DESC, activation.id DESC
    LIMIT 1
) AS current_activation ON true
WHERE u.company_id = $1
  AND u.source = 'external'
  AND u.role IN ('owner', 'admin')
ORDER BY CASE u.role WHEN 'owner' THEN 0 ELSE 1 END, u.id
`

type ListOnboardingParticipantsRow struct {
	ID                  uuid.UUID          `json:"id"`
	CompanyID           uuid.UUID          `json:"company_id"`
	Email               string             `json:"email"`
	FirstName           string             `json:"first_name"`
	LastName            pgtype.Text        `json:"last_name"`
	Phone               pgtype.Text        `json:"phone"`
	AvatarUrl           pgtype.Text        `json:"avatar_url"`
	Role                string             `json:"role"`
	Status              string             `json:"status"`
	BirthDate           pgtype.Date        `json:"birth_date"`
	HiredAt             pgtype.Date        `json:"hired_at"`
	VacationAllowance   pgtype.Int2        `json:"vacation_allowance"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	Source              string             `json:"source"`
	ExternalID          pgtype.Text        `json:"external_id"`
	ExternalGroupID     pgtype.Text        `json:"external_group_id"`
	ExternalGroupName   pgtype.Text        `json:"external_group_name"`
	AvatarSource        pgtype.Text        `json:"avatar_source"`
	ExternalDeletedAt   pgtype.Timestamptz `json:"external_deleted_at"`
	HasOpenActivation   interface{}        `json:"has_open_activation"`
	ActivationExpiresAt time.Time          `json:"activation_expires_at"`
}

func (q *Queries) ListOnboardingParticipants(ctx context.Context, companyID uuid.UUID) ([]ListOnboardingParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listOnboardingParticipants, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOnboardingParticipantsRow{}
	for rows.Next() {
		var i ListOnboardingParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.AvatarUrl,
			&i.Role,
			&i.Status,
			&i.BirthDate,
			&i.HiredAt,
			&i.VacationAllowance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.ExternalID,
			&i.ExternalGroupID,
			&i.ExternalGroupName,
			&i.AvatarSource,
			&i.ExternalDeletedAt,
			&i.HasOpenActivation,
			&i.ActivationExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProvisioningAccount = `-- name: LockProvisioningAccount :exec
SELECT pg_advisory_xact_lock(
    hashtextextended(
        $1::text || ':' || $2::text,
        0
    )
)
`

type LockProvisioningAccountParams struct {
	Provider          string `json:"provider"`
	ExternalAccountID string `json:"external_account_id"`
}

func (q *Queries) LockProvisioningAccount(ctx context.Context, arg LockProvisioningAccountParams) error {
	_, err := q.db.Exec(ctx, lockProvisioningAccount, arg.Provider, arg.ExternalAccountID)
	return err
}

const lockProvisioningKey = `-- name: LockProvisioningKey :exec
SELECT pg_advisory_xact_lock(
    hashtextextended(
        $1::text || ':idempotency:' || $2::text,
        0
    )
)
`

type LockProvisioningKeyParams struct {
	Provider       string `json:"provider"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) LockProvisioningKey(ctx context.Context, arg LockProvisioningKeyParams) error {
	_, err := q.db.Exec(ctx, lockProvisioningKey, arg.Provider, arg.IdempotencyKey)
	return err
}

const markExternalIdentityVerified = `-- name: MarkExternalIdentityVerified :one
UPDATE user_external_identities
SET last_verified_at = $1,
    updated_at = $1
WHERE company_id = $2
  AND id = $3
RETURNING id, company_id, integration_id, user_id, provider, external_account_id, external_user_id, status, last_verified_at, created_at, updated_at
`

type MarkExternalIdentityVerifiedParams struct {
	VerifiedAt time.Time `json:"verified_at"`
	CompanyID  uuid.UUID `json:"company_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) MarkExternalIdentityVerified(ctx context.Context, arg MarkExternalIdentityVerifiedParams) (UserExternalIdentity, error) {
	row := q.db.QueryRow(ctx, markExternalIdentityVerified, arg.VerifiedAt, arg.CompanyID, arg.ID)
	var i UserExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.IntegrationID,
		&i.UserID,
		&i.Provider,
		&i.ExternalAccountID,
		&i.ExternalUserID,
		&i.Status,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeActiveSSOTokens = `-- name: RevokeActiveSSOTokens :execrows
UPDATE sso_tokens
SET revoked_at = $1
WHERE external_identity_id = $2
  AND consumed_at IS NULL
  AND revoked_at IS NULL
`

type RevokeActiveSSOTokensParams struct {
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
	ExternalIdentityID uuid.UUID          `json:"external_identity_id"`
}

func (q *Queries) RevokeActiveSSOTokens(ctx context.Context, arg RevokeActiveSSOTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeActiveSSOTokens, arg.RevokedAt, arg.ExternalIdentityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeBootstrapActivations = `-- name: RevokeBootstrapActivations :execrows
UPDATE bootstrap_activations
SET revoked_at = $1,
    revocation_reason = $2
WHERE company_id = $3
  AND user_id = $4
  AND consumed_at IS NULL
  AND revoked_at IS NULL
`

type RevokeBootstrapActivationsParams struct {
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	RevocationReason pgtype.Text        `json:"revocation_reason"`
	CompanyID        uuid.UUID          `json:"company_id"`
	UserID           uuid.UUID          `json:"user_id"`
}

func (q *Queries) RevokeBootstrapActivations(ctx context.Context, arg RevokeBootstrapActivationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeBootstrapActivations,
		arg.RevokedAt,
		arg.RevocationReason,
		arg.CompanyID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCompanyIntegrationStatus = `-- name: UpdateCompanyIntegrationStatus :one
UPDATE company_integrations
SET status = $1,
    frozen_at = CASE
        WHEN $1::text = 'frozen' THEN COALESCE(frozen_at, $2)
        ELSE NULL
    END,
    last_verified_at = CASE
        WHEN $3::boolean THEN $2
        ELSE last_verified_at
    END,
    updated_at = $2
WHERE id = $4 AND company_id = $5
RETURNING id, company_id, provider, external_account_id, app_name, entitlements, status, last_verified_at, frozen_at, metadata, created_at, updated_at
`

type UpdateCompanyIntegrationStatusParams struct {
	Status       string    `json:"status"`
	ChangedAt    time.Time `json:"changed_at"`
	MarkVerified bool      `json:"mark_verified"`
	ID           uuid.UUID `json:"id"`
	CompanyID    uuid.UUID `json:"company_id"`
}

func (q *Queries) UpdateCompanyIntegrationStatus(ctx context.Context, arg UpdateCompanyIntegrationStatusParams) (CompanyIntegration, error) {
	row := q.db.QueryRow(ctx, updateCompanyIntegrationStatus,
		arg.Status,
		arg.ChangedAt,
		arg.MarkVerified,
		arg.ID,
		arg.CompanyID,
	)
	var i CompanyIntegration
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Provider,
		&i.ExternalAccountID,
		&i.AppName,
		&i.Entitlements,
		&i.Status,
		&i.LastVerifiedAt,
		&i.FrozenAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
