// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptInvite(ctx context.Context, id uuid.UUID) (Invite, error)
	ActivateBootstrapUser(ctx context.Context, arg ActivateBootstrapUserParams) (User, error)
	ActivateInvitedUser(ctx context.Context, arg ActivateInvitedUserParams) (User, error)
	AssignUserPosition(ctx context.Context, arg AssignUserPositionParams) error
	ClearAmoUserTombstone(ctx context.Context, arg ClearAmoUserTombstoneParams) (User, error)
	CompleteCompanyOnboarding(ctx context.Context, arg CompleteCompanyOnboardingParams) (Company, error)
	ConsumeBootstrapActivation(ctx context.Context, arg ConsumeBootstrapActivationParams) (BootstrapActivation, error)
	ConsumeSSOToken(ctx context.Context, arg ConsumeSSOTokenParams) (SsoToken, error)
	CountDepartmentChildren(ctx context.Context, arg CountDepartmentChildrenParams) (int64, error)
	CountDepartmentPositions(ctx context.Context, arg CountDepartmentPositionsParams) (int64, error)
	CreateAmoUser(ctx context.Context, arg CreateAmoUserParams) (User, error)
	CreateBootstrapActivation(ctx context.Context, arg CreateBootstrapActivationParams) (BootstrapActivation, error)
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	CreateCompanyIntegration(ctx context.Context, arg CreateCompanyIntegrationParams) (CompanyIntegration, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateDistributionEvent(ctx context.Context, arg CreateDistributionEventParams) (DistributionEvent, error)
	CreateDistributionGroup(ctx context.Context, arg CreateDistributionGroupParams) (DistributionGroup, error)
	CreateEmployeeAccessAudit(ctx context.Context, arg CreateEmployeeAccessAuditParams) error
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (Outbox, error)
	CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error)
	CreateProvisioningCompany(ctx context.Context, arg CreateProvisioningCompanyParams) (Company, error)
	CreateProvisioningRequest(ctx context.Context, arg CreateProvisioningRequestParams) (ProvisioningRequest, error)
	CreateProvisioningUser(ctx context.Context, arg CreateProvisioningUserParams) (User, error)
	CreateSSOToken(ctx context.Context, arg CreateSSOTokenParams) (SsoToken, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserAdminAudit(ctx context.Context, arg CreateUserAdminAuditParams) error
	CreateUserExternalIdentity(ctx context.Context, arg CreateUserExternalIdentityParams) (UserExternalIdentity, error)
	DeleteAccessLink(ctx context.Context, arg DeleteAccessLinkParams) error
	DeleteCredential(ctx context.Context, arg DeleteCredentialParams) error
	DeleteDepartment(ctx context.Context, arg DeleteDepartmentParams) (int64, error)
	DeleteDistributionGroup(ctx context.Context, arg DeleteDistributionGroupParams) (int64, error)
	DeleteEmployeeSectionAccess(ctx context.Context, arg DeleteEmployeeSectionAccessParams) error
	DeleteExpiredBootstrapActivations(ctx context.Context, before time.Time) (int64, error)
	DeleteExpiredProvisioningRequests(ctx context.Context, before time.Time) (int64, error)
	DeleteExpiredSSOTokens(ctx context.Context, before time.Time) (int64, error)
	DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) (int64, error)
	DeleteLocalUser(ctx context.Context, arg DeleteLocalUserParams) (int64, error)
	DeletePosition(ctx context.Context, arg DeletePositionParams) (int64, error)
	DeleteUserPositions(ctx context.Context, arg DeleteUserPositionsParams) error
	DisableUserInDistributionGroups(ctx context.Context, arg DisableUserInDistributionGroupsParams) error
	FindUserForAmoSync(ctx context.Context, arg FindUserForAmoSyncParams) (User, error)
	GetAccessLink(ctx context.Context, arg GetAccessLinkParams) (AccessLink, error)
	GetBootstrapActivation(ctx context.Context, tokenHash []byte) (GetBootstrapActivationRow, error)
	GetBootstrapActivationForUpdate(ctx context.Context, tokenHash []byte) (GetBootstrapActivationForUpdateRow, error)
	GetCompany(ctx context.Context, id uuid.UUID) (Company, error)
	GetCompanyForOnboardingUpdate(ctx context.Context, companyID uuid.UUID) (Company, error)
	GetCompanyIntegrationByExternalAccount(ctx context.Context, arg GetCompanyIntegrationByExternalAccountParams) (CompanyIntegration, error)
	GetCompanyIntegrationByExternalAccountForUpdate(ctx context.Context, arg GetCompanyIntegrationByExternalAccountForUpdateParams) (CompanyIntegration, error)
	GetDepartment(ctx context.Context, arg GetDepartmentParams) (Department, error)
	GetDistributionGroup(ctx context.Context, arg GetDistributionGroupParams) (DistributionGroup, error)
	GetDistributionGroupForUpdate(ctx context.Context, arg GetDistributionGroupForUpdateParams) (DistributionGroup, error)
	GetExternalIdentityForSSO(ctx context.Context, arg GetExternalIdentityForSSOParams) (GetExternalIdentityForSSORow, error)
	GetInvite(ctx context.Context, arg GetInviteParams) (Invite, error)
	GetInviteByToken(ctx context.Context, token string) (Invite, error)
	GetInviteByTokenForUpdate(ctx context.Context, token string) (Invite, error)
	GetOnboardingIntegration(ctx context.Context, companyID uuid.UUID) (CompanyIntegration, error)
	GetOnboardingIntegrationForUpdate(ctx context.Context, companyID uuid.UUID) (CompanyIntegration, error)
	GetOpenBootstrapActivationForUser(ctx context.Context, arg GetOpenBootstrapActivationForUserParams) (BootstrapActivation, error)
	GetPendingOnboardingUser(ctx context.Context, arg GetPendingOnboardingUserParams) (User, error)
	GetPendingOnboardingUserForActor(ctx context.Context, arg GetPendingOnboardingUserForActorParams) (User, error)
	GetPosition(ctx context.Context, arg GetPositionParams) (Position, error)
	GetPositionUserIDs(ctx context.Context, arg GetPositionUserIDsParams) ([]uuid.UUID, error)
	GetProvisionedCompanyStatus(ctx context.Context, arg GetProvisionedCompanyStatusParams) (GetProvisionedCompanyStatusRow, error)
	GetProvisioningRequestForUpdate(ctx context.Context, arg GetProvisioningRequestForUpdateParams) (ProvisioningRequest, error)
	GetProvisioningUsers(ctx context.Context, arg GetProvisioningUsersParams) ([]GetProvisioningUsersRow, error)
	GetReportUserProfiles(ctx context.Context, arg GetReportUserProfilesParams) ([]GetReportUserProfilesRow, error)
	GetSSOTokenByHashForUpdate(ctx context.Context, tokenHash []byte) (GetSSOTokenByHashForUpdateRow, error)
	GetSessionByHashForUpdate(ctx context.Context, refreshHash []byte) (Session, error)
	GetUser(ctx context.Context, arg GetUserParams) (User, error)
	GetUserAccessMode(ctx context.Context, arg GetUserAccessModeParams) (string, error)
	GetUserByAccessToken(ctx context.Context, token string) (User, error)
	GetUserByEmailForUpdate(ctx context.Context, email string) (User, error)
	GetUserDepartmentClaims(ctx context.Context, arg GetUserDepartmentClaimsParams) ([]uuid.UUID, error)
	GetUserForAccessUpdate(ctx context.Context, arg GetUserForAccessUpdateParams) (User, error)
	GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error)
	GetUserPositionIDs(ctx context.Context, arg GetUserPositionIDsParams) ([]uuid.UUID, error)
	GetUserWithPositions(ctx context.Context, arg GetUserWithPositionsParams) (GetUserWithPositionsRow, error)
	GetUsersByIDs(ctx context.Context, arg GetUsersByIDsParams) ([]GetUsersByIDsRow, error)
	GrantEmployeeSectionAccess(ctx context.Context, arg GrantEmployeeSectionAccessParams) error
	IsPendingBootstrapUser(ctx context.Context, arg IsPendingBootstrapUserParams) (bool, error)
	ListAmoUsersForReconciliation(ctx context.Context, companyID uuid.UUID) ([]User, error)
	ListDepartments(ctx context.Context, companyID uuid.UUID) ([]Department, error)
	ListDistributionEvents(ctx context.Context, arg ListDistributionEventsParams) ([]DistributionEvent, error)
	ListDistributionGroups(ctx context.Context, companyID uuid.UUID) ([]DistributionGroup, error)
	ListDistributionGroupsContainingUserForUpdate(ctx context.Context, arg ListDistributionGroupsContainingUserForUpdateParams) ([]DistributionGroup, error)
	ListEmployeeSectionAccess(ctx context.Context, arg ListEmployeeSectionAccessParams) ([]string, error)
	ListInvites(ctx context.Context, companyID uuid.UUID) ([]Invite, error)
	ListOnboardingParticipants(ctx context.Context, companyID uuid.UUID) ([]ListOnboardingParticipantsRow, error)
	ListPositions(ctx context.Context, companyID uuid.UUID) ([]Position, error)
	ListSchedules(ctx context.Context, companyID uuid.UUID) ([]UserSchedule, error)
	ListShiftExceptionsByMonth(ctx context.Context, arg ListShiftExceptionsByMonthParams) ([]ShiftException, error)
	ListUsers(ctx context.Context, companyID uuid.UUID) ([]ListUsersRow, error)
	LockAmoUserSync(ctx context.Context, companyID uuid.UUID) error
	LockProvisioningAccount(ctx context.Context, arg LockProvisioningAccountParams) error
	LockProvisioningKey(ctx context.Context, arg LockProvisioningKeyParams) error
	MarkAmoUserExternallyDeleted(ctx context.Context, arg MarkAmoUserExternallyDeletedParams) (User, error)
	MarkExternalIdentityVerified(ctx context.Context, arg MarkExternalIdentityVerifiedParams) (UserExternalIdentity, error)
	MoveDepartment(ctx context.Context, arg MoveDepartmentParams) (Department, error)
	ReassignUserInvites(ctx context.Context, arg ReassignUserInvitesParams) error
	RemoveUserFromDistributionGroups(ctx context.Context, arg RemoveUserFromDistributionGroupsParams) error
	ResendInvite(ctx context.Context, arg ResendInviteParams) (Invite, error)
	ResetDistributionEvents(ctx context.Context, arg ResetDistributionEventsParams) (int64, error)
	ResolveDepartmentUserIDs(ctx context.Context, arg ResolveDepartmentUserIDsParams) ([]uuid.UUID, error)
	ResolvePositionUserIDs(ctx context.Context, arg ResolvePositionUserIDsParams) ([]uuid.UUID, error)
	ResolveReportUserScope(ctx context.Context, arg ResolveReportUserScopeParams) ([]ResolveReportUserScopeRow, error)
	RevokeActiveSSOTokens(ctx context.Context, arg RevokeActiveSSOTokensParams) (int64, error)
	RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error
	RevokeBootstrapActivations(ctx context.Context, arg RevokeBootstrapActivationsParams) (int64, error)
	RevokeInvite(ctx context.Context, arg RevokeInviteParams) (Invite, error)
	RevokeSessionByHash(ctx context.Context, arg RevokeSessionByHashParams) (int64, error)
	RotateSession(ctx context.Context, arg RotateSessionParams) (int64, error)
	SetCompanyOwner(ctx context.Context, arg SetCompanyOwnerParams) (Company, error)
	SetCredential(ctx context.Context, arg SetCredentialParams) error
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error)
	UpdateCompanyIntegrationStatus(ctx context.Context, arg UpdateCompanyIntegrationStatusParams) (CompanyIntegration, error)
	UpdateCurrentUser(ctx context.Context, arg UpdateCurrentUserParams) (User, error)
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error)
	UpdateDistributionGroup(ctx context.Context, arg UpdateDistributionGroupParams) (DistributionGroup, error)
	UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertAccessLink(ctx context.Context, arg UpsertAccessLinkParams) (AccessLink, error)
	UpsertSchedule(ctx context.Context, arg UpsertScheduleParams) (UserSchedule, error)
	UpsertShiftException(ctx context.Context, arg UpsertShiftExceptionParams) (ShiftException, error)
}

var _ Querier = (*Queries)(nil)
