// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveCourse = `-- name: ArchiveCourse :one
UPDATE courses
SET lifecycle_status = 'archived',
    archived_at = $1,
    archived_by_id = $2,
    updated_at = $1
WHERE company_id = $3
  AND id = $4
  AND lifecycle_status = 'active'
RETURNING id, company_id, title, description, cover_url, status, author_id,
    sequential, deadline_days, created_at, updated_at, visibility,
    owner_type, owner_user_id, created_by_id, lifecycle_status,
    distribution_status, archived_at, archived_by_id, deleted_at, deleted_by_id,
    current_draft_version_id, latest_published_version_id
`

type ArchiveCourseParams struct {
	ArchivedAt   pgtype.Timestamptz `json:"archived_at"`
	ArchivedByID uuid.NullUUID      `json:"archived_by_id"`
	CompanyID    uuid.UUID          `json:"company_id"`
	ID           uuid.UUID          `json:"id"`
}

func (q *Queries) ArchiveCourse(ctx context.Context, arg ArchiveCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, archiveCourse,
		arg.ArchivedAt,
		arg.ArchivedByID,
		arg.CompanyID,
		arg.ID,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.CoverUrl,
		&i.Status,
		&i.AuthorID,
		&i.Sequential,
		&i.DeadlineDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Visibility,
		&i.OwnerType,
		&i.OwnerUserID,
		&i.CreatedByID,
		&i.LifecycleStatus,
		&i.DistributionStatus,
		&i.ArchivedAt,
		&i.ArchivedByID,
		&i.DeletedAt,
		&i.DeletedByID,
		&i.CurrentDraftVersionID,
		&i.LatestPublishedVersionID,
	)
	return i, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (
    id, company_id, title, description, cover_url, status, author_id,
    sequential, deadline_days, created_at, updated_at, visibility
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10, $11)
RETURNING id, company_id, title, description, cover_url, status, author_id,
    sequential, deadline_days, created_at, updated_at, visibility,
    owner_type, owner_user_id, created_by_id, lifecycle_status,
    distribution_status, archived_at, archived_by_id, deleted_at, deleted_by_id,
    current_draft_version_id, latest_published_version_id
`

type CreateCourseParams struct {
	ID           uuid.UUID   `json:"id"`
	CompanyID    uuid.UUID   `json:"company_id"`
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	CoverUrl     pgtype.Text `json:"cover_url"`
	Status       string      `json:"status"`
	AuthorID     uuid.UUID   `json:"author_id"`
	Sequential   bool        `json:"sequential"`
	DeadlineDays pgtype.Int4 `json:"deadline_days"`
	CreatedAt    time.Time   `json:"created_at"`
	Visibility   string      `json:"visibility"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.ID,
		arg.CompanyID,
		arg.Title,
		arg.Description,
		arg.CoverUrl,
		arg.Status,
		arg.AuthorID,
		arg.Sequential,
		arg.DeadlineDays,
		arg.CreatedAt,
		arg.Visibility,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.CoverUrl,
		&i.Status,
		&i.AuthorID,
		&i.Sequential,
		&i.DeadlineDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Visibility,
		&i.OwnerType,
		&i.OwnerUserID,
		&i.CreatedByID,
		&i.LifecycleStatus,
		&i.DistributionStatus,
		&i.ArchivedAt,
		&i.ArchivedByID,
		&i.DeletedAt,
		&i.DeletedByID,
		&i.CurrentDraftVersionID,
		&i.LatestPublishedVersionID,
	)
	return i, err
}

const createOwnedCourse = `-- name: CreateOwnedCourse :one
INSERT INTO courses (
    id, company_id, title, description, cover_url, status, author_id,
    sequential, deadline_days, created_at, updated_at, visibility,
    owner_type, owner_user_id, created_by_id
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $10, $11, $12,
    $13, $14
)
RETURNING id, company_id, title, description, cover_url, status, author_id,
    sequential, deadline_days, created_at, updated_at, visibility,
    owner_type, owner_user_id, created_by_id, lifecycle_status,
    distribution_status, archived_at, archived_by_id, deleted_at, deleted_by_id,
    current_draft_version_id, latest_published_version_id
`

type CreateOwnedCourseParams struct {
	ID           uuid.UUID     `json:"id"`
	CompanyID    uuid.UUID     `json:"company_id"`
	Title        string        `json:"title"`
	Description  pgtype.Text   `json:"description"`
	CoverUrl     pgtype.Text   `json:"cover_url"`
	Status       string        `json:"status"`
	AuthorID     uuid.UUID     `json:"author_id"`
	Sequential   bool          `json:"sequential"`
	DeadlineDays pgtype.Int4   `json:"deadline_days"`
	CreatedAt    time.Time     `json:"created_at"`
	Visibility   string        `json:"visibility"`
	OwnerType    string        `json:"owner_type"`
	OwnerUserID  uuid.NullUUID `json:"owner_user_id"`
	CreatedByID  uuid.NullUUID `json:"created_by_id"`
}

func (q *Queries) CreateOwnedCourse(ctx context.Context, arg CreateOwnedCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createOwnedCourse,
		arg.ID,
		arg.CompanyID,
		arg.Title,
		arg.Description,
		arg.CoverUrl,
		arg.Status,
		arg.AuthorID,
		arg.Sequential,
		arg.DeadlineDays,
		arg.CreatedAt,
		arg.Visibility,
		arg.OwnerType,
		arg.OwnerUserID,
		arg.CreatedByID,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.CoverUrl,
		&i.Status,
		&i.AuthorID,
		&i.Sequential,
		&i.DeadlineDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Visibility,
		&i.OwnerType,
		&i.OwnerUserID,
		&i.CreatedByID,
		&i.LifecycleStatus,
		&i.DistributionStatus,
		&i.ArchivedAt,
		&i.ArchivedByID,
		&i.DeletedAt,
		&i.DeletedByID,
		&i.CurrentDraftVersionID,
		&i.LatestPublishedVersionID,
	)
	return i, err
}

const deleteCourseLegacyHard = `-- name: DeleteCourseLegacyHard :execrows
DELETE FROM courses
WHERE company_id = $1 AND id = $2
`

type DeleteCourseLegacyHardParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) DeleteCourseLegacyHard(ctx context.Context, arg DeleteCourseLegacyHardParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCourseLegacyHard, arg.CompanyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCourse = `-- name: GetCourse :one
SELECT id, company_id, title, description, cover_url, status, author_id,
    sequential, deadline_days, created_at, updated_at, visibility,
    owner_type, owner_user_id, created_by_id, lifecycle_status,
    distribution_status, archived_at, archived_by_id, deleted_at, deleted_by_id,
    current_draft_version_id, latest_published_version_id
FROM courses
WHERE company_id = $1 AND id = $2
`

type GetCourseParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetCourse(ctx context.Context, arg GetCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, getCourse, arg.CompanyID, arg.ID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.CoverUrl,
		&i.Status,
		&i.AuthorID,
		&i.Sequential,
		&i.DeadlineDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Visibility,
		&i.OwnerType,
		&i.OwnerUserID,
		&i.CreatedByID,
		&i.LifecycleStatus,
		&i.DistributionStatus,
		&i.ArchivedAt,
		&i.ArchivedByID,
		&i.DeletedAt,
		&i.DeletedByID,
		&i.CurrentDraftVersionID,
		&i.LatestPublishedVersionID,
	)
	return i, err
}

const getCourseForUpdate = `-- name: GetCourseForUpdate :one
SELECT id, company_id, title, description, cover_url, status, author_id,
    sequential, deadline_days, created_at, updated_at, visibility,
    owner_type, owner_user_id, created_by_id, lifecycle_status,
    distribution_status, archived_at, archived_by_id, deleted_at, deleted_by_id,
    current_draft_version_id, latest_published_version_id
FROM courses
WHERE company_id = $1 AND id = $2
FOR UPDATE
`

type GetCourseForUpdateParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetCourseForUpdate(ctx context.Context, arg GetCourseForUpdateParams) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseForUpdate, arg.CompanyID, arg.ID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.CoverUrl,
		&i.Status,
		&i.AuthorID,
		&i.Sequential,
		&i.DeadlineDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Visibility,
		&i.OwnerType,
		&i.OwnerUserID,
		&i.CreatedByID,
		&i.LifecycleStatus,
		&i.DistributionStatus,
		&i.ArchivedAt,
		&i.ArchivedByID,
		&i.DeletedAt,
		&i.DeletedByID,
		&i.CurrentDraftVersionID,
		&i.LatestPublishedVersionID,
	)
	return i, err
}

const getCourses = `-- name: GetCourses :many
SELECT id, company_id, title, description, cover_url, status, author_id,
    sequential, deadline_days, created_at, updated_at, visibility,
    owner_type, owner_user_id, created_by_id, lifecycle_status,
    distribution_status, archived_at, archived_by_id, deleted_at, deleted_by_id,
    current_draft_version_id, latest_published_version_id
FROM courses
WHERE company_id = $1 AND lifecycle_status <> 'deleted'
ORDER BY created_at, id
`

func (q *Queries) GetCourses(ctx context.Context, companyID uuid.UUID) ([]Course, error) {
	rows, err := q.db.Query(ctx, getCourses, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.CoverUrl,
			&i.Status,
			&i.AuthorID,
			&i.Sequential,
			&i.DeadlineDays,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Visibility,
			&i.OwnerType,
			&i.OwnerUserID,
			&i.CreatedByID,
			&i.LifecycleStatus,
			&i.DistributionStatus,
			&i.ArchivedAt,
			&i.ArchivedByID,
			&i.DeletedAt,
			&i.DeletedByID,
			&i.CurrentDraftVersionID,
			&i.LatestPublishedVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursesByIds = `-- name: GetCoursesByIds :many
SELECT id, company_id, title, description, cover_url, status, author_id,
    sequential, deadline_days, created_at, updated_at, visibility,
    owner_type, owner_user_id, created_by_id, lifecycle_status,
    distribution_status, archived_at, archived_by_id, deleted_at, deleted_by_id,
    current_draft_version_id, latest_published_version_id
FROM courses
WHERE company_id = $1 AND id = ANY($2::uuid[])
ORDER BY created_at, id
`

type GetCoursesByIdsParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	Ids       []uuid.UUID `json:"ids"`
}

func (q *Queries) GetCoursesByIds(ctx context.Context, arg GetCoursesByIdsParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, getCoursesByIds, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.CoverUrl,
			&i.Status,
			&i.AuthorID,
			&i.Sequential,
			&i.DeadlineDays,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Visibility,
			&i.OwnerType,
			&i.OwnerUserID,
			&i.CreatedByID,
			&i.LifecycleStatus,
			&i.DistributionStatus,
			&i.ArchivedAt,
			&i.ArchivedByID,
			&i.DeletedAt,
			&i.DeletedByID,
			&i.CurrentDraftVersionID,
			&i.LatestPublishedVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursesFiltered = `-- name: GetCoursesFiltered :many
SELECT id, company_id, title, description, cover_url, status, author_id,
    sequential, deadline_days, created_at, updated_at, visibility,
    owner_type, owner_user_id, created_by_id, lifecycle_status,
    distribution_status, archived_at, archived_by_id, deleted_at, deleted_by_id,
    current_draft_version_id, latest_published_version_id
FROM courses
WHERE company_id = $1
  AND ($2::text IS NULL OR owner_type = $2)
  AND ($3::uuid IS NULL OR owner_user_id = $3)
  AND ($4::text IS NULL OR lifecycle_status = $4)
  AND ($5::text IS NULL OR distribution_status = $5)
ORDER BY created_at, id
`

type GetCoursesFilteredParams struct {
	CompanyID          uuid.UUID     `json:"company_id"`
	OwnerType          pgtype.Text   `json:"owner_type"`
	OwnerUserID        uuid.NullUUID `json:"owner_user_id"`
	LifecycleStatus    pgtype.Text   `json:"lifecycle_status"`
	DistributionStatus pgtype.Text   `json:"distribution_status"`
}

func (q *Queries) GetCoursesFiltered(ctx context.Context, arg GetCoursesFilteredParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, getCoursesFiltered,
		arg.CompanyID,
		arg.OwnerType,
		arg.OwnerUserID,
		arg.LifecycleStatus,
		arg.DistributionStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.CoverUrl,
			&i.Status,
			&i.AuthorID,
			&i.Sequential,
			&i.DeadlineDays,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Visibility,
			&i.OwnerType,
			&i.OwnerUserID,
			&i.CreatedByID,
			&i.LifecycleStatus,
			&i.DistributionStatus,
			&i.ArchivedAt,
			&i.ArchivedByID,
			&i.DeletedAt,
			&i.DeletedByID,
			&i.CurrentDraftVersionID,
			&i.LatestPublishedVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicCourse = `-- name: GetPublicCourse :one
SELECT id, company_id, title, description, cover_url, status, author_id,
    sequential, deadline_days, created_at, updated_at, visibility,
    owner_type, owner_user_id, created_by_id, lifecycle_status,
    distribution_status, archived_at, archived_by_id, deleted_at, deleted_by_id,
    current_draft_version_id, latest_published_version_id
FROM courses
WHERE id = $1
  AND status = 'published'
  AND visibility = 'public'
  AND lifecycle_status = 'active'
  AND distribution_status <> 'blocked'
`

func (q *Queries) GetPublicCourse(ctx context.Context, id uuid.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getPublicCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.CoverUrl,
		&i.Status,
		&i.AuthorID,
		&i.Sequential,
		&i.DeadlineDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Visibility,
		&i.OwnerType,
		&i.OwnerUserID,
		&i.CreatedByID,
		&i.LifecycleStatus,
		&i.DistributionStatus,
		&i.ArchivedAt,
		&i.ArchivedByID,
		&i.DeletedAt,
		&i.DeletedByID,
		&i.CurrentDraftVersionID,
		&i.LatestPublishedVersionID,
	)
	return i, err
}

const lockCourseOrder = `-- name: LockCourseOrder :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::uuid::text, 0))
`

func (q *Queries) LockCourseOrder(ctx context.Context, courseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockCourseOrder, courseID)
	return err
}

const restoreCourse = `-- name: RestoreCourse :one
UPDATE courses
SET lifecycle_status = 'active',
    archived_at = NULL,
    archived_by_id = NULL,
    updated_at = $1
WHERE company_id = $2
  AND id = $3
  AND lifecycle_status = 'archived'
RETURNING id, company_id, title, description, cover_url, status, author_id,
    sequential, deadline_days, created_at, updated_at, visibility,
    owner_type, owner_user_id, created_by_id, lifecycle_status,
    distribution_status, archived_at, archived_by_id, deleted_at, deleted_by_id,
    current_draft_version_id, latest_published_version_id
`

type RestoreCourseParams struct {
	RestoredAt time.Time `json:"restored_at"`
	CompanyID  uuid.UUID `json:"company_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) RestoreCourse(ctx context.Context, arg RestoreCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, restoreCourse, arg.RestoredAt, arg.CompanyID, arg.ID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.CoverUrl,
		&i.Status,
		&i.AuthorID,
		&i.Sequential,
		&i.DeadlineDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Visibility,
		&i.OwnerType,
		&i.OwnerUserID,
		&i.CreatedByID,
		&i.LifecycleStatus,
		&i.DistributionStatus,
		&i.ArchivedAt,
		&i.ArchivedByID,
		&i.DeletedAt,
		&i.DeletedByID,
		&i.CurrentDraftVersionID,
		&i.LatestPublishedVersionID,
	)
	return i, err
}

const softDeleteCourse = `-- name: SoftDeleteCourse :one
UPDATE courses
SET lifecycle_status = 'deleted',
    deleted_at = $1,
    deleted_by_id = $2,
    updated_at = $1
WHERE company_id = $3
  AND id = $4
  AND lifecycle_status <> 'deleted'
RETURNING id, company_id, title, description, cover_url, status, author_id,
    sequential, deadline_days, created_at, updated_at, visibility,
    owner_type, owner_user_id, created_by_id, lifecycle_status,
    distribution_status, archived_at, archived_by_id, deleted_at, deleted_by_id,
    current_draft_version_id, latest_published_version_id
`

type SoftDeleteCourseParams struct {
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	DeletedByID uuid.NullUUID      `json:"deleted_by_id"`
	CompanyID   uuid.UUID          `json:"company_id"`
	ID          uuid.UUID          `json:"id"`
}

func (q *Queries) SoftDeleteCourse(ctx context.Context, arg SoftDeleteCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, softDeleteCourse,
		arg.DeletedAt,
		arg.DeletedByID,
		arg.CompanyID,
		arg.ID,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.CoverUrl,
		&i.Status,
		&i.AuthorID,
		&i.Sequential,
		&i.DeadlineDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Visibility,
		&i.OwnerType,
		&i.OwnerUserID,
		&i.CreatedByID,
		&i.LifecycleStatus,
		&i.DistributionStatus,
		&i.ArchivedAt,
		&i.ArchivedByID,
		&i.DeletedAt,
		&i.DeletedByID,
		&i.CurrentDraftVersionID,
		&i.LatestPublishedVersionID,
	)
	return i, err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET title = coalesce($3, title),
    description = CASE WHEN $4::boolean THEN $5 ELSE description END,
    status = coalesce($6, status),
    sequential = coalesce($7, sequential),
    deadline_days = CASE WHEN $8::boolean THEN $9 ELSE deadline_days END,
    visibility = coalesce($10, visibility),
    updated_at = $11
WHERE company_id = $1 AND id = $2 AND lifecycle_status <> 'deleted'
RETURNING id, company_id, title, description, cover_url, status, author_id,
    sequential, deadline_days, created_at, updated_at, visibility,
    owner_type, owner_user_id, created_by_id, lifecycle_status,
    distribution_status, archived_at, archived_by_id, deleted_at, deleted_by_id,
    current_draft_version_id, latest_published_version_id
`

type UpdateCourseParams struct {
	CompanyID       uuid.UUID   `json:"company_id"`
	ID              uuid.UUID   `json:"id"`
	Title           pgtype.Text `json:"title"`
	SetDescription  bool        `json:"set_description"`
	Description     pgtype.Text `json:"description"`
	Status          pgtype.Text `json:"status"`
	Sequential      pgtype.Bool `json:"sequential"`
	SetDeadlineDays bool        `json:"set_deadline_days"`
	DeadlineDays    pgtype.Int4 `json:"deadline_days"`
	Visibility      pgtype.Text `json:"visibility"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.CompanyID,
		arg.ID,
		arg.Title,
		arg.SetDescription,
		arg.Description,
		arg.Status,
		arg.Sequential,
		arg.SetDeadlineDays,
		arg.DeadlineDays,
		arg.Visibility,
		arg.UpdatedAt,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.CoverUrl,
		&i.Status,
		&i.AuthorID,
		&i.Sequential,
		&i.DeadlineDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Visibility,
		&i.OwnerType,
		&i.OwnerUserID,
		&i.CreatedByID,
		&i.LifecycleStatus,
		&i.DistributionStatus,
		&i.ArchivedAt,
		&i.ArchivedByID,
		&i.DeletedAt,
		&i.DeletedByID,
		&i.CurrentDraftVersionID,
		&i.LatestPublishedVersionID,
	)
	return i, err
}

const updateCourseDistributionStatus = `-- name: UpdateCourseDistributionStatus :one
UPDATE courses
SET distribution_status = $1,
    updated_at = $2
WHERE company_id = $3
  AND id = $4
  AND owner_type = 'partner'
  AND lifecycle_status <> 'deleted'
RETURNING id, company_id, title, description, cover_url, status, author_id,
    sequential, deadline_days, created_at, updated_at, visibility,
    owner_type, owner_user_id, created_by_id, lifecycle_status,
    distribution_status, archived_at, archived_by_id, deleted_at, deleted_by_id,
    current_draft_version_id, latest_published_version_id
`

type UpdateCourseDistributionStatusParams struct {
	DistributionStatus string    `json:"distribution_status"`
	UpdatedAt          time.Time `json:"updated_at"`
	CompanyID          uuid.UUID `json:"company_id"`
	ID                 uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCourseDistributionStatus(ctx context.Context, arg UpdateCourseDistributionStatusParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourseDistributionStatus,
		arg.DistributionStatus,
		arg.UpdatedAt,
		arg.CompanyID,
		arg.ID,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.CoverUrl,
		&i.Status,
		&i.AuthorID,
		&i.Sequential,
		&i.DeadlineDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Visibility,
		&i.OwnerType,
		&i.OwnerUserID,
		&i.CreatedByID,
		&i.LifecycleStatus,
		&i.DistributionStatus,
		&i.ArchivedAt,
		&i.ArchivedByID,
		&i.DeletedAt,
		&i.DeletedByID,
		&i.CurrentDraftVersionID,
		&i.LatestPublishedVersionID,
	)
	return i, err
}
