// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course_versions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearCourseCurrentDraftVersion = `-- name: ClearCourseCurrentDraftVersion :execrows
UPDATE courses
SET current_draft_version_id = NULL,
    updated_at = $1
WHERE company_id = $2
  AND id = $3
  AND current_draft_version_id = $4
`

type ClearCourseCurrentDraftVersionParams struct {
	UpdatedAt time.Time     `json:"updated_at"`
	CompanyID uuid.UUID     `json:"company_id"`
	CourseID  uuid.UUID     `json:"course_id"`
	VersionID uuid.NullUUID `json:"version_id"`
}

func (q *Queries) ClearCourseCurrentDraftVersion(ctx context.Context, arg ClearCourseCurrentDraftVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearCourseCurrentDraftVersion,
		arg.UpdatedAt,
		arg.CompanyID,
		arg.CourseID,
		arg.VersionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cloneCourseVersionLessons = `-- name: CloneCourseVersionLessons :execrows
INSERT INTO course_version_lessons (
    id, company_id, course_version_id, section_version_id, stable_key,
    title, "order", content, source_type, source_article_id,
    source_article_version, source_template_id, source_template_version_id,
    estimated_minutes, file_ids, kb_snapshot_id
)
SELECT gen_random_uuid(), target.company_id, target.id, target_section.id,
       source.stable_key, source.title, source."order", source.content,
       source.source_type, source.source_article_id,
       source.source_article_version, source.source_template_id,
       source.source_template_version_id, source.estimated_minutes,
       source.file_ids, source.kb_snapshot_id
FROM course_version_lessons AS source
JOIN course_version_sections AS source_section
  ON source_section.id = source.section_version_id
JOIN course_versions AS target
  ON target.company_id = source.company_id
 AND target.id = $1
 AND target.status = 'draft'
JOIN course_version_sections AS target_section
  ON target_section.course_version_id = target.id
 AND target_section.stable_key = source_section.stable_key
WHERE source.company_id = $2
  AND source.course_version_id = $3
ORDER BY target_section."order", source."order", source.id
`

type CloneCourseVersionLessonsParams struct {
	TargetVersionID uuid.UUID `json:"target_version_id"`
	CompanyID       uuid.UUID `json:"company_id"`
	SourceVersionID uuid.UUID `json:"source_version_id"`
}

func (q *Queries) CloneCourseVersionLessons(ctx context.Context, arg CloneCourseVersionLessonsParams) (int64, error) {
	result, err := q.db.Exec(ctx, cloneCourseVersionLessons, arg.TargetVersionID, arg.CompanyID, arg.SourceVersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cloneCourseVersionQuizzes = `-- name: CloneCourseVersionQuizzes :execrows
WITH inserted AS (
    INSERT INTO course_version_quizzes (
        id, company_id, course_version_id, lesson_version_id,
        questions, passing_score, max_attempts
    )
    SELECT gen_random_uuid(), target.company_id, target.id, target_lesson.id,
           source.questions, source.passing_score, source.max_attempts
    FROM course_version_quizzes AS source
    JOIN course_version_lessons AS source_lesson
      ON source_lesson.id = source.lesson_version_id
    JOIN course_versions AS target
      ON target.company_id = source.company_id
     AND target.id = $1
     AND target.status = 'draft'
    JOIN course_version_lessons AS target_lesson
      ON target_lesson.course_version_id = target.id
     AND target_lesson.stable_key = source_lesson.stable_key
    WHERE source.company_id = $2
      AND source.course_version_id = $3
    RETURNING id, lesson_version_id
)
UPDATE course_version_lessons AS lesson
SET quiz_version_id = inserted.id
FROM inserted
WHERE lesson.id = inserted.lesson_version_id
`

type CloneCourseVersionQuizzesParams struct {
	TargetVersionID uuid.UUID `json:"target_version_id"`
	CompanyID       uuid.UUID `json:"company_id"`
	SourceVersionID uuid.UUID `json:"source_version_id"`
}

func (q *Queries) CloneCourseVersionQuizzes(ctx context.Context, arg CloneCourseVersionQuizzesParams) (int64, error) {
	result, err := q.db.Exec(ctx, cloneCourseVersionQuizzes, arg.TargetVersionID, arg.CompanyID, arg.SourceVersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cloneCourseVersionSections = `-- name: CloneCourseVersionSections :execrows
INSERT INTO course_version_sections (
    id, company_id, course_version_id, stable_key, title, "order"
)
SELECT gen_random_uuid(), target.company_id, target.id, source.stable_key,
       source.title, source."order"
FROM course_version_sections AS source
JOIN course_versions AS target
  ON target.company_id = source.company_id
 AND target.id = $1
 AND target.status = 'draft'
WHERE source.company_id = $2
  AND source.course_version_id = $3
ORDER BY source."order", source.id
`

type CloneCourseVersionSectionsParams struct {
	TargetVersionID uuid.UUID `json:"target_version_id"`
	CompanyID       uuid.UUID `json:"company_id"`
	SourceVersionID uuid.UUID `json:"source_version_id"`
}

func (q *Queries) CloneCourseVersionSections(ctx context.Context, arg CloneCourseVersionSectionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, cloneCourseVersionSections, arg.TargetVersionID, arg.CompanyID, arg.SourceVersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCourseVersion = `-- name: CreateCourseVersion :one
INSERT INTO course_versions (
    id, company_id, course_id, number, status, title, description,
    cover_file_id, cover_url, sequential, default_internal_deadline_days,
    created_by_id, created_at
)
VALUES (
    $1, $2, $3, $4,
    'draft', $5, $6, $7,
    $8, $9,
    $10, $11,
    $12
)
RETURNING id, company_id, course_id, number, status, title, description,
    cover_file_id, cover_url, sequential, default_internal_deadline_days,
    created_by_id, created_at, published_by_id, published_at, content_hash
`

type CreateCourseVersionParams struct {
	ID                          uuid.UUID     `json:"id"`
	CompanyID                   uuid.UUID     `json:"company_id"`
	CourseID                    uuid.UUID     `json:"course_id"`
	Number                      int32         `json:"number"`
	Title                       string        `json:"title"`
	Description                 pgtype.Text   `json:"description"`
	CoverFileID                 uuid.NullUUID `json:"cover_file_id"`
	CoverUrl                    pgtype.Text   `json:"cover_url"`
	Sequential                  bool          `json:"sequential"`
	DefaultInternalDeadlineDays pgtype.Int4   `json:"default_internal_deadline_days"`
	CreatedByID                 uuid.UUID     `json:"created_by_id"`
	CreatedAt                   time.Time     `json:"created_at"`
}

func (q *Queries) CreateCourseVersion(ctx context.Context, arg CreateCourseVersionParams) (CourseVersion, error) {
	row := q.db.QueryRow(ctx, createCourseVersion,
		arg.ID,
		arg.CompanyID,
		arg.CourseID,
		arg.Number,
		arg.Title,
		arg.Description,
		arg.CoverFileID,
		arg.CoverUrl,
		arg.Sequential,
		arg.DefaultInternalDeadlineDays,
		arg.CreatedByID,
		arg.CreatedAt,
	)
	var i CourseVersion
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.Number,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CoverFileID,
		&i.CoverUrl,
		&i.Sequential,
		&i.DefaultInternalDeadlineDays,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.PublishedByID,
		&i.PublishedAt,
		&i.ContentHash,
	)
	return i, err
}

const createCourseVersionLesson = `-- name: CreateCourseVersionLesson :one
INSERT INTO course_version_lessons (
    id, company_id, course_version_id, section_version_id, stable_key,
    title, "order", content, source_type, source_article_id,
    source_article_version, source_template_id, source_template_version_id,
    estimated_minutes, file_ids, kb_snapshot_id
)
SELECT $1, version.company_id, version.id,
       $2, $3, $4,
       $5, $6, $7,
       $8, $9,
       $10, $11,
       $12,
       COALESCE($13::uuid[], '{}'::uuid[]),
       $14
FROM course_versions AS version
JOIN course_version_sections AS section
  ON section.company_id = version.company_id
 AND section.course_version_id = version.id
 AND section.id = $2
WHERE version.company_id = $15
  AND version.id = $16
  AND version.status = 'draft'
RETURNING id, company_id, course_version_id, section_version_id, stable_key,
    title, "order", content, source_type, source_article_id,
    source_article_version, source_template_id, source_template_version_id,
    estimated_minutes, quiz_version_id, kb_snapshot_id, file_ids
`

type CreateCourseVersionLessonParams struct {
	ID                      uuid.UUID     `json:"id"`
	SectionVersionID        uuid.UUID     `json:"section_version_id"`
	StableKey               uuid.UUID     `json:"stable_key"`
	Title                   string        `json:"title"`
	OrderValue              int32         `json:"order_value"`
	Content                 []byte        `json:"content"`
	SourceType              string        `json:"source_type"`
	SourceArticleID         uuid.NullUUID `json:"source_article_id"`
	SourceArticleVersion    pgtype.Int4   `json:"source_article_version"`
	SourceTemplateID        uuid.NullUUID `json:"source_template_id"`
	SourceTemplateVersionID uuid.NullUUID `json:"source_template_version_id"`
	EstimatedMinutes        pgtype.Int4   `json:"estimated_minutes"`
	FileIds                 []uuid.UUID   `json:"file_ids"`
	KbSnapshotID            uuid.NullUUID `json:"kb_snapshot_id"`
	CompanyID               uuid.UUID     `json:"company_id"`
	CourseVersionID         uuid.UUID     `json:"course_version_id"`
}

func (q *Queries) CreateCourseVersionLesson(ctx context.Context, arg CreateCourseVersionLessonParams) (CourseVersionLesson, error) {
	row := q.db.QueryRow(ctx, createCourseVersionLesson,
		arg.ID,
		arg.SectionVersionID,
		arg.StableKey,
		arg.Title,
		arg.OrderValue,
		arg.Content,
		arg.SourceType,
		arg.SourceArticleID,
		arg.SourceArticleVersion,
		arg.SourceTemplateID,
		arg.SourceTemplateVersionID,
		arg.EstimatedMinutes,
		arg.FileIds,
		arg.KbSnapshotID,
		arg.CompanyID,
		arg.CourseVersionID,
	)
	var i CourseVersionLesson
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseVersionID,
		&i.SectionVersionID,
		&i.StableKey,
		&i.Title,
		&i.Order,
		&i.Content,
		&i.SourceType,
		&i.SourceArticleID,
		&i.SourceArticleVersion,
		&i.SourceTemplateID,
		&i.SourceTemplateVersionID,
		&i.EstimatedMinutes,
		&i.QuizVersionID,
		&i.KbSnapshotID,
		&i.FileIds,
	)
	return i, err
}

const createCourseVersionPublishIdempotency = `-- name: CreateCourseVersionPublishIdempotency :one
INSERT INTO course_version_publish_idempotency (
    id, company_id, course_id, idempotency_key, version_id, created_at
)
VALUES (
    $1, $2, $3,
    $4, $5, $6
)
ON CONFLICT (company_id, course_id, idempotency_key) DO NOTHING
RETURNING id, company_id, course_id, idempotency_key, version_id, created_at
`

type CreateCourseVersionPublishIdempotencyParams struct {
	ID             uuid.UUID `json:"id"`
	CompanyID      uuid.UUID `json:"company_id"`
	CourseID       uuid.UUID `json:"course_id"`
	IdempotencyKey string    `json:"idempotency_key"`
	VersionID      uuid.UUID `json:"version_id"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) CreateCourseVersionPublishIdempotency(ctx context.Context, arg CreateCourseVersionPublishIdempotencyParams) (CourseVersionPublishIdempotency, error) {
	row := q.db.QueryRow(ctx, createCourseVersionPublishIdempotency,
		arg.ID,
		arg.CompanyID,
		arg.CourseID,
		arg.IdempotencyKey,
		arg.VersionID,
		arg.CreatedAt,
	)
	var i CourseVersionPublishIdempotency
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.IdempotencyKey,
		&i.VersionID,
		&i.CreatedAt,
	)
	return i, err
}

const createCourseVersionQuiz = `-- name: CreateCourseVersionQuiz :one
WITH inserted AS (
    INSERT INTO course_version_quizzes (
        id, company_id, course_version_id, lesson_version_id,
        questions, passing_score, max_attempts
    )
    SELECT $1, version.company_id, version.id,
           $2, $3,
           $4, $5
    FROM course_versions AS version
    JOIN course_version_lessons AS lesson
      ON lesson.company_id = version.company_id
     AND lesson.course_version_id = version.id
     AND lesson.id = $2
    WHERE version.company_id = $6
      AND version.id = $7
      AND version.status = 'draft'
    RETURNING id, company_id, course_version_id, lesson_version_id,
        questions, passing_score, max_attempts
), linked AS (
    UPDATE course_version_lessons AS lesson
    SET quiz_version_id = inserted.id
    FROM inserted
    WHERE lesson.id = inserted.lesson_version_id
    RETURNING inserted.id, inserted.company_id, inserted.course_version_id, inserted.lesson_version_id, inserted.questions, inserted.passing_score, inserted.max_attempts
)
SELECT id, company_id, course_version_id, lesson_version_id, questions,
    passing_score, max_attempts
FROM linked
`

type CreateCourseVersionQuizParams struct {
	ID              uuid.UUID   `json:"id"`
	LessonVersionID uuid.UUID   `json:"lesson_version_id"`
	Questions       []byte      `json:"questions"`
	PassingScore    int32       `json:"passing_score"`
	MaxAttempts     pgtype.Int4 `json:"max_attempts"`
	CompanyID       uuid.UUID   `json:"company_id"`
	CourseVersionID uuid.UUID   `json:"course_version_id"`
}

type CreateCourseVersionQuizRow struct {
	ID              uuid.UUID   `json:"id"`
	CompanyID       uuid.UUID   `json:"company_id"`
	CourseVersionID uuid.UUID   `json:"course_version_id"`
	LessonVersionID uuid.UUID   `json:"lesson_version_id"`
	Questions       []byte      `json:"questions"`
	PassingScore    int32       `json:"passing_score"`
	MaxAttempts     pgtype.Int4 `json:"max_attempts"`
}

func (q *Queries) CreateCourseVersionQuiz(ctx context.Context, arg CreateCourseVersionQuizParams) (CreateCourseVersionQuizRow, error) {
	row := q.db.QueryRow(ctx, createCourseVersionQuiz,
		arg.ID,
		arg.LessonVersionID,
		arg.Questions,
		arg.PassingScore,
		arg.MaxAttempts,
		arg.CompanyID,
		arg.CourseVersionID,
	)
	var i CreateCourseVersionQuizRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseVersionID,
		&i.LessonVersionID,
		&i.Questions,
		&i.PassingScore,
		&i.MaxAttempts,
	)
	return i, err
}

const createCourseVersionSection = `-- name: CreateCourseVersionSection :one
INSERT INTO course_version_sections (
    id, company_id, course_version_id, stable_key, title, "order"
)
SELECT $1, version.company_id, version.id, $2,
       $3, $4
FROM course_versions AS version
WHERE version.company_id = $5
  AND version.id = $6
  AND version.status = 'draft'
RETURNING id, company_id, course_version_id, stable_key, title, "order"
`

type CreateCourseVersionSectionParams struct {
	ID              uuid.UUID `json:"id"`
	StableKey       uuid.UUID `json:"stable_key"`
	Title           string    `json:"title"`
	OrderValue      int32     `json:"order_value"`
	CompanyID       uuid.UUID `json:"company_id"`
	CourseVersionID uuid.UUID `json:"course_version_id"`
}

func (q *Queries) CreateCourseVersionSection(ctx context.Context, arg CreateCourseVersionSectionParams) (CourseVersionSection, error) {
	row := q.db.QueryRow(ctx, createCourseVersionSection,
		arg.ID,
		arg.StableKey,
		arg.Title,
		arg.OrderValue,
		arg.CompanyID,
		arg.CourseVersionID,
	)
	var i CourseVersionSection
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseVersionID,
		&i.StableKey,
		&i.Title,
		&i.Order,
	)
	return i, err
}

const createNextDraftCourseVersionFromPublished = `-- name: CreateNextDraftCourseVersionFromPublished :one
INSERT INTO course_versions (
    id, company_id, course_id, number, status, title, description,
    cover_file_id, cover_url, sequential, default_internal_deadline_days,
    created_by_id, created_at
)
SELECT $1, source.company_id, source.course_id,
       source.number + 1, 'draft', source.title, source.description,
       source.cover_file_id, source.cover_url, source.sequential,
       source.default_internal_deadline_days, $2,
       $3
FROM course_versions AS source
WHERE source.company_id = $4
  AND source.id = $5
  AND source.status IN ('published', 'retired')
RETURNING id, company_id, course_id, number, status, title, description,
    cover_file_id, cover_url, sequential, default_internal_deadline_days,
    created_by_id, created_at, published_by_id, published_at, content_hash
`

type CreateNextDraftCourseVersionFromPublishedParams struct {
	ID              uuid.UUID `json:"id"`
	CreatedByID     uuid.UUID `json:"created_by_id"`
	CreatedAt       time.Time `json:"created_at"`
	CompanyID       uuid.UUID `json:"company_id"`
	SourceVersionID uuid.UUID `json:"source_version_id"`
}

func (q *Queries) CreateNextDraftCourseVersionFromPublished(ctx context.Context, arg CreateNextDraftCourseVersionFromPublishedParams) (CourseVersion, error) {
	row := q.db.QueryRow(ctx, createNextDraftCourseVersionFromPublished,
		arg.ID,
		arg.CreatedByID,
		arg.CreatedAt,
		arg.CompanyID,
		arg.SourceVersionID,
	)
	var i CourseVersion
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.Number,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CoverFileID,
		&i.CoverUrl,
		&i.Sequential,
		&i.DefaultInternalDeadlineDays,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.PublishedByID,
		&i.PublishedAt,
		&i.ContentHash,
	)
	return i, err
}

const deleteCourseVersionLesson = `-- name: DeleteCourseVersionLesson :execrows
DELETE FROM course_version_lessons AS lesson
USING course_versions AS version
WHERE lesson.company_id = $1
  AND lesson.id = $2
  AND version.id = lesson.course_version_id
  AND version.status = 'draft'
`

type DeleteCourseVersionLessonParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) DeleteCourseVersionLesson(ctx context.Context, arg DeleteCourseVersionLessonParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCourseVersionLesson, arg.CompanyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCourseVersionQuiz = `-- name: DeleteCourseVersionQuiz :execrows
WITH unlinked AS (
    UPDATE course_version_lessons AS lesson
    SET quiz_version_id = NULL
    FROM course_version_quizzes AS quiz, course_versions AS version
    WHERE quiz.company_id = $1
      AND quiz.id = $2
      AND lesson.id = quiz.lesson_version_id
      AND version.id = quiz.course_version_id
      AND version.status = 'draft'
    RETURNING quiz.id
)
DELETE FROM course_version_quizzes AS quiz
USING unlinked
WHERE quiz.id = unlinked.id
`

type DeleteCourseVersionQuizParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) DeleteCourseVersionQuiz(ctx context.Context, arg DeleteCourseVersionQuizParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCourseVersionQuiz, arg.CompanyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCourseVersionSection = `-- name: DeleteCourseVersionSection :execrows
DELETE FROM course_version_sections AS section
USING course_versions AS version
WHERE section.company_id = $1
  AND section.id = $2
  AND version.id = section.course_version_id
  AND version.status = 'draft'
`

type DeleteCourseVersionSectionParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) DeleteCourseVersionSection(ctx context.Context, arg DeleteCourseVersionSectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCourseVersionSection, arg.CompanyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDraftCourseVersion = `-- name: DeleteDraftCourseVersion :execrows
DELETE FROM course_versions
WHERE company_id = $1
  AND id = $2
  AND status = 'draft'
`

type DeleteDraftCourseVersionParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) DeleteDraftCourseVersion(ctx context.Context, arg DeleteDraftCourseVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraftCourseVersion, arg.CompanyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCourseVersion = `-- name: GetCourseVersion :one
SELECT id, company_id, course_id, number, status, title, description,
    cover_file_id, cover_url, sequential, default_internal_deadline_days,
    created_by_id, created_at, published_by_id, published_at, content_hash
FROM course_versions
WHERE company_id = $1
  AND id = $2
`

type GetCourseVersionParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetCourseVersion(ctx context.Context, arg GetCourseVersionParams) (CourseVersion, error) {
	row := q.db.QueryRow(ctx, getCourseVersion, arg.CompanyID, arg.ID)
	var i CourseVersion
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.Number,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CoverFileID,
		&i.CoverUrl,
		&i.Sequential,
		&i.DefaultInternalDeadlineDays,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.PublishedByID,
		&i.PublishedAt,
		&i.ContentHash,
	)
	return i, err
}

const getCourseVersionByLesson = `-- name: GetCourseVersionByLesson :one
SELECT version.id, version.company_id, version.course_id, version.number,
    version.status, version.title, version.description, version.cover_file_id,
    version.cover_url, version.sequential,
    version.default_internal_deadline_days, version.created_by_id,
    version.created_at, version.published_by_id, version.published_at,
    version.content_hash
FROM course_version_lessons AS lesson
JOIN course_versions AS version ON version.id = lesson.course_version_id
WHERE lesson.company_id = $1
  AND lesson.id = $2
`

type GetCourseVersionByLessonParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	LessonID  uuid.UUID `json:"lesson_id"`
}

func (q *Queries) GetCourseVersionByLesson(ctx context.Context, arg GetCourseVersionByLessonParams) (CourseVersion, error) {
	row := q.db.QueryRow(ctx, getCourseVersionByLesson, arg.CompanyID, arg.LessonID)
	var i CourseVersion
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.Number,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CoverFileID,
		&i.CoverUrl,
		&i.Sequential,
		&i.DefaultInternalDeadlineDays,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.PublishedByID,
		&i.PublishedAt,
		&i.ContentHash,
	)
	return i, err
}

const getCourseVersionByNumber = `-- name: GetCourseVersionByNumber :one
SELECT id, company_id, course_id, number, status, title, description,
    cover_file_id, cover_url, sequential, default_internal_deadline_days,
    created_by_id, created_at, published_by_id, published_at, content_hash
FROM course_versions
WHERE company_id = $1
  AND course_id = $2
  AND number = $3
`

type GetCourseVersionByNumberParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	CourseID  uuid.UUID `json:"course_id"`
	Number    int32     `json:"number"`
}

func (q *Queries) GetCourseVersionByNumber(ctx context.Context, arg GetCourseVersionByNumberParams) (CourseVersion, error) {
	row := q.db.QueryRow(ctx, getCourseVersionByNumber, arg.CompanyID, arg.CourseID, arg.Number)
	var i CourseVersion
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.Number,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CoverFileID,
		&i.CoverUrl,
		&i.Sequential,
		&i.DefaultInternalDeadlineDays,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.PublishedByID,
		&i.PublishedAt,
		&i.ContentHash,
	)
	return i, err
}

const getCourseVersionByQuiz = `-- name: GetCourseVersionByQuiz :one
SELECT version.id, version.company_id, version.course_id, version.number,
    version.status, version.title, version.description, version.cover_file_id,
    version.cover_url, version.sequential,
    version.default_internal_deadline_days, version.created_by_id,
    version.created_at, version.published_by_id, version.published_at,
    version.content_hash
FROM course_version_quizzes AS quiz
JOIN course_versions AS version ON version.id = quiz.course_version_id
WHERE quiz.company_id = $1
  AND quiz.id = $2
`

type GetCourseVersionByQuizParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	QuizID    uuid.UUID `json:"quiz_id"`
}

func (q *Queries) GetCourseVersionByQuiz(ctx context.Context, arg GetCourseVersionByQuizParams) (CourseVersion, error) {
	row := q.db.QueryRow(ctx, getCourseVersionByQuiz, arg.CompanyID, arg.QuizID)
	var i CourseVersion
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.Number,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CoverFileID,
		&i.CoverUrl,
		&i.Sequential,
		&i.DefaultInternalDeadlineDays,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.PublishedByID,
		&i.PublishedAt,
		&i.ContentHash,
	)
	return i, err
}

const getCourseVersionBySection = `-- name: GetCourseVersionBySection :one
SELECT version.id, version.company_id, version.course_id, version.number,
    version.status, version.title, version.description, version.cover_file_id,
    version.cover_url, version.sequential,
    version.default_internal_deadline_days, version.created_by_id,
    version.created_at, version.published_by_id, version.published_at,
    version.content_hash
FROM course_version_sections AS section
JOIN course_versions AS version ON version.id = section.course_version_id
WHERE section.company_id = $1
  AND section.id = $2
`

type GetCourseVersionBySectionParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	SectionID uuid.UUID `json:"section_id"`
}

func (q *Queries) GetCourseVersionBySection(ctx context.Context, arg GetCourseVersionBySectionParams) (CourseVersion, error) {
	row := q.db.QueryRow(ctx, getCourseVersionBySection, arg.CompanyID, arg.SectionID)
	var i CourseVersion
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.Number,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CoverFileID,
		&i.CoverUrl,
		&i.Sequential,
		&i.DefaultInternalDeadlineDays,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.PublishedByID,
		&i.PublishedAt,
		&i.ContentHash,
	)
	return i, err
}

const getCourseVersionForUpdate = `-- name: GetCourseVersionForUpdate :one
SELECT id, company_id, course_id, number, status, title, description,
    cover_file_id, cover_url, sequential, default_internal_deadline_days,
    created_by_id, created_at, published_by_id, published_at, content_hash
FROM course_versions
WHERE company_id = $1
  AND id = $2
FOR UPDATE
`

type GetCourseVersionForUpdateParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetCourseVersionForUpdate(ctx context.Context, arg GetCourseVersionForUpdateParams) (CourseVersion, error) {
	row := q.db.QueryRow(ctx, getCourseVersionForUpdate, arg.CompanyID, arg.ID)
	var i CourseVersion
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.Number,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CoverFileID,
		&i.CoverUrl,
		&i.Sequential,
		&i.DefaultInternalDeadlineDays,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.PublishedByID,
		&i.PublishedAt,
		&i.ContentHash,
	)
	return i, err
}

const getCourseVersionLesson = `-- name: GetCourseVersionLesson :one
SELECT id, company_id, course_version_id, section_version_id, stable_key,
    title, "order", content, source_type, source_article_id,
    source_article_version, source_template_id, source_template_version_id,
    estimated_minutes, quiz_version_id, kb_snapshot_id, file_ids
FROM course_version_lessons
WHERE company_id = $1
  AND id = $2
`

type GetCourseVersionLessonParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetCourseVersionLesson(ctx context.Context, arg GetCourseVersionLessonParams) (CourseVersionLesson, error) {
	row := q.db.QueryRow(ctx, getCourseVersionLesson, arg.CompanyID, arg.ID)
	var i CourseVersionLesson
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseVersionID,
		&i.SectionVersionID,
		&i.StableKey,
		&i.Title,
		&i.Order,
		&i.Content,
		&i.SourceType,
		&i.SourceArticleID,
		&i.SourceArticleVersion,
		&i.SourceTemplateID,
		&i.SourceTemplateVersionID,
		&i.EstimatedMinutes,
		&i.QuizVersionID,
		&i.KbSnapshotID,
		&i.FileIds,
	)
	return i, err
}

const getCourseVersionLessons = `-- name: GetCourseVersionLessons :many
SELECT id, company_id, course_version_id, section_version_id, stable_key,
    title, "order", content, source_type, source_article_id,
    source_article_version, source_template_id, source_template_version_id,
    estimated_minutes, quiz_version_id, kb_snapshot_id, file_ids
FROM course_version_lessons
WHERE company_id = $1
  AND course_version_id = $2
ORDER BY section_version_id, "order", id
`

type GetCourseVersionLessonsParams struct {
	CompanyID       uuid.UUID `json:"company_id"`
	CourseVersionID uuid.UUID `json:"course_version_id"`
}

func (q *Queries) GetCourseVersionLessons(ctx context.Context, arg GetCourseVersionLessonsParams) ([]CourseVersionLesson, error) {
	rows, err := q.db.Query(ctx, getCourseVersionLessons, arg.CompanyID, arg.CourseVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseVersionLesson{}
	for rows.Next() {
		var i CourseVersionLesson
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CourseVersionID,
			&i.SectionVersionID,
			&i.StableKey,
			&i.Title,
			&i.Order,
			&i.Content,
			&i.SourceType,
			&i.SourceArticleID,
			&i.SourceArticleVersion,
			&i.SourceTemplateID,
			&i.SourceTemplateVersionID,
			&i.EstimatedMinutes,
			&i.QuizVersionID,
			&i.KbSnapshotID,
			&i.FileIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseVersionPublishIdempotency = `-- name: GetCourseVersionPublishIdempotency :one
SELECT id, company_id, course_id, idempotency_key, version_id, created_at
FROM course_version_publish_idempotency
WHERE company_id = $1
  AND course_id = $2
  AND idempotency_key = $3
`

type GetCourseVersionPublishIdempotencyParams struct {
	CompanyID      uuid.UUID `json:"company_id"`
	CourseID       uuid.UUID `json:"course_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) GetCourseVersionPublishIdempotency(ctx context.Context, arg GetCourseVersionPublishIdempotencyParams) (CourseVersionPublishIdempotency, error) {
	row := q.db.QueryRow(ctx, getCourseVersionPublishIdempotency, arg.CompanyID, arg.CourseID, arg.IdempotencyKey)
	var i CourseVersionPublishIdempotency
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.IdempotencyKey,
		&i.VersionID,
		&i.CreatedAt,
	)
	return i, err
}

const getCourseVersionPublishIdempotencyForUpdate = `-- name: GetCourseVersionPublishIdempotencyForUpdate :one
SELECT id, company_id, course_id, idempotency_key, version_id, created_at
FROM course_version_publish_idempotency
WHERE company_id = $1
  AND course_id = $2
  AND idempotency_key = $3
FOR UPDATE
`

type GetCourseVersionPublishIdempotencyForUpdateParams struct {
	CompanyID      uuid.UUID `json:"company_id"`
	CourseID       uuid.UUID `json:"course_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) GetCourseVersionPublishIdempotencyForUpdate(ctx context.Context, arg GetCourseVersionPublishIdempotencyForUpdateParams) (CourseVersionPublishIdempotency, error) {
	row := q.db.QueryRow(ctx, getCourseVersionPublishIdempotencyForUpdate, arg.CompanyID, arg.CourseID, arg.IdempotencyKey)
	var i CourseVersionPublishIdempotency
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.IdempotencyKey,
		&i.VersionID,
		&i.CreatedAt,
	)
	return i, err
}

const getCourseVersionQuiz = `-- name: GetCourseVersionQuiz :one
SELECT id, company_id, course_version_id, lesson_version_id, questions,
    passing_score, max_attempts
FROM course_version_quizzes
WHERE company_id = $1
  AND id = $2
`

type GetCourseVersionQuizParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetCourseVersionQuiz(ctx context.Context, arg GetCourseVersionQuizParams) (CourseVersionQuiz, error) {
	row := q.db.QueryRow(ctx, getCourseVersionQuiz, arg.CompanyID, arg.ID)
	var i CourseVersionQuiz
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseVersionID,
		&i.LessonVersionID,
		&i.Questions,
		&i.PassingScore,
		&i.MaxAttempts,
	)
	return i, err
}

const getCourseVersionQuizzes = `-- name: GetCourseVersionQuizzes :many
SELECT id, company_id, course_version_id, lesson_version_id, questions,
    passing_score, max_attempts
FROM course_version_quizzes
WHERE company_id = $1
  AND course_version_id = $2
ORDER BY id
`

type GetCourseVersionQuizzesParams struct {
	CompanyID       uuid.UUID `json:"company_id"`
	CourseVersionID uuid.UUID `json:"course_version_id"`
}

func (q *Queries) GetCourseVersionQuizzes(ctx context.Context, arg GetCourseVersionQuizzesParams) ([]CourseVersionQuiz, error) {
	rows, err := q.db.Query(ctx, getCourseVersionQuizzes, arg.CompanyID, arg.CourseVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseVersionQuiz{}
	for rows.Next() {
		var i CourseVersionQuiz
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CourseVersionID,
			&i.LessonVersionID,
			&i.Questions,
			&i.PassingScore,
			&i.MaxAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseVersionSection = `-- name: GetCourseVersionSection :one
SELECT id, company_id, course_version_id, stable_key, title, "order"
FROM course_version_sections
WHERE company_id = $1
  AND id = $2
`

type GetCourseVersionSectionParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetCourseVersionSection(ctx context.Context, arg GetCourseVersionSectionParams) (CourseVersionSection, error) {
	row := q.db.QueryRow(ctx, getCourseVersionSection, arg.CompanyID, arg.ID)
	var i CourseVersionSection
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseVersionID,
		&i.StableKey,
		&i.Title,
		&i.Order,
	)
	return i, err
}

const getCourseVersionSections = `-- name: GetCourseVersionSections :many
SELECT id, company_id, course_version_id, stable_key, title, "order"
FROM course_version_sections
WHERE company_id = $1
  AND course_version_id = $2
ORDER BY "order", id
`

type GetCourseVersionSectionsParams struct {
	CompanyID       uuid.UUID `json:"company_id"`
	CourseVersionID uuid.UUID `json:"course_version_id"`
}

func (q *Queries) GetCourseVersionSections(ctx context.Context, arg GetCourseVersionSectionsParams) ([]CourseVersionSection, error) {
	rows, err := q.db.Query(ctx, getCourseVersionSections, arg.CompanyID, arg.CourseVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseVersionSection{}
	for rows.Next() {
		var i CourseVersionSection
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CourseVersionID,
			&i.StableKey,
			&i.Title,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseVersions = `-- name: GetCourseVersions :many
SELECT id, company_id, course_id, number, status, title, description,
    cover_file_id, cover_url, sequential, default_internal_deadline_days,
    created_by_id, created_at, published_by_id, published_at, content_hash
FROM course_versions
WHERE company_id = $1
  AND course_id = $2
ORDER BY number DESC, id
`

type GetCourseVersionsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	CourseID  uuid.UUID `json:"course_id"`
}

func (q *Queries) GetCourseVersions(ctx context.Context, arg GetCourseVersionsParams) ([]CourseVersion, error) {
	rows, err := q.db.Query(ctx, getCourseVersions, arg.CompanyID, arg.CourseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseVersion{}
	for rows.Next() {
		var i CourseVersion
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CourseID,
			&i.Number,
			&i.Status,
			&i.Title,
			&i.Description,
			&i.CoverFileID,
			&i.CoverUrl,
			&i.Sequential,
			&i.DefaultInternalDeadlineDays,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.PublishedByID,
			&i.PublishedAt,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentDraftCourseVersion = `-- name: GetCurrentDraftCourseVersion :one
SELECT version.id, version.company_id, version.course_id, version.number,
    version.status, version.title, version.description, version.cover_file_id,
    version.cover_url, version.sequential,
    version.default_internal_deadline_days, version.created_by_id,
    version.created_at, version.published_by_id, version.published_at,
    version.content_hash
FROM courses AS course
JOIN course_versions AS version ON version.id = course.current_draft_version_id
WHERE course.company_id = $1
  AND course.id = $2
`

type GetCurrentDraftCourseVersionParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	CourseID  uuid.UUID `json:"course_id"`
}

func (q *Queries) GetCurrentDraftCourseVersion(ctx context.Context, arg GetCurrentDraftCourseVersionParams) (CourseVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentDraftCourseVersion, arg.CompanyID, arg.CourseID)
	var i CourseVersion
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.Number,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CoverFileID,
		&i.CoverUrl,
		&i.Sequential,
		&i.DefaultInternalDeadlineDays,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.PublishedByID,
		&i.PublishedAt,
		&i.ContentHash,
	)
	return i, err
}

const getLatestPublishedCourseVersion = `-- name: GetLatestPublishedCourseVersion :one
SELECT version.id, version.company_id, version.course_id, version.number,
    version.status, version.title, version.description, version.cover_file_id,
    version.cover_url, version.sequential,
    version.default_internal_deadline_days, version.created_by_id,
    version.created_at, version.published_by_id, version.published_at,
    version.content_hash
FROM courses AS course
JOIN course_versions AS version ON version.id = course.latest_published_version_id
WHERE course.company_id = $1
  AND course.id = $2
`

type GetLatestPublishedCourseVersionParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	CourseID  uuid.UUID `json:"course_id"`
}

func (q *Queries) GetLatestPublishedCourseVersion(ctx context.Context, arg GetLatestPublishedCourseVersionParams) (CourseVersion, error) {
	row := q.db.QueryRow(ctx, getLatestPublishedCourseVersion, arg.CompanyID, arg.CourseID)
	var i CourseVersion
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.Number,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CoverFileID,
		&i.CoverUrl,
		&i.Sequential,
		&i.DefaultInternalDeadlineDays,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.PublishedByID,
		&i.PublishedAt,
		&i.ContentHash,
	)
	return i, err
}

const getNextCourseVersionNumber = `-- name: GetNextCourseVersionNumber :one
SELECT COALESCE(max(number), 0)::integer + 1
FROM course_versions
WHERE company_id = $1
  AND course_id = $2
`

type GetNextCourseVersionNumberParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	CourseID  uuid.UUID `json:"course_id"`
}

func (q *Queries) GetNextCourseVersionNumber(ctx context.Context, arg GetNextCourseVersionNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, getNextCourseVersionNumber, arg.CompanyID, arg.CourseID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const lockCourseAndCurrentDraftVersion = `-- name: LockCourseAndCurrentDraftVersion :one
SELECT version.id, version.company_id, version.course_id, version.number,
    version.status, version.title, version.description, version.cover_file_id,
    version.cover_url, version.sequential,
    version.default_internal_deadline_days, version.created_by_id,
    version.created_at, version.published_by_id, version.published_at,
    version.content_hash
FROM courses AS course
JOIN course_versions AS version ON version.id = course.current_draft_version_id
WHERE course.company_id = $1
  AND course.id = $2
FOR UPDATE OF course, version
`

type LockCourseAndCurrentDraftVersionParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	CourseID  uuid.UUID `json:"course_id"`
}

func (q *Queries) LockCourseAndCurrentDraftVersion(ctx context.Context, arg LockCourseAndCurrentDraftVersionParams) (CourseVersion, error) {
	row := q.db.QueryRow(ctx, lockCourseAndCurrentDraftVersion, arg.CompanyID, arg.CourseID)
	var i CourseVersion
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.Number,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CoverFileID,
		&i.CoverUrl,
		&i.Sequential,
		&i.DefaultInternalDeadlineDays,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.PublishedByID,
		&i.PublishedAt,
		&i.ContentHash,
	)
	return i, err
}

const moveCourseVersionLesson = `-- name: MoveCourseVersionLesson :one
UPDATE course_version_lessons AS lesson
SET section_version_id = target_section.id,
    "order" = $1
FROM course_versions AS version, course_version_sections AS target_section
WHERE lesson.company_id = $2
  AND lesson.id = $3
  AND version.id = lesson.course_version_id
  AND version.status = 'draft'
  AND target_section.company_id = lesson.company_id
  AND target_section.course_version_id = lesson.course_version_id
  AND target_section.id = $4
RETURNING lesson.id, lesson.company_id, lesson.course_version_id,
    lesson.section_version_id, lesson.stable_key, lesson.title, lesson."order",
    lesson.content, lesson.source_type, lesson.source_article_id,
    lesson.source_article_version, lesson.source_template_id,
    lesson.source_template_version_id, lesson.estimated_minutes, lesson.file_ids,
    lesson.quiz_version_id, lesson.kb_snapshot_id
`

type MoveCourseVersionLessonParams struct {
	OrderValue       int32     `json:"order_value"`
	CompanyID        uuid.UUID `json:"company_id"`
	ID               uuid.UUID `json:"id"`
	SectionVersionID uuid.UUID `json:"section_version_id"`
}

type MoveCourseVersionLessonRow struct {
	ID                      uuid.UUID     `json:"id"`
	CompanyID               uuid.UUID     `json:"company_id"`
	CourseVersionID         uuid.UUID     `json:"course_version_id"`
	SectionVersionID        uuid.UUID     `json:"section_version_id"`
	StableKey               uuid.UUID     `json:"stable_key"`
	Title                   string        `json:"title"`
	Order                   int32         `json:"order"`
	Content                 []byte        `json:"content"`
	SourceType              string        `json:"source_type"`
	SourceArticleID         uuid.NullUUID `json:"source_article_id"`
	SourceArticleVersion    pgtype.Int4   `json:"source_article_version"`
	SourceTemplateID        uuid.NullUUID `json:"source_template_id"`
	SourceTemplateVersionID uuid.NullUUID `json:"source_template_version_id"`
	EstimatedMinutes        pgtype.Int4   `json:"estimated_minutes"`
	FileIds                 []uuid.UUID   `json:"file_ids"`
	QuizVersionID           uuid.NullUUID `json:"quiz_version_id"`
	KbSnapshotID            uuid.NullUUID `json:"kb_snapshot_id"`
}

func (q *Queries) MoveCourseVersionLesson(ctx context.Context, arg MoveCourseVersionLessonParams) (MoveCourseVersionLessonRow, error) {
	row := q.db.QueryRow(ctx, moveCourseVersionLesson,
		arg.OrderValue,
		arg.CompanyID,
		arg.ID,
		arg.SectionVersionID,
	)
	var i MoveCourseVersionLessonRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseVersionID,
		&i.SectionVersionID,
		&i.StableKey,
		&i.Title,
		&i.Order,
		&i.Content,
		&i.SourceType,
		&i.SourceArticleID,
		&i.SourceArticleVersion,
		&i.SourceTemplateID,
		&i.SourceTemplateVersionID,
		&i.EstimatedMinutes,
		&i.FileIds,
		&i.QuizVersionID,
		&i.KbSnapshotID,
	)
	return i, err
}

const publishCourseVersion = `-- name: PublishCourseVersion :one
UPDATE course_versions
SET status = 'published',
    published_by_id = $1,
    published_at = $2,
    content_hash = $3
WHERE company_id = $4
  AND course_id = $5
  AND id = $6
  AND status = 'draft'
RETURNING id, company_id, course_id, number, status, title, description,
    cover_file_id, cover_url, sequential, default_internal_deadline_days,
    created_by_id, created_at, published_by_id, published_at, content_hash
`

type PublishCourseVersionParams struct {
	PublishedByID uuid.NullUUID      `json:"published_by_id"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	ContentHash   pgtype.Text        `json:"content_hash"`
	CompanyID     uuid.UUID          `json:"company_id"`
	CourseID      uuid.UUID          `json:"course_id"`
	ID            uuid.UUID          `json:"id"`
}

func (q *Queries) PublishCourseVersion(ctx context.Context, arg PublishCourseVersionParams) (CourseVersion, error) {
	row := q.db.QueryRow(ctx, publishCourseVersion,
		arg.PublishedByID,
		arg.PublishedAt,
		arg.ContentHash,
		arg.CompanyID,
		arg.CourseID,
		arg.ID,
	)
	var i CourseVersion
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.Number,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CoverFileID,
		&i.CoverUrl,
		&i.Sequential,
		&i.DefaultInternalDeadlineDays,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.PublishedByID,
		&i.PublishedAt,
		&i.ContentHash,
	)
	return i, err
}

const retireCourseVersion = `-- name: RetireCourseVersion :one
UPDATE course_versions
SET status = 'retired'
WHERE company_id = $1
  AND id = $2
  AND status = 'published'
RETURNING id, company_id, course_id, number, status, title, description,
    cover_file_id, cover_url, sequential, default_internal_deadline_days,
    created_by_id, created_at, published_by_id, published_at, content_hash
`

type RetireCourseVersionParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) RetireCourseVersion(ctx context.Context, arg RetireCourseVersionParams) (CourseVersion, error) {
	row := q.db.QueryRow(ctx, retireCourseVersion, arg.CompanyID, arg.ID)
	var i CourseVersion
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.Number,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CoverFileID,
		&i.CoverUrl,
		&i.Sequential,
		&i.DefaultInternalDeadlineDays,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.PublishedByID,
		&i.PublishedAt,
		&i.ContentHash,
	)
	return i, err
}

const setCourseCurrentDraftVersion = `-- name: SetCourseCurrentDraftVersion :execrows
UPDATE courses AS course
SET current_draft_version_id = version.id,
    updated_at = $1
FROM course_versions AS version
WHERE course.company_id = $2
  AND course.id = $3
  AND version.company_id = course.company_id
  AND version.course_id = course.id
  AND version.id = $4
  AND version.status = 'draft'
`

type SetCourseCurrentDraftVersionParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	CompanyID uuid.UUID `json:"company_id"`
	CourseID  uuid.UUID `json:"course_id"`
	VersionID uuid.UUID `json:"version_id"`
}

func (q *Queries) SetCourseCurrentDraftVersion(ctx context.Context, arg SetCourseCurrentDraftVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCourseCurrentDraftVersion,
		arg.UpdatedAt,
		arg.CompanyID,
		arg.CourseID,
		arg.VersionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCoursePublishedVersionPointers = `-- name: SetCoursePublishedVersionPointers :execrows
UPDATE courses AS course
SET current_draft_version_id = NULL,
    latest_published_version_id = version.id,
    status = 'published',
    title = version.title,
    description = version.description,
    cover_url = version.cover_url,
    sequential = version.sequential,
    deadline_days = version.default_internal_deadline_days,
    updated_at = $1
FROM course_versions AS version
WHERE course.company_id = $2
  AND course.id = $3
  AND course.current_draft_version_id = version.id
  AND version.company_id = course.company_id
  AND version.course_id = course.id
  AND version.id = $4
  AND version.status = 'published'
`

type SetCoursePublishedVersionPointersParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	CompanyID uuid.UUID `json:"company_id"`
	CourseID  uuid.UUID `json:"course_id"`
	VersionID uuid.UUID `json:"version_id"`
}

func (q *Queries) SetCoursePublishedVersionPointers(ctx context.Context, arg SetCoursePublishedVersionPointersParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCoursePublishedVersionPointers,
		arg.UpdatedAt,
		arg.CompanyID,
		arg.CourseID,
		arg.VersionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCourseVersionLessonOrder = `-- name: SetCourseVersionLessonOrder :execrows
UPDATE course_version_lessons AS lesson
SET "order" = $1
FROM course_versions AS version
WHERE lesson.company_id = $2
  AND lesson.id = $3
  AND version.id = lesson.course_version_id
  AND version.status = 'draft'
`

type SetCourseVersionLessonOrderParams struct {
	OrderValue int32     `json:"order_value"`
	CompanyID  uuid.UUID `json:"company_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) SetCourseVersionLessonOrder(ctx context.Context, arg SetCourseVersionLessonOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCourseVersionLessonOrder, arg.OrderValue, arg.CompanyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCourseVersionLesson = `-- name: UpdateCourseVersionLesson :one
UPDATE course_version_lessons AS lesson
SET title = $1,
    content = $2,
    source_type = $3,
    source_article_id = $4,
    source_article_version = $5,
    source_template_id = $6,
    source_template_version_id = $7,
    estimated_minutes = $8,
    file_ids = COALESCE($9::uuid[], lesson.file_ids),
    kb_snapshot_id = $10
FROM course_versions AS version
WHERE lesson.company_id = $11
  AND lesson.id = $12
  AND version.id = lesson.course_version_id
  AND version.status = 'draft'
RETURNING lesson.id, lesson.company_id, lesson.course_version_id,
    lesson.section_version_id, lesson.stable_key, lesson.title, lesson."order",
    lesson.content, lesson.source_type, lesson.source_article_id,
    lesson.source_article_version, lesson.source_template_id,
    lesson.source_template_version_id, lesson.estimated_minutes,
    lesson.quiz_version_id, lesson.kb_snapshot_id, lesson.file_ids
`

type UpdateCourseVersionLessonParams struct {
	Title                   string        `json:"title"`
	Content                 []byte        `json:"content"`
	SourceType              string        `json:"source_type"`
	SourceArticleID         uuid.NullUUID `json:"source_article_id"`
	SourceArticleVersion    pgtype.Int4   `json:"source_article_version"`
	SourceTemplateID        uuid.NullUUID `json:"source_template_id"`
	SourceTemplateVersionID uuid.NullUUID `json:"source_template_version_id"`
	EstimatedMinutes        pgtype.Int4   `json:"estimated_minutes"`
	FileIds                 []uuid.UUID   `json:"file_ids"`
	KbSnapshotID            uuid.NullUUID `json:"kb_snapshot_id"`
	CompanyID               uuid.UUID     `json:"company_id"`
	ID                      uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateCourseVersionLesson(ctx context.Context, arg UpdateCourseVersionLessonParams) (CourseVersionLesson, error) {
	row := q.db.QueryRow(ctx, updateCourseVersionLesson,
		arg.Title,
		arg.Content,
		arg.SourceType,
		arg.SourceArticleID,
		arg.SourceArticleVersion,
		arg.SourceTemplateID,
		arg.SourceTemplateVersionID,
		arg.EstimatedMinutes,
		arg.FileIds,
		arg.KbSnapshotID,
		arg.CompanyID,
		arg.ID,
	)
	var i CourseVersionLesson
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseVersionID,
		&i.SectionVersionID,
		&i.StableKey,
		&i.Title,
		&i.Order,
		&i.Content,
		&i.SourceType,
		&i.SourceArticleID,
		&i.SourceArticleVersion,
		&i.SourceTemplateID,
		&i.SourceTemplateVersionID,
		&i.EstimatedMinutes,
		&i.QuizVersionID,
		&i.KbSnapshotID,
		&i.FileIds,
	)
	return i, err
}

const updateCourseVersionQuiz = `-- name: UpdateCourseVersionQuiz :one
UPDATE course_version_quizzes AS quiz
SET questions = $1,
    passing_score = $2,
    max_attempts = $3
FROM course_versions AS version
WHERE quiz.company_id = $4
  AND quiz.id = $5
  AND version.id = quiz.course_version_id
  AND version.status = 'draft'
RETURNING quiz.id, quiz.company_id, quiz.course_version_id,
    quiz.lesson_version_id, quiz.questions, quiz.passing_score,
    quiz.max_attempts
`

type UpdateCourseVersionQuizParams struct {
	Questions    []byte      `json:"questions"`
	PassingScore int32       `json:"passing_score"`
	MaxAttempts  pgtype.Int4 `json:"max_attempts"`
	CompanyID    uuid.UUID   `json:"company_id"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateCourseVersionQuiz(ctx context.Context, arg UpdateCourseVersionQuizParams) (CourseVersionQuiz, error) {
	row := q.db.QueryRow(ctx, updateCourseVersionQuiz,
		arg.Questions,
		arg.PassingScore,
		arg.MaxAttempts,
		arg.CompanyID,
		arg.ID,
	)
	var i CourseVersionQuiz
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseVersionID,
		&i.LessonVersionID,
		&i.Questions,
		&i.PassingScore,
		&i.MaxAttempts,
	)
	return i, err
}

const updateCourseVersionSection = `-- name: UpdateCourseVersionSection :one
UPDATE course_version_sections AS section
SET title = COALESCE($1::text, section.title),
    "order" = COALESCE($2::integer, section."order")
FROM course_versions AS version
WHERE section.company_id = $3
  AND section.id = $4
  AND version.id = section.course_version_id
  AND version.status = 'draft'
RETURNING section.id, section.company_id, section.course_version_id,
    section.stable_key, section.title, section."order"
`

type UpdateCourseVersionSectionParams struct {
	Title      pgtype.Text `json:"title"`
	OrderValue pgtype.Int4 `json:"order_value"`
	CompanyID  uuid.UUID   `json:"company_id"`
	ID         uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateCourseVersionSection(ctx context.Context, arg UpdateCourseVersionSectionParams) (CourseVersionSection, error) {
	row := q.db.QueryRow(ctx, updateCourseVersionSection,
		arg.Title,
		arg.OrderValue,
		arg.CompanyID,
		arg.ID,
	)
	var i CourseVersionSection
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseVersionID,
		&i.StableKey,
		&i.Title,
		&i.Order,
	)
	return i, err
}

const updateDraftCourseVersion = `-- name: UpdateDraftCourseVersion :one
UPDATE course_versions
SET title = $1,
    description = $2,
    cover_file_id = $3,
    cover_url = $4,
    sequential = $5,
    default_internal_deadline_days = $6,
    content_hash = NULL
WHERE company_id = $7
  AND id = $8
  AND status = 'draft'
RETURNING id, company_id, course_id, number, status, title, description,
    cover_file_id, cover_url, sequential, default_internal_deadline_days,
    created_by_id, created_at, published_by_id, published_at, content_hash
`

type UpdateDraftCourseVersionParams struct {
	Title                       string        `json:"title"`
	Description                 pgtype.Text   `json:"description"`
	CoverFileID                 uuid.NullUUID `json:"cover_file_id"`
	CoverUrl                    pgtype.Text   `json:"cover_url"`
	Sequential                  bool          `json:"sequential"`
	DefaultInternalDeadlineDays pgtype.Int4   `json:"default_internal_deadline_days"`
	CompanyID                   uuid.UUID     `json:"company_id"`
	ID                          uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateDraftCourseVersion(ctx context.Context, arg UpdateDraftCourseVersionParams) (CourseVersion, error) {
	row := q.db.QueryRow(ctx, updateDraftCourseVersion,
		arg.Title,
		arg.Description,
		arg.CoverFileID,
		arg.CoverUrl,
		arg.Sequential,
		arg.DefaultInternalDeadlineDays,
		arg.CompanyID,
		arg.ID,
	)
	var i CourseVersion
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.Number,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CoverFileID,
		&i.CoverUrl,
		&i.Sequential,
		&i.DefaultInternalDeadlineDays,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.PublishedByID,
		&i.PublishedAt,
		&i.ContentHash,
	)
	return i, err
}
