// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollment_mutation_idempotency.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeEnrollmentMutationIdempotency = `-- name: CompleteEnrollmentMutationIdempotency :one
UPDATE enrollment_mutation_idempotency
SET result_id = $1,
    completed_at = $2
WHERE company_id = $3
  AND id = $4
  AND completed_at IS NULL
RETURNING id, company_id, enrollment_id, actor_user_id, operation,
    idempotency_key, request_hash, result_id, completed_at, created_at
`

type CompleteEnrollmentMutationIdempotencyParams struct {
	ResultID    uuid.NullUUID      `json:"result_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CompanyID   uuid.UUID          `json:"company_id"`
	ID          uuid.UUID          `json:"id"`
}

func (q *Queries) CompleteEnrollmentMutationIdempotency(ctx context.Context, arg CompleteEnrollmentMutationIdempotencyParams) (EnrollmentMutationIdempotency, error) {
	row := q.db.QueryRow(ctx, completeEnrollmentMutationIdempotency,
		arg.ResultID,
		arg.CompletedAt,
		arg.CompanyID,
		arg.ID,
	)
	var i EnrollmentMutationIdempotency
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EnrollmentID,
		&i.ActorUserID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResultID,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const reserveEnrollmentMutationIdempotency = `-- name: ReserveEnrollmentMutationIdempotency :one
INSERT INTO enrollment_mutation_idempotency (
    id, company_id, enrollment_id, actor_user_id, operation,
    idempotency_key, request_hash, created_at
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8
)
ON CONFLICT (company_id, actor_user_id, operation, idempotency_key)
DO UPDATE SET id = enrollment_mutation_idempotency.id
RETURNING id, company_id, enrollment_id, actor_user_id, operation,
    idempotency_key, request_hash, result_id, completed_at, created_at
`

type ReserveEnrollmentMutationIdempotencyParams struct {
	ID             uuid.UUID `json:"id"`
	CompanyID      uuid.UUID `json:"company_id"`
	EnrollmentID   uuid.UUID `json:"enrollment_id"`
	ActorUserID    uuid.UUID `json:"actor_user_id"`
	Operation      string    `json:"operation"`
	IdempotencyKey string    `json:"idempotency_key"`
	RequestHash    string    `json:"request_hash"`
	CreatedAt      time.Time `json:"created_at"`
}

// The conflict branch takes a row lock until the surrounding transaction ends.
// This serializes concurrent retries with the same key.
func (q *Queries) ReserveEnrollmentMutationIdempotency(ctx context.Context, arg ReserveEnrollmentMutationIdempotencyParams) (EnrollmentMutationIdempotency, error) {
	row := q.db.QueryRow(ctx, reserveEnrollmentMutationIdempotency,
		arg.ID,
		arg.CompanyID,
		arg.EnrollmentID,
		arg.ActorUserID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.CreatedAt,
	)
	var i EnrollmentMutationIdempotency
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EnrollmentID,
		&i.ActorUserID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResultID,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
