// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: external_reports.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getExternalEnrollmentForMutationForUpdate = `-- name: GetExternalEnrollmentForMutationForUpdate :one
SELECT enrollment.id, enrollment.company_id, enrollment.course_id,
    enrollment.course_version_id, enrollment.external_learner_id,
    enrollment.source_type, enrollment.source_id, enrollment.attempt_number,
    enrollment.progress_status, enrollment.access_status,
    enrollment.current_lesson_version_id, enrollment.activated_at,
    enrollment.access_until, enrollment.started_at, enrollment.completed_at,
    enrollment.last_activity_at, enrollment.created_at, enrollment.updated_at
FROM course_enrollments AS enrollment
JOIN external_sessions AS session
  ON session.company_id = enrollment.company_id
 AND session.external_learner_id = enrollment.external_learner_id
JOIN courses AS course
  ON course.company_id = enrollment.company_id
 AND course.id = enrollment.course_id
WHERE enrollment.company_id = $1
  AND enrollment.id = $2
  AND enrollment.learner_type = 'external'
  AND session.id = $3
  AND session.revoked_at IS NULL
  AND session.expires_at > $4
  AND enrollment.access_status = 'active'
  AND enrollment.access_until > $4
  AND course.lifecycle_status = 'active'
  AND course.distribution_status <> 'blocked'
FOR UPDATE OF enrollment
`

type GetExternalEnrollmentForMutationForUpdateParams struct {
	CompanyID    uuid.UUID `json:"company_id"`
	EnrollmentID uuid.UUID `json:"enrollment_id"`
	SessionID    uuid.UUID `json:"session_id"`
	Now          time.Time `json:"now"`
}

type GetExternalEnrollmentForMutationForUpdateRow struct {
	ID                     uuid.UUID          `json:"id"`
	CompanyID              uuid.UUID          `json:"company_id"`
	CourseID               uuid.UUID          `json:"course_id"`
	CourseVersionID        uuid.UUID          `json:"course_version_id"`
	ExternalLearnerID      uuid.NullUUID      `json:"external_learner_id"`
	SourceType             string             `json:"source_type"`
	SourceID               uuid.NullUUID      `json:"source_id"`
	AttemptNumber          int32              `json:"attempt_number"`
	ProgressStatus         string             `json:"progress_status"`
	AccessStatus           string             `json:"access_status"`
	CurrentLessonVersionID uuid.NullUUID      `json:"current_lesson_version_id"`
	ActivatedAt            pgtype.Timestamptz `json:"activated_at"`
	AccessUntil            pgtype.Timestamptz `json:"access_until"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	LastActivityAt         pgtype.Timestamptz `json:"last_activity_at"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
}

func (q *Queries) GetExternalEnrollmentForMutationForUpdate(ctx context.Context, arg GetExternalEnrollmentForMutationForUpdateParams) (GetExternalEnrollmentForMutationForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getExternalEnrollmentForMutationForUpdate,
		arg.CompanyID,
		arg.EnrollmentID,
		arg.SessionID,
		arg.Now,
	)
	var i GetExternalEnrollmentForMutationForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.CourseVersionID,
		&i.ExternalLearnerID,
		&i.SourceType,
		&i.SourceID,
		&i.AttemptNumber,
		&i.ProgressStatus,
		&i.AccessStatus,
		&i.CurrentLessonVersionID,
		&i.ActivatedAt,
		&i.AccessUntil,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExternalEnrollmentForSession = `-- name: GetExternalEnrollmentForSession :one
SELECT enrollment.id, enrollment.company_id, enrollment.course_id,
    enrollment.course_version_id, enrollment.external_learner_id,
    enrollment.source_type, enrollment.source_id, enrollment.attempt_number,
    enrollment.progress_status, enrollment.access_status,
    enrollment.current_lesson_version_id, enrollment.activated_at,
    enrollment.access_until, enrollment.started_at, enrollment.completed_at,
    enrollment.last_activity_at, enrollment.frozen_at,
    enrollment.suspended_at, enrollment.created_at, enrollment.updated_at,
    version.number AS course_version_number, version.title AS course_title,
    version.description AS course_description, version.cover_file_id,
    version.sequential
FROM course_enrollments AS enrollment
JOIN external_sessions AS session
  ON session.company_id = enrollment.company_id
 AND session.external_learner_id = enrollment.external_learner_id
JOIN course_versions AS version
  ON version.company_id = enrollment.company_id
 AND version.id = enrollment.course_version_id
WHERE enrollment.company_id = $1
  AND enrollment.id = $2
  AND enrollment.learner_type = 'external'
  AND session.id = $3
  AND session.revoked_at IS NULL
  AND session.expires_at > $4
  AND enrollment.access_status IN ('active', 'expired', 'frozen')
`

type GetExternalEnrollmentForSessionParams struct {
	CompanyID    uuid.UUID `json:"company_id"`
	EnrollmentID uuid.UUID `json:"enrollment_id"`
	SessionID    uuid.UUID `json:"session_id"`
	Now          time.Time `json:"now"`
}

type GetExternalEnrollmentForSessionRow struct {
	ID                     uuid.UUID          `json:"id"`
	CompanyID              uuid.UUID          `json:"company_id"`
	CourseID               uuid.UUID          `json:"course_id"`
	CourseVersionID        uuid.UUID          `json:"course_version_id"`
	ExternalLearnerID      uuid.NullUUID      `json:"external_learner_id"`
	SourceType             string             `json:"source_type"`
	SourceID               uuid.NullUUID      `json:"source_id"`
	AttemptNumber          int32              `json:"attempt_number"`
	ProgressStatus         string             `json:"progress_status"`
	AccessStatus           string             `json:"access_status"`
	CurrentLessonVersionID uuid.NullUUID      `json:"current_lesson_version_id"`
	ActivatedAt            pgtype.Timestamptz `json:"activated_at"`
	AccessUntil            pgtype.Timestamptz `json:"access_until"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	LastActivityAt         pgtype.Timestamptz `json:"last_activity_at"`
	FrozenAt               pgtype.Timestamptz `json:"frozen_at"`
	SuspendedAt            pgtype.Timestamptz `json:"suspended_at"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
	CourseVersionNumber    int32              `json:"course_version_number"`
	CourseTitle            string             `json:"course_title"`
	CourseDescription      pgtype.Text        `json:"course_description"`
	CoverFileID            uuid.NullUUID      `json:"cover_file_id"`
	Sequential             bool               `json:"sequential"`
}

func (q *Queries) GetExternalEnrollmentForSession(ctx context.Context, arg GetExternalEnrollmentForSessionParams) (GetExternalEnrollmentForSessionRow, error) {
	row := q.db.QueryRow(ctx, getExternalEnrollmentForSession,
		arg.CompanyID,
		arg.EnrollmentID,
		arg.SessionID,
		arg.Now,
	)
	var i GetExternalEnrollmentForSessionRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.CourseVersionID,
		&i.ExternalLearnerID,
		&i.SourceType,
		&i.SourceID,
		&i.AttemptNumber,
		&i.ProgressStatus,
		&i.AccessStatus,
		&i.CurrentLessonVersionID,
		&i.ActivatedAt,
		&i.AccessUntil,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastActivityAt,
		&i.FrozenAt,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CourseVersionNumber,
		&i.CourseTitle,
		&i.CourseDescription,
		&i.CoverFileID,
		&i.Sequential,
	)
	return i, err
}

const getExternalEnrollmentIndividualReport = `-- name: GetExternalEnrollmentIndividualReport :one
SELECT enrollment.id AS enrollment_id, enrollment.company_id,
    enrollment.course_id, enrollment.course_version_id,
    version.number AS course_version_number, version.title AS course_title,
    learner.id AS external_learner_id, learner.email,
    learner.first_name, learner.last_name, learner.email_verified_at,
    enrollment.source_type, enrollment.source_id,
    enrollment.attempt_number, enrollment.progress_status,
    enrollment.access_status, enrollment.current_lesson_version_id,
    access.id AS personal_access_id, access.status AS personal_access_status,
    access.issued_by_id, access.issued_at, access.deadline_days,
    access.activated_at AS access_activated_at,
    count(lesson.id)::integer AS lesson_count,
    count(lesson.id) FILTER (
        WHERE progress.status = 'completed'
    )::integer AS completed_lesson_count,
    CASE WHEN count(lesson.id) = 0 THEN 0
         ELSE (count(lesson.id) FILTER (WHERE progress.status = 'completed')
               * 100 / count(lesson.id))::integer END AS progress_percent,
    COALESCE(sum(progress.active_seconds), 0)::bigint AS active_seconds,
    attempt_stats.attempt_count, attempt_stats.best_score,
    attempt_stats.pending_review_count,
    session_stats.session_count,
    enrollment.activated_at, enrollment.access_until,
    enrollment.started_at, enrollment.completed_at,
    enrollment.last_activity_at, enrollment.frozen_at,
    enrollment.suspended_at, enrollment.created_at, enrollment.updated_at
FROM course_enrollments AS enrollment
JOIN external_learners AS learner
  ON learner.company_id = enrollment.company_id
 AND learner.id = enrollment.external_learner_id
JOIN courses AS course
  ON course.company_id = enrollment.company_id
 AND course.id = enrollment.course_id
JOIN course_versions AS version
  ON version.company_id = enrollment.company_id
 AND version.id = enrollment.course_version_id
LEFT JOIN external_personal_accesses AS access
  ON access.company_id = enrollment.company_id
 AND access.id = enrollment.source_id
 AND enrollment.source_type IN ('personal_access', 'repeat_training')
LEFT JOIN course_version_lessons AS lesson
  ON lesson.company_id = enrollment.company_id
 AND lesson.course_version_id = enrollment.course_version_id
LEFT JOIN enrollment_lesson_progress AS progress
  ON progress.company_id = enrollment.company_id
 AND progress.enrollment_id = enrollment.id
 AND progress.lesson_version_id = lesson.id
LEFT JOIN LATERAL (
    SELECT count(*)::integer AS attempt_count,
           max(attempt.score)::integer AS best_score,
           count(*) FILTER (
               WHERE attempt.pending_review AND attempt.reviewed_at IS NULL
           )::integer AS pending_review_count
    FROM quiz_attempts AS attempt
    WHERE attempt.company_id = enrollment.company_id
      AND attempt.enrollment_id = enrollment.id
) AS attempt_stats ON true
LEFT JOIN LATERAL (
    SELECT count(*)::integer AS session_count
    FROM external_sessions AS session
    WHERE session.company_id = enrollment.company_id
      AND session.external_learner_id = enrollment.external_learner_id
) AS session_stats ON true
WHERE enrollment.company_id = $1
  AND enrollment.id = $2
  AND enrollment.learner_type = 'external'
  AND ($3::uuid IS NULL
       OR (course.owner_type = 'partner'
           AND course.owner_user_id = $3::uuid))
GROUP BY enrollment.id, version.number, version.title, learner.id,
    access.id, attempt_stats.attempt_count, attempt_stats.best_score,
    attempt_stats.pending_review_count, session_stats.session_count
`

type GetExternalEnrollmentIndividualReportParams struct {
	CompanyID      uuid.UUID     `json:"company_id"`
	EnrollmentID   uuid.UUID     `json:"enrollment_id"`
	PartnerOwnerID uuid.NullUUID `json:"partner_owner_id"`
}

type GetExternalEnrollmentIndividualReportRow struct {
	EnrollmentID           uuid.UUID          `json:"enrollment_id"`
	CompanyID              uuid.UUID          `json:"company_id"`
	CourseID               uuid.UUID          `json:"course_id"`
	CourseVersionID        uuid.UUID          `json:"course_version_id"`
	CourseVersionNumber    int32              `json:"course_version_number"`
	CourseTitle            string             `json:"course_title"`
	ExternalLearnerID      uuid.UUID          `json:"external_learner_id"`
	Email                  string             `json:"email"`
	FirstName              pgtype.Text        `json:"first_name"`
	LastName               pgtype.Text        `json:"last_name"`
	EmailVerifiedAt        pgtype.Timestamptz `json:"email_verified_at"`
	SourceType             string             `json:"source_type"`
	SourceID               uuid.NullUUID      `json:"source_id"`
	AttemptNumber          int32              `json:"attempt_number"`
	ProgressStatus         string             `json:"progress_status"`
	AccessStatus           string             `json:"access_status"`
	CurrentLessonVersionID uuid.NullUUID      `json:"current_lesson_version_id"`
	PersonalAccessID       uuid.NullUUID      `json:"personal_access_id"`
	PersonalAccessStatus   pgtype.Text        `json:"personal_access_status"`
	IssuedByID             uuid.NullUUID      `json:"issued_by_id"`
	IssuedAt               pgtype.Timestamptz `json:"issued_at"`
	DeadlineDays           pgtype.Int2        `json:"deadline_days"`
	AccessActivatedAt      pgtype.Timestamptz `json:"access_activated_at"`
	LessonCount            int32              `json:"lesson_count"`
	CompletedLessonCount   int32              `json:"completed_lesson_count"`
	ProgressPercent        int32              `json:"progress_percent"`
	ActiveSeconds          int64              `json:"active_seconds"`
	AttemptCount           int32              `json:"attempt_count"`
	BestScore              int32              `json:"best_score"`
	PendingReviewCount     int32              `json:"pending_review_count"`
	SessionCount           int32              `json:"session_count"`
	ActivatedAt            pgtype.Timestamptz `json:"activated_at"`
	AccessUntil            pgtype.Timestamptz `json:"access_until"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	LastActivityAt         pgtype.Timestamptz `json:"last_activity_at"`
	FrozenAt               pgtype.Timestamptz `json:"frozen_at"`
	SuspendedAt            pgtype.Timestamptz `json:"suspended_at"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
}

func (q *Queries) GetExternalEnrollmentIndividualReport(ctx context.Context, arg GetExternalEnrollmentIndividualReportParams) (GetExternalEnrollmentIndividualReportRow, error) {
	row := q.db.QueryRow(ctx, getExternalEnrollmentIndividualReport, arg.CompanyID, arg.EnrollmentID, arg.PartnerOwnerID)
	var i GetExternalEnrollmentIndividualReportRow
	err := row.Scan(
		&i.EnrollmentID,
		&i.CompanyID,
		&i.CourseID,
		&i.CourseVersionID,
		&i.CourseVersionNumber,
		&i.CourseTitle,
		&i.ExternalLearnerID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.EmailVerifiedAt,
		&i.SourceType,
		&i.SourceID,
		&i.AttemptNumber,
		&i.ProgressStatus,
		&i.AccessStatus,
		&i.CurrentLessonVersionID,
		&i.PersonalAccessID,
		&i.PersonalAccessStatus,
		&i.IssuedByID,
		&i.IssuedAt,
		&i.DeadlineDays,
		&i.AccessActivatedAt,
		&i.LessonCount,
		&i.CompletedLessonCount,
		&i.ProgressPercent,
		&i.ActiveSeconds,
		&i.AttemptCount,
		&i.BestScore,
		&i.PendingReviewCount,
		&i.SessionCount,
		&i.ActivatedAt,
		&i.AccessUntil,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastActivityAt,
		&i.FrozenAt,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExternalLearnerForReport = `-- name: GetExternalLearnerForReport :one
SELECT learner.id, learner.company_id, learner.email,
    learner.normalized_email, learner.first_name, learner.last_name,
    learner.phone, learner.email_verified_at, learner.created_at,
    learner.updated_at,
    count(DISTINCT enrollment.id)::integer AS enrollment_count,
    count(DISTINCT enrollment.id) FILTER (
        WHERE enrollment.progress_status = 'completed'
    )::integer AS completed_enrollment_count,
    max(enrollment.last_activity_at) AS last_activity_at
FROM external_learners AS learner
JOIN course_enrollments AS enrollment
  ON enrollment.company_id = learner.company_id
 AND enrollment.external_learner_id = learner.id
 AND enrollment.learner_type = 'external'
JOIN courses AS course
  ON course.company_id = enrollment.company_id
 AND course.id = enrollment.course_id
WHERE learner.company_id = $1
  AND learner.id = $2
  AND learner.deleted_at IS NULL
  AND ($3::uuid IS NULL
       OR (course.owner_type = 'partner'
           AND course.owner_user_id = $3::uuid))
GROUP BY learner.id
`

type GetExternalLearnerForReportParams struct {
	CompanyID      uuid.UUID     `json:"company_id"`
	LearnerID      uuid.UUID     `json:"learner_id"`
	PartnerOwnerID uuid.NullUUID `json:"partner_owner_id"`
}

type GetExternalLearnerForReportRow struct {
	ID                       uuid.UUID          `json:"id"`
	CompanyID                uuid.UUID          `json:"company_id"`
	Email                    string             `json:"email"`
	NormalizedEmail          string             `json:"normalized_email"`
	FirstName                pgtype.Text        `json:"first_name"`
	LastName                 pgtype.Text        `json:"last_name"`
	Phone                    pgtype.Text        `json:"phone"`
	EmailVerifiedAt          pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt                time.Time          `json:"created_at"`
	UpdatedAt                time.Time          `json:"updated_at"`
	EnrollmentCount          int32              `json:"enrollment_count"`
	CompletedEnrollmentCount int32              `json:"completed_enrollment_count"`
	LastActivityAt           interface{}        `json:"last_activity_at"`
}

func (q *Queries) GetExternalLearnerForReport(ctx context.Context, arg GetExternalLearnerForReportParams) (GetExternalLearnerForReportRow, error) {
	row := q.db.QueryRow(ctx, getExternalLearnerForReport, arg.CompanyID, arg.LearnerID, arg.PartnerOwnerID)
	var i GetExternalLearnerForReportRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.NormalizedEmail,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrollmentCount,
		&i.CompletedEnrollmentCount,
		&i.LastActivityAt,
	)
	return i, err
}

const getExternalLessonContentForSession = `-- name: GetExternalLessonContentForSession :one
SELECT lesson.id, lesson.company_id, lesson.course_version_id,
    lesson.section_version_id, lesson.title, lesson."order", lesson.content,
    lesson.source_type, lesson.estimated_minutes, lesson.file_ids,
    lesson.quiz_version_id, progress.status AS lesson_status,
    progress.first_opened_at, progress.completed_at,
    progress.active_seconds, progress.last_position
FROM course_enrollments AS enrollment
JOIN external_sessions AS session
  ON session.company_id = enrollment.company_id
 AND session.external_learner_id = enrollment.external_learner_id
JOIN enrollment_lesson_progress AS progress
  ON progress.company_id = enrollment.company_id
 AND progress.enrollment_id = enrollment.id
JOIN course_version_lessons AS lesson
  ON lesson.company_id = enrollment.company_id
 AND lesson.course_version_id = enrollment.course_version_id
 AND lesson.id = progress.lesson_version_id
WHERE enrollment.company_id = $1
  AND enrollment.id = $2
  AND enrollment.learner_type = 'external'
  AND lesson.id = $3
  AND session.id = $4
  AND session.revoked_at IS NULL
  AND session.expires_at > $5
  AND (
      (enrollment.access_status = 'active'
       AND enrollment.access_until > $5)
      OR
      (enrollment.access_status IN ('expired', 'frozen')
       AND progress.status = 'completed')
  )
`

type GetExternalLessonContentForSessionParams struct {
	CompanyID       uuid.UUID `json:"company_id"`
	EnrollmentID    uuid.UUID `json:"enrollment_id"`
	LessonVersionID uuid.UUID `json:"lesson_version_id"`
	SessionID       uuid.UUID `json:"session_id"`
	Now             time.Time `json:"now"`
}

type GetExternalLessonContentForSessionRow struct {
	ID               uuid.UUID          `json:"id"`
	CompanyID        uuid.UUID          `json:"company_id"`
	CourseVersionID  uuid.UUID          `json:"course_version_id"`
	SectionVersionID uuid.UUID          `json:"section_version_id"`
	Title            string             `json:"title"`
	Order            int32              `json:"order"`
	Content          []byte             `json:"content"`
	SourceType       string             `json:"source_type"`
	EstimatedMinutes pgtype.Int4        `json:"estimated_minutes"`
	FileIds          []uuid.UUID        `json:"file_ids"`
	QuizVersionID    uuid.NullUUID      `json:"quiz_version_id"`
	LessonStatus     string             `json:"lesson_status"`
	FirstOpenedAt    pgtype.Timestamptz `json:"first_opened_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	ActiveSeconds    int64              `json:"active_seconds"`
	LastPosition     pgtype.Text        `json:"last_position"`
}

func (q *Queries) GetExternalLessonContentForSession(ctx context.Context, arg GetExternalLessonContentForSessionParams) (GetExternalLessonContentForSessionRow, error) {
	row := q.db.QueryRow(ctx, getExternalLessonContentForSession,
		arg.CompanyID,
		arg.EnrollmentID,
		arg.LessonVersionID,
		arg.SessionID,
		arg.Now,
	)
	var i GetExternalLessonContentForSessionRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseVersionID,
		&i.SectionVersionID,
		&i.Title,
		&i.Order,
		&i.Content,
		&i.SourceType,
		&i.EstimatedMinutes,
		&i.FileIds,
		&i.QuizVersionID,
		&i.LessonStatus,
		&i.FirstOpenedAt,
		&i.CompletedAt,
		&i.ActiveSeconds,
		&i.LastPosition,
	)
	return i, err
}

const getExternalQuizForSession = `-- name: GetExternalQuizForSession :one
SELECT quiz.id, quiz.company_id, quiz.course_version_id,
    quiz.lesson_version_id, quiz.questions, quiz.passing_score,
    quiz.max_attempts
FROM course_enrollments AS enrollment
JOIN external_sessions AS session
  ON session.company_id = enrollment.company_id
 AND session.external_learner_id = enrollment.external_learner_id
JOIN enrollment_lesson_progress AS progress
  ON progress.company_id = enrollment.company_id
 AND progress.enrollment_id = enrollment.id
JOIN course_version_quizzes AS quiz
  ON quiz.company_id = enrollment.company_id
 AND quiz.course_version_id = enrollment.course_version_id
 AND quiz.id = $1
 AND quiz.lesson_version_id = progress.lesson_version_id
WHERE enrollment.company_id = $2
  AND enrollment.id = $3
  AND enrollment.learner_type = 'external'
  AND session.id = $4
  AND session.revoked_at IS NULL
  AND session.expires_at > $5
  AND enrollment.access_status = 'active'
  AND enrollment.access_until > $5
  AND progress.status IN ('current', 'available')
`

type GetExternalQuizForSessionParams struct {
	QuizVersionID uuid.UUID `json:"quiz_version_id"`
	CompanyID     uuid.UUID `json:"company_id"`
	EnrollmentID  uuid.UUID `json:"enrollment_id"`
	SessionID     uuid.UUID `json:"session_id"`
	Now           time.Time `json:"now"`
}

func (q *Queries) GetExternalQuizForSession(ctx context.Context, arg GetExternalQuizForSessionParams) (CourseVersionQuiz, error) {
	row := q.db.QueryRow(ctx, getExternalQuizForSession,
		arg.QuizVersionID,
		arg.CompanyID,
		arg.EnrollmentID,
		arg.SessionID,
		arg.Now,
	)
	var i CourseVersionQuiz
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseVersionID,
		&i.LessonVersionID,
		&i.Questions,
		&i.PassingScore,
		&i.MaxAttempts,
	)
	return i, err
}

const listCourseEnrollmentAccessHistory = `-- name: ListCourseEnrollmentAccessHistory :many
SELECT history.id, history.company_id, history.enrollment_id,
    history.from_access_status, history.to_access_status,
    history.actor_type, history.actor_id, history.reason,
    history.access_until_before, history.access_until_after,
    history.occurred_at
FROM course_enrollment_access_history AS history
JOIN course_enrollments AS enrollment
  ON enrollment.company_id = history.company_id
 AND enrollment.id = history.enrollment_id
JOIN courses AS course
  ON course.company_id = enrollment.company_id
 AND course.id = enrollment.course_id
WHERE history.company_id = $1
  AND history.enrollment_id = $2
  AND enrollment.learner_type = 'external'
  AND ($3::uuid IS NULL
       OR (course.owner_type = 'partner'
           AND course.owner_user_id = $3::uuid))
ORDER BY history.occurred_at, history.id
`

type ListCourseEnrollmentAccessHistoryParams struct {
	CompanyID      uuid.UUID     `json:"company_id"`
	EnrollmentID   uuid.UUID     `json:"enrollment_id"`
	PartnerOwnerID uuid.NullUUID `json:"partner_owner_id"`
}

func (q *Queries) ListCourseEnrollmentAccessHistory(ctx context.Context, arg ListCourseEnrollmentAccessHistoryParams) ([]CourseEnrollmentAccessHistory, error) {
	rows, err := q.db.Query(ctx, listCourseEnrollmentAccessHistory, arg.CompanyID, arg.EnrollmentID, arg.PartnerOwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseEnrollmentAccessHistory{}
	for rows.Next() {
		var i CourseEnrollmentAccessHistory
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EnrollmentID,
			&i.FromAccessStatus,
			&i.ToAccessStatus,
			&i.ActorType,
			&i.ActorID,
			&i.Reason,
			&i.AccessUntilBefore,
			&i.AccessUntilAfter,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalAccessLandingOutline = `-- name: ListExternalAccessLandingOutline :many
SELECT lesson.id, lesson.company_id, lesson.course_version_id,
    lesson.section_version_id, section.title AS section_title,
    section."order" AS section_order, lesson.title,
    lesson."order" AS lesson_order, lesson.estimated_minutes,
    (lesson.quiz_version_id IS NOT NULL) AS has_quiz
FROM external_personal_accesses AS access
JOIN course_version_sections AS section
  ON section.company_id = access.company_id
 AND section.course_version_id = access.course_version_id
JOIN course_version_lessons AS lesson
  ON lesson.company_id = access.company_id
 AND lesson.course_version_id = access.course_version_id
 AND lesson.section_version_id = section.id
WHERE access.company_id = $1
  AND access.id = $2
  AND access.status IN ('issued', 'activated')
ORDER BY section."order", lesson."order", lesson.id
`

type ListExternalAccessLandingOutlineParams struct {
	CompanyID        uuid.UUID `json:"company_id"`
	PersonalAccessID uuid.UUID `json:"personal_access_id"`
}

type ListExternalAccessLandingOutlineRow struct {
	ID               uuid.UUID   `json:"id"`
	CompanyID        uuid.UUID   `json:"company_id"`
	CourseVersionID  uuid.UUID   `json:"course_version_id"`
	SectionVersionID uuid.UUID   `json:"section_version_id"`
	SectionTitle     string      `json:"section_title"`
	SectionOrder     int32       `json:"section_order"`
	Title            string      `json:"title"`
	LessonOrder      int32       `json:"lesson_order"`
	EstimatedMinutes pgtype.Int4 `json:"estimated_minutes"`
	HasQuiz          interface{} `json:"has_quiz"`
}

func (q *Queries) ListExternalAccessLandingOutline(ctx context.Context, arg ListExternalAccessLandingOutlineParams) ([]ListExternalAccessLandingOutlineRow, error) {
	rows, err := q.db.Query(ctx, listExternalAccessLandingOutline, arg.CompanyID, arg.PersonalAccessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExternalAccessLandingOutlineRow{}
	for rows.Next() {
		var i ListExternalAccessLandingOutlineRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CourseVersionID,
			&i.SectionVersionID,
			&i.SectionTitle,
			&i.SectionOrder,
			&i.Title,
			&i.LessonOrder,
			&i.EstimatedMinutes,
			&i.HasQuiz,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalCampaignLandingOutline = `-- name: ListExternalCampaignLandingOutline :many
SELECT lesson.id, lesson.company_id, lesson.course_version_id,
    lesson.section_version_id, section.title AS section_title,
    section."order" AS section_order, lesson.title,
    lesson."order" AS lesson_order, lesson.estimated_minutes,
    (lesson.quiz_version_id IS NOT NULL) AS has_quiz
FROM external_campaigns AS campaign
JOIN course_version_sections AS section
  ON section.company_id = campaign.company_id
 AND section.course_version_id = campaign.course_version_id
JOIN course_version_lessons AS lesson
  ON lesson.company_id = campaign.company_id
 AND lesson.course_version_id = campaign.course_version_id
 AND lesson.section_version_id = section.id
WHERE campaign.company_id = $1
  AND campaign.id = $2
ORDER BY section."order", lesson."order", lesson.id
`

type ListExternalCampaignLandingOutlineParams struct {
	CompanyID  uuid.UUID `json:"company_id"`
	CampaignID uuid.UUID `json:"campaign_id"`
}

type ListExternalCampaignLandingOutlineRow struct {
	ID               uuid.UUID   `json:"id"`
	CompanyID        uuid.UUID   `json:"company_id"`
	CourseVersionID  uuid.UUID   `json:"course_version_id"`
	SectionVersionID uuid.UUID   `json:"section_version_id"`
	SectionTitle     string      `json:"section_title"`
	SectionOrder     int32       `json:"section_order"`
	Title            string      `json:"title"`
	LessonOrder      int32       `json:"lesson_order"`
	EstimatedMinutes pgtype.Int4 `json:"estimated_minutes"`
	HasQuiz          interface{} `json:"has_quiz"`
}

func (q *Queries) ListExternalCampaignLandingOutline(ctx context.Context, arg ListExternalCampaignLandingOutlineParams) ([]ListExternalCampaignLandingOutlineRow, error) {
	rows, err := q.db.Query(ctx, listExternalCampaignLandingOutline, arg.CompanyID, arg.CampaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExternalCampaignLandingOutlineRow{}
	for rows.Next() {
		var i ListExternalCampaignLandingOutlineRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CourseVersionID,
			&i.SectionVersionID,
			&i.SectionTitle,
			&i.SectionOrder,
			&i.Title,
			&i.LessonOrder,
			&i.EstimatedMinutes,
			&i.HasQuiz,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalEnrollmentLessonReport = `-- name: ListExternalEnrollmentLessonReport :many
SELECT lesson.id AS lesson_version_id, lesson.title,
    section."order" AS section_order, lesson."order" AS lesson_order,
    progress.status, progress.first_opened_at, progress.completed_at,
    COALESCE(progress.active_seconds, 0)::bigint AS active_seconds,
    progress.last_position
FROM course_enrollments AS enrollment
JOIN courses AS course
  ON course.company_id = enrollment.company_id
 AND course.id = enrollment.course_id
JOIN course_version_lessons AS lesson
  ON lesson.company_id = enrollment.company_id
 AND lesson.course_version_id = enrollment.course_version_id
JOIN course_version_sections AS section ON section.id = lesson.section_version_id
LEFT JOIN enrollment_lesson_progress AS progress
  ON progress.company_id = enrollment.company_id
 AND progress.enrollment_id = enrollment.id
 AND progress.lesson_version_id = lesson.id
WHERE enrollment.company_id = $1
  AND enrollment.id = $2
  AND enrollment.learner_type = 'external'
  AND ($3::uuid IS NULL
       OR (course.owner_type = 'partner'
           AND course.owner_user_id = $3::uuid))
ORDER BY section."order", lesson."order", lesson.id
`

type ListExternalEnrollmentLessonReportParams struct {
	CompanyID      uuid.UUID     `json:"company_id"`
	EnrollmentID   uuid.UUID     `json:"enrollment_id"`
	PartnerOwnerID uuid.NullUUID `json:"partner_owner_id"`
}

type ListExternalEnrollmentLessonReportRow struct {
	LessonVersionID uuid.UUID          `json:"lesson_version_id"`
	Title           string             `json:"title"`
	SectionOrder    int32              `json:"section_order"`
	LessonOrder     int32              `json:"lesson_order"`
	Status          pgtype.Text        `json:"status"`
	FirstOpenedAt   pgtype.Timestamptz `json:"first_opened_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	ActiveSeconds   int64              `json:"active_seconds"`
	LastPosition    pgtype.Text        `json:"last_position"`
}

func (q *Queries) ListExternalEnrollmentLessonReport(ctx context.Context, arg ListExternalEnrollmentLessonReportParams) ([]ListExternalEnrollmentLessonReportRow, error) {
	rows, err := q.db.Query(ctx, listExternalEnrollmentLessonReport, arg.CompanyID, arg.EnrollmentID, arg.PartnerOwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExternalEnrollmentLessonReportRow{}
	for rows.Next() {
		var i ListExternalEnrollmentLessonReportRow
		if err := rows.Scan(
			&i.LessonVersionID,
			&i.Title,
			&i.SectionOrder,
			&i.LessonOrder,
			&i.Status,
			&i.FirstOpenedAt,
			&i.CompletedAt,
			&i.ActiveSeconds,
			&i.LastPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalEnrollmentOutlineForSession = `-- name: ListExternalEnrollmentOutlineForSession :many
SELECT lesson.id, lesson.company_id, lesson.course_version_id,
    lesson.section_version_id, section.title AS section_title,
    section."order" AS section_order, lesson.title,
    lesson."order" AS lesson_order, lesson.estimated_minutes,
    (lesson.quiz_version_id IS NOT NULL) AS has_quiz,
    progress.status AS lesson_status, progress.first_opened_at,
    progress.completed_at, COALESCE(progress.active_seconds, 0)::bigint
        AS active_seconds,
    CASE
        WHEN enrollment.access_status = 'active'
             AND enrollment.access_until > $1 THEN progress.status IS NOT NULL
        WHEN enrollment.access_status IN ('expired', 'frozen')
             THEN progress.status = 'completed'
        ELSE false
    END AS content_available
FROM course_enrollments AS enrollment
JOIN external_sessions AS session
  ON session.company_id = enrollment.company_id
 AND session.external_learner_id = enrollment.external_learner_id
JOIN course_version_sections AS section
  ON section.company_id = enrollment.company_id
 AND section.course_version_id = enrollment.course_version_id
JOIN course_version_lessons AS lesson
  ON lesson.company_id = enrollment.company_id
 AND lesson.course_version_id = enrollment.course_version_id
 AND lesson.section_version_id = section.id
LEFT JOIN enrollment_lesson_progress AS progress
  ON progress.company_id = enrollment.company_id
 AND progress.enrollment_id = enrollment.id
 AND progress.lesson_version_id = lesson.id
WHERE enrollment.company_id = $2
  AND enrollment.id = $3
  AND enrollment.learner_type = 'external'
  AND session.id = $4
  AND session.revoked_at IS NULL
  AND session.expires_at > $1
ORDER BY section."order", lesson."order", lesson.id
`

type ListExternalEnrollmentOutlineForSessionParams struct {
	Now          pgtype.Timestamptz `json:"now"`
	CompanyID    uuid.UUID          `json:"company_id"`
	EnrollmentID uuid.UUID          `json:"enrollment_id"`
	SessionID    uuid.UUID          `json:"session_id"`
}

type ListExternalEnrollmentOutlineForSessionRow struct {
	ID               uuid.UUID          `json:"id"`
	CompanyID        uuid.UUID          `json:"company_id"`
	CourseVersionID  uuid.UUID          `json:"course_version_id"`
	SectionVersionID uuid.UUID          `json:"section_version_id"`
	SectionTitle     string             `json:"section_title"`
	SectionOrder     int32              `json:"section_order"`
	Title            string             `json:"title"`
	LessonOrder      int32              `json:"lesson_order"`
	EstimatedMinutes pgtype.Int4        `json:"estimated_minutes"`
	HasQuiz          interface{}        `json:"has_quiz"`
	LessonStatus     pgtype.Text        `json:"lesson_status"`
	FirstOpenedAt    pgtype.Timestamptz `json:"first_opened_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	ActiveSeconds    int64              `json:"active_seconds"`
	ContentAvailable bool               `json:"content_available"`
}

func (q *Queries) ListExternalEnrollmentOutlineForSession(ctx context.Context, arg ListExternalEnrollmentOutlineForSessionParams) ([]ListExternalEnrollmentOutlineForSessionRow, error) {
	rows, err := q.db.Query(ctx, listExternalEnrollmentOutlineForSession,
		arg.Now,
		arg.CompanyID,
		arg.EnrollmentID,
		arg.SessionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExternalEnrollmentOutlineForSessionRow{}
	for rows.Next() {
		var i ListExternalEnrollmentOutlineForSessionRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CourseVersionID,
			&i.SectionVersionID,
			&i.SectionTitle,
			&i.SectionOrder,
			&i.Title,
			&i.LessonOrder,
			&i.EstimatedMinutes,
			&i.HasQuiz,
			&i.LessonStatus,
			&i.FirstOpenedAt,
			&i.CompletedAt,
			&i.ActiveSeconds,
			&i.ContentAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalEnrollmentQuizAttemptReport = `-- name: ListExternalEnrollmentQuizAttemptReport :many
SELECT attempt.id, attempt.company_id, attempt.enrollment_id,
    attempt.quiz_version_id, attempt.answers, attempt.score,
    attempt.passed, attempt.pending_review, attempt.reviewed_by_id,
    attempt.reviewed_at, attempt.review_comment, attempt.created_at
FROM quiz_attempts AS attempt
JOIN course_enrollments AS enrollment
  ON enrollment.company_id = attempt.company_id
 AND enrollment.id = attempt.enrollment_id
JOIN courses AS course
  ON course.company_id = enrollment.company_id
 AND course.id = enrollment.course_id
WHERE attempt.company_id = $1
  AND attempt.enrollment_id = $2
  AND enrollment.learner_type = 'external'
  AND ($3::uuid IS NULL
       OR (course.owner_type = 'partner'
           AND course.owner_user_id = $3::uuid))
ORDER BY attempt.created_at DESC, attempt.id DESC
`

type ListExternalEnrollmentQuizAttemptReportParams struct {
	CompanyID      uuid.UUID     `json:"company_id"`
	EnrollmentID   uuid.UUID     `json:"enrollment_id"`
	PartnerOwnerID uuid.NullUUID `json:"partner_owner_id"`
}

type ListExternalEnrollmentQuizAttemptReportRow struct {
	ID            uuid.UUID          `json:"id"`
	CompanyID     uuid.UUID          `json:"company_id"`
	EnrollmentID  uuid.UUID          `json:"enrollment_id"`
	QuizVersionID uuid.UUID          `json:"quiz_version_id"`
	Answers       []byte             `json:"answers"`
	Score         int32              `json:"score"`
	Passed        bool               `json:"passed"`
	PendingReview bool               `json:"pending_review"`
	ReviewedByID  uuid.NullUUID      `json:"reviewed_by_id"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	ReviewComment pgtype.Text        `json:"review_comment"`
	CreatedAt     time.Time          `json:"created_at"`
}

func (q *Queries) ListExternalEnrollmentQuizAttemptReport(ctx context.Context, arg ListExternalEnrollmentQuizAttemptReportParams) ([]ListExternalEnrollmentQuizAttemptReportRow, error) {
	rows, err := q.db.Query(ctx, listExternalEnrollmentQuizAttemptReport, arg.CompanyID, arg.EnrollmentID, arg.PartnerOwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExternalEnrollmentQuizAttemptReportRow{}
	for rows.Next() {
		var i ListExternalEnrollmentQuizAttemptReportRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EnrollmentID,
			&i.QuizVersionID,
			&i.Answers,
			&i.Score,
			&i.Passed,
			&i.PendingReview,
			&i.ReviewedByID,
			&i.ReviewedAt,
			&i.ReviewComment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalLearnerEnrollmentsForReport = `-- name: ListExternalLearnerEnrollmentsForReport :many
SELECT enrollment.id, enrollment.company_id, enrollment.course_id,
    enrollment.course_version_id, version.number AS course_version_number,
    version.title AS course_title, enrollment.source_type,
    enrollment.source_id, enrollment.attempt_number,
    enrollment.progress_status, enrollment.access_status,
    enrollment.current_lesson_version_id, enrollment.activated_at,
    enrollment.access_until, enrollment.started_at, enrollment.completed_at,
    enrollment.last_activity_at, enrollment.frozen_at,
    enrollment.suspended_at, enrollment.created_at,
    count(lesson.id)::integer AS lesson_count,
    count(lesson.id) FILTER (
        WHERE progress.status = 'completed'
    )::integer AS completed_lesson_count,
    CASE WHEN count(lesson.id) = 0 THEN 0
         ELSE (count(lesson.id) FILTER (WHERE progress.status = 'completed')
               * 100 / count(lesson.id))::integer END AS progress_percent,
    COALESCE(sum(progress.active_seconds), 0)::bigint AS active_seconds
FROM course_enrollments AS enrollment
JOIN courses AS course
  ON course.company_id = enrollment.company_id
 AND course.id = enrollment.course_id
JOIN course_versions AS version
  ON version.company_id = enrollment.company_id
 AND version.id = enrollment.course_version_id
LEFT JOIN course_version_lessons AS lesson
  ON lesson.company_id = enrollment.company_id
 AND lesson.course_version_id = enrollment.course_version_id
LEFT JOIN enrollment_lesson_progress AS progress
  ON progress.company_id = enrollment.company_id
 AND progress.enrollment_id = enrollment.id
 AND progress.lesson_version_id = lesson.id
WHERE enrollment.company_id = $1
  AND enrollment.external_learner_id = $2
  AND enrollment.learner_type = 'external'
  AND ($3::uuid IS NULL
       OR (course.owner_type = 'partner'
           AND course.owner_user_id = $3::uuid))
GROUP BY enrollment.id, version.number, version.title
ORDER BY enrollment.created_at DESC, enrollment.id DESC
`

type ListExternalLearnerEnrollmentsForReportParams struct {
	CompanyID      uuid.UUID     `json:"company_id"`
	LearnerID      uuid.NullUUID `json:"learner_id"`
	PartnerOwnerID uuid.NullUUID `json:"partner_owner_id"`
}

type ListExternalLearnerEnrollmentsForReportRow struct {
	ID                     uuid.UUID          `json:"id"`
	CompanyID              uuid.UUID          `json:"company_id"`
	CourseID               uuid.UUID          `json:"course_id"`
	CourseVersionID        uuid.UUID          `json:"course_version_id"`
	CourseVersionNumber    int32              `json:"course_version_number"`
	CourseTitle            string             `json:"course_title"`
	SourceType             string             `json:"source_type"`
	SourceID               uuid.NullUUID      `json:"source_id"`
	AttemptNumber          int32              `json:"attempt_number"`
	ProgressStatus         string             `json:"progress_status"`
	AccessStatus           string             `json:"access_status"`
	CurrentLessonVersionID uuid.NullUUID      `json:"current_lesson_version_id"`
	ActivatedAt            pgtype.Timestamptz `json:"activated_at"`
	AccessUntil            pgtype.Timestamptz `json:"access_until"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	LastActivityAt         pgtype.Timestamptz `json:"last_activity_at"`
	FrozenAt               pgtype.Timestamptz `json:"frozen_at"`
	SuspendedAt            pgtype.Timestamptz `json:"suspended_at"`
	CreatedAt              time.Time          `json:"created_at"`
	LessonCount            int32              `json:"lesson_count"`
	CompletedLessonCount   int32              `json:"completed_lesson_count"`
	ProgressPercent        int32              `json:"progress_percent"`
	ActiveSeconds          int64              `json:"active_seconds"`
}

func (q *Queries) ListExternalLearnerEnrollmentsForReport(ctx context.Context, arg ListExternalLearnerEnrollmentsForReportParams) ([]ListExternalLearnerEnrollmentsForReportRow, error) {
	rows, err := q.db.Query(ctx, listExternalLearnerEnrollmentsForReport, arg.CompanyID, arg.LearnerID, arg.PartnerOwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExternalLearnerEnrollmentsForReportRow{}
	for rows.Next() {
		var i ListExternalLearnerEnrollmentsForReportRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CourseID,
			&i.CourseVersionID,
			&i.CourseVersionNumber,
			&i.CourseTitle,
			&i.SourceType,
			&i.SourceID,
			&i.AttemptNumber,
			&i.ProgressStatus,
			&i.AccessStatus,
			&i.CurrentLessonVersionID,
			&i.ActivatedAt,
			&i.AccessUntil,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LastActivityAt,
			&i.FrozenAt,
			&i.SuspendedAt,
			&i.CreatedAt,
			&i.LessonCount,
			&i.CompletedLessonCount,
			&i.ProgressPercent,
			&i.ActiveSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalLearnersForReport = `-- name: ListExternalLearnersForReport :many
SELECT learner.id, learner.company_id, learner.email,
    learner.normalized_email, learner.first_name, learner.last_name,
    learner.phone, learner.email_verified_at, learner.created_at,
    learner.updated_at,
    count(DISTINCT enrollment.id)::integer AS enrollment_count,
    count(DISTINCT enrollment.id) FILTER (
        WHERE enrollment.progress_status = 'completed'
    )::integer AS completed_enrollment_count,
    max(enrollment.last_activity_at) AS last_activity_at
FROM external_learners AS learner
JOIN course_enrollments AS enrollment
  ON enrollment.company_id = learner.company_id
 AND enrollment.external_learner_id = learner.id
 AND enrollment.learner_type = 'external'
JOIN courses AS course
  ON course.company_id = enrollment.company_id
 AND course.id = enrollment.course_id
WHERE learner.company_id = $1
  AND learner.deleted_at IS NULL
  AND ($2::uuid IS NULL
       OR (course.owner_type = 'partner'
           AND course.owner_user_id = $2::uuid))
  AND ($3::text IS NULL
       OR learner.normalized_email ILIKE '%' || $3::text || '%'
       OR COALESCE(learner.first_name, '') ILIKE '%' || $3::text || '%'
       OR COALESCE(learner.last_name, '') ILIKE '%' || $3::text || '%')
GROUP BY learner.id
ORDER BY max(enrollment.last_activity_at) DESC NULLS LAST,
    learner.created_at DESC, learner.id DESC
`

type ListExternalLearnersForReportParams struct {
	CompanyID      uuid.UUID     `json:"company_id"`
	PartnerOwnerID uuid.NullUUID `json:"partner_owner_id"`
	Search         pgtype.Text   `json:"search"`
}

type ListExternalLearnersForReportRow struct {
	ID                       uuid.UUID          `json:"id"`
	CompanyID                uuid.UUID          `json:"company_id"`
	Email                    string             `json:"email"`
	NormalizedEmail          string             `json:"normalized_email"`
	FirstName                pgtype.Text        `json:"first_name"`
	LastName                 pgtype.Text        `json:"last_name"`
	Phone                    pgtype.Text        `json:"phone"`
	EmailVerifiedAt          pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt                time.Time          `json:"created_at"`
	UpdatedAt                time.Time          `json:"updated_at"`
	EnrollmentCount          int32              `json:"enrollment_count"`
	CompletedEnrollmentCount int32              `json:"completed_enrollment_count"`
	LastActivityAt           interface{}        `json:"last_activity_at"`
}

func (q *Queries) ListExternalLearnersForReport(ctx context.Context, arg ListExternalLearnersForReportParams) ([]ListExternalLearnersForReportRow, error) {
	rows, err := q.db.Query(ctx, listExternalLearnersForReport, arg.CompanyID, arg.PartnerOwnerID, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExternalLearnersForReportRow{}
	for rows.Next() {
		var i ListExternalLearnersForReportRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Email,
			&i.NormalizedEmail,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrollmentCount,
			&i.CompletedEnrollmentCount,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalPersonalAccessHistory = `-- name: ListExternalPersonalAccessHistory :many
SELECT history.id, history.company_id, history.personal_access_id,
    history.external_learner_id, history.enrollment_id, history.event_type,
    history.actor_type, history.actor_id, history.idempotency_key,
    history.previous_token_prefix, history.current_token_prefix,
    history.access_until_before, history.access_until_after,
    history.details, history.occurred_at
FROM external_personal_access_history AS history
JOIN external_personal_accesses AS access
  ON access.company_id = history.company_id
 AND access.id = history.personal_access_id
WHERE history.company_id = $1
  AND history.personal_access_id = $2
  AND ($3::uuid IS NULL
       OR access.partner_owner_id = $3::uuid)
ORDER BY history.occurred_at, history.id
`

type ListExternalPersonalAccessHistoryParams struct {
	CompanyID        uuid.UUID     `json:"company_id"`
	PersonalAccessID uuid.UUID     `json:"personal_access_id"`
	PartnerOwnerID   uuid.NullUUID `json:"partner_owner_id"`
}

func (q *Queries) ListExternalPersonalAccessHistory(ctx context.Context, arg ListExternalPersonalAccessHistoryParams) ([]ExternalPersonalAccessHistory, error) {
	rows, err := q.db.Query(ctx, listExternalPersonalAccessHistory, arg.CompanyID, arg.PersonalAccessID, arg.PartnerOwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalPersonalAccessHistory{}
	for rows.Next() {
		var i ExternalPersonalAccessHistory
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.PersonalAccessID,
			&i.ExternalLearnerID,
			&i.EnrollmentID,
			&i.EventType,
			&i.ActorType,
			&i.ActorID,
			&i.IdempotencyKey,
			&i.PreviousTokenPrefix,
			&i.CurrentTokenPrefix,
			&i.AccessUntilBefore,
			&i.AccessUntilAfter,
			&i.Details,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalQuizResultsForSession = `-- name: ListExternalQuizResultsForSession :many
SELECT attempt.id, attempt.company_id, attempt.enrollment_id,
    attempt.quiz_version_id, attempt.answers, attempt.score,
    attempt.passed, attempt.pending_review, attempt.reviewed_at,
    attempt.review_comment, attempt.created_at
FROM quiz_attempts AS attempt
JOIN course_enrollments AS enrollment
  ON enrollment.company_id = attempt.company_id
 AND enrollment.id = attempt.enrollment_id
JOIN external_sessions AS session
  ON session.company_id = enrollment.company_id
 AND session.external_learner_id = enrollment.external_learner_id
WHERE attempt.company_id = $1
  AND attempt.enrollment_id = $2
  AND enrollment.learner_type = 'external'
  AND session.id = $3
  AND session.revoked_at IS NULL
  AND session.expires_at > $4
  AND enrollment.access_status IN ('active', 'expired', 'frozen')
ORDER BY attempt.created_at DESC, attempt.id DESC
`

type ListExternalQuizResultsForSessionParams struct {
	CompanyID    uuid.UUID `json:"company_id"`
	EnrollmentID uuid.UUID `json:"enrollment_id"`
	SessionID    uuid.UUID `json:"session_id"`
	Now          time.Time `json:"now"`
}

type ListExternalQuizResultsForSessionRow struct {
	ID            uuid.UUID          `json:"id"`
	CompanyID     uuid.UUID          `json:"company_id"`
	EnrollmentID  uuid.UUID          `json:"enrollment_id"`
	QuizVersionID uuid.UUID          `json:"quiz_version_id"`
	Answers       []byte             `json:"answers"`
	Score         int32              `json:"score"`
	Passed        bool               `json:"passed"`
	PendingReview bool               `json:"pending_review"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	ReviewComment pgtype.Text        `json:"review_comment"`
	CreatedAt     time.Time          `json:"created_at"`
}

func (q *Queries) ListExternalQuizResultsForSession(ctx context.Context, arg ListExternalQuizResultsForSessionParams) ([]ListExternalQuizResultsForSessionRow, error) {
	rows, err := q.db.Query(ctx, listExternalQuizResultsForSession,
		arg.CompanyID,
		arg.EnrollmentID,
		arg.SessionID,
		arg.Now,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExternalQuizResultsForSessionRow{}
	for rows.Next() {
		var i ListExternalQuizResultsForSessionRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EnrollmentID,
			&i.QuizVersionID,
			&i.Answers,
			&i.Score,
			&i.Passed,
			&i.PendingReview,
			&i.ReviewedAt,
			&i.ReviewComment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
