// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: external_identity.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeExternalMutationIdempotency = `-- name: CompleteExternalMutationIdempotency :one
UPDATE external_mutation_idempotency
SET result_id = $1,
    enrollment_id = $2,
    result_payload = $3,
    completed_at = $4
WHERE company_id = $5
  AND id = $6
  AND completed_at IS NULL
RETURNING id, company_id, external_learner_id, operation, idempotency_key,
    request_hash, aggregate_id, result_id, enrollment_id, result_payload,
    completed_at, created_at
`

type CompleteExternalMutationIdempotencyParams struct {
	ResultID      uuid.NullUUID      `json:"result_id"`
	EnrollmentID  uuid.NullUUID      `json:"enrollment_id"`
	ResultPayload []byte             `json:"result_payload"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CompanyID     uuid.UUID          `json:"company_id"`
	ID            uuid.UUID          `json:"id"`
}

func (q *Queries) CompleteExternalMutationIdempotency(ctx context.Context, arg CompleteExternalMutationIdempotencyParams) (ExternalMutationIdempotency, error) {
	row := q.db.QueryRow(ctx, completeExternalMutationIdempotency,
		arg.ResultID,
		arg.EnrollmentID,
		arg.ResultPayload,
		arg.CompletedAt,
		arg.CompanyID,
		arg.ID,
	)
	var i ExternalMutationIdempotency
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ExternalLearnerID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.AggregateID,
		&i.ResultID,
		&i.EnrollmentID,
		&i.ResultPayload,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const consumeExternalVerificationChallenge = `-- name: ConsumeExternalVerificationChallenge :one
UPDATE external_verification_challenges
SET consumed_at = $1
WHERE company_id = $2
  AND id = $3
  AND consumed_at IS NULL
  AND invalidated_at IS NULL
  AND expires_at > $1
  AND attempts < max_attempts
RETURNING id, company_id, normalized_email, purpose, source_id,
    claimed_first_name, claimed_last_name, code_hash, request_ip_hash,
    expires_at, attempts, max_attempts, consumed_at, invalidated_at,
    invalidation_reason, created_at
`

type ConsumeExternalVerificationChallengeParams struct {
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CompanyID  uuid.UUID          `json:"company_id"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) ConsumeExternalVerificationChallenge(ctx context.Context, arg ConsumeExternalVerificationChallengeParams) (ExternalVerificationChallenge, error) {
	row := q.db.QueryRow(ctx, consumeExternalVerificationChallenge, arg.ConsumedAt, arg.CompanyID, arg.ID)
	var i ExternalVerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.NormalizedEmail,
		&i.Purpose,
		&i.SourceID,
		&i.ClaimedFirstName,
		&i.ClaimedLastName,
		&i.CodeHash,
		&i.RequestIpHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ConsumedAt,
		&i.InvalidatedAt,
		&i.InvalidationReason,
		&i.CreatedAt,
	)
	return i, err
}

const countRecentExternalChallengesByEmail = `-- name: CountRecentExternalChallengesByEmail :one
SELECT count(*)::integer
FROM external_verification_challenges
WHERE company_id = $1
  AND normalized_email = $2
  AND created_at >= $3
`

type CountRecentExternalChallengesByEmailParams struct {
	CompanyID       uuid.UUID `json:"company_id"`
	NormalizedEmail string    `json:"normalized_email"`
	Since           time.Time `json:"since"`
}

func (q *Queries) CountRecentExternalChallengesByEmail(ctx context.Context, arg CountRecentExternalChallengesByEmailParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRecentExternalChallengesByEmail, arg.CompanyID, arg.NormalizedEmail, arg.Since)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countRecentExternalChallengesByIPHash = `-- name: CountRecentExternalChallengesByIPHash :one
SELECT count(*)::integer
FROM external_verification_challenges
WHERE company_id = $1
  AND request_ip_hash = $2
  AND created_at >= $3
`

type CountRecentExternalChallengesByIPHashParams struct {
	CompanyID     uuid.UUID `json:"company_id"`
	RequestIpHash []byte    `json:"request_ip_hash"`
	Since         time.Time `json:"since"`
}

func (q *Queries) CountRecentExternalChallengesByIPHash(ctx context.Context, arg CountRecentExternalChallengesByIPHashParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRecentExternalChallengesByIPHash, arg.CompanyID, arg.RequestIpHash, arg.Since)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countRecentExternalChallengesBySource = `-- name: CountRecentExternalChallengesBySource :one
SELECT count(*)::integer
FROM external_verification_challenges
WHERE company_id = $1
  AND purpose = $2
  AND source_id = $3
  AND created_at >= $4
`

type CountRecentExternalChallengesBySourceParams struct {
	CompanyID uuid.UUID     `json:"company_id"`
	Purpose   string        `json:"purpose"`
	SourceID  uuid.NullUUID `json:"source_id"`
	Since     time.Time     `json:"since"`
}

func (q *Queries) CountRecentExternalChallengesBySource(ctx context.Context, arg CountRecentExternalChallengesBySourceParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRecentExternalChallengesBySource,
		arg.CompanyID,
		arg.Purpose,
		arg.SourceID,
		arg.Since,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createExternalSession = `-- name: CreateExternalSession :one
INSERT INTO external_sessions (
    id, company_id, external_learner_id, token_hash,
    expires_at, last_used_at, created_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $6
)
RETURNING id, company_id, external_learner_id, token_hash, expires_at,
    last_used_at, revoked_at, revocation_reason, created_at
`

type CreateExternalSessionParams struct {
	ID                uuid.UUID          `json:"id"`
	CompanyID         uuid.UUID          `json:"company_id"`
	ExternalLearnerID uuid.UUID          `json:"external_learner_id"`
	TokenHash         []byte             `json:"token_hash"`
	ExpiresAt         time.Time          `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateExternalSession(ctx context.Context, arg CreateExternalSessionParams) (ExternalSession, error) {
	row := q.db.QueryRow(ctx, createExternalSession,
		arg.ID,
		arg.CompanyID,
		arg.ExternalLearnerID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i ExternalSession
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ExternalLearnerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
	)
	return i, err
}

const createExternalVerificationChallenge = `-- name: CreateExternalVerificationChallenge :one
INSERT INTO external_verification_challenges (
    id, company_id, normalized_email, purpose, source_id,
    claimed_first_name, claimed_last_name, code_hash, request_ip_hash,
    expires_at, attempts, max_attempts, created_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8,
    $9, $10, 0,
    $11, $12
)
RETURNING id, company_id, normalized_email, purpose, source_id,
    claimed_first_name, claimed_last_name, code_hash, request_ip_hash,
    expires_at, attempts, max_attempts, consumed_at, invalidated_at,
    invalidation_reason, created_at
`

type CreateExternalVerificationChallengeParams struct {
	ID               uuid.UUID     `json:"id"`
	CompanyID        uuid.UUID     `json:"company_id"`
	NormalizedEmail  string        `json:"normalized_email"`
	Purpose          string        `json:"purpose"`
	SourceID         uuid.NullUUID `json:"source_id"`
	ClaimedFirstName pgtype.Text   `json:"claimed_first_name"`
	ClaimedLastName  pgtype.Text   `json:"claimed_last_name"`
	CodeHash         []byte        `json:"code_hash"`
	RequestIpHash    []byte        `json:"request_ip_hash"`
	ExpiresAt        time.Time     `json:"expires_at"`
	MaxAttempts      int16         `json:"max_attempts"`
	CreatedAt        time.Time     `json:"created_at"`
}

func (q *Queries) CreateExternalVerificationChallenge(ctx context.Context, arg CreateExternalVerificationChallengeParams) (ExternalVerificationChallenge, error) {
	row := q.db.QueryRow(ctx, createExternalVerificationChallenge,
		arg.ID,
		arg.CompanyID,
		arg.NormalizedEmail,
		arg.Purpose,
		arg.SourceID,
		arg.ClaimedFirstName,
		arg.ClaimedLastName,
		arg.CodeHash,
		arg.RequestIpHash,
		arg.ExpiresAt,
		arg.MaxAttempts,
		arg.CreatedAt,
	)
	var i ExternalVerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.NormalizedEmail,
		&i.Purpose,
		&i.SourceID,
		&i.ClaimedFirstName,
		&i.ClaimedLastName,
		&i.CodeHash,
		&i.RequestIpHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ConsumedAt,
		&i.InvalidatedAt,
		&i.InvalidationReason,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveExternalSessionForEmail = `-- name: GetActiveExternalSessionForEmail :one
SELECT session.id, session.company_id, session.external_learner_id,
    session.token_hash, session.expires_at, session.last_used_at,
    session.revoked_at, session.revocation_reason, session.created_at
FROM external_sessions AS session
JOIN external_learners AS learner
  ON learner.company_id = session.company_id
 AND learner.id = session.external_learner_id
WHERE session.company_id = $1
  AND learner.normalized_email = $2
  AND learner.deleted_at IS NULL
  AND session.revoked_at IS NULL
  AND session.expires_at > $3
ORDER BY session.last_used_at DESC NULLS LAST, session.created_at DESC, session.id DESC
LIMIT 1
`

type GetActiveExternalSessionForEmailParams struct {
	CompanyID       uuid.UUID `json:"company_id"`
	NormalizedEmail string    `json:"normalized_email"`
	Now             time.Time `json:"now"`
}

func (q *Queries) GetActiveExternalSessionForEmail(ctx context.Context, arg GetActiveExternalSessionForEmailParams) (ExternalSession, error) {
	row := q.db.QueryRow(ctx, getActiveExternalSessionForEmail, arg.CompanyID, arg.NormalizedEmail, arg.Now)
	var i ExternalSession
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ExternalLearnerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
	)
	return i, err
}

const getExternalLearner = `-- name: GetExternalLearner :one
SELECT id, company_id, email, normalized_email, first_name, last_name,
    phone, email_verified_at, created_at, updated_at, deleted_at
FROM external_learners
WHERE company_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type GetExternalLearnerParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetExternalLearner(ctx context.Context, arg GetExternalLearnerParams) (ExternalLearner, error) {
	row := q.db.QueryRow(ctx, getExternalLearner, arg.CompanyID, arg.ID)
	var i ExternalLearner
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.NormalizedEmail,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExternalLearnerByEmail = `-- name: GetExternalLearnerByEmail :one
SELECT id, company_id, email, normalized_email, first_name, last_name,
    phone, email_verified_at, created_at, updated_at, deleted_at
FROM external_learners
WHERE company_id = $1
  AND normalized_email = $2
  AND deleted_at IS NULL
`

type GetExternalLearnerByEmailParams struct {
	CompanyID       uuid.UUID `json:"company_id"`
	NormalizedEmail string    `json:"normalized_email"`
}

func (q *Queries) GetExternalLearnerByEmail(ctx context.Context, arg GetExternalLearnerByEmailParams) (ExternalLearner, error) {
	row := q.db.QueryRow(ctx, getExternalLearnerByEmail, arg.CompanyID, arg.NormalizedEmail)
	var i ExternalLearner
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.NormalizedEmail,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExternalMutationIdempotencyForUpdate = `-- name: GetExternalMutationIdempotencyForUpdate :one
SELECT id, company_id, external_learner_id, operation, idempotency_key,
    request_hash, aggregate_id, result_id, enrollment_id, result_payload,
    completed_at, created_at
FROM external_mutation_idempotency
WHERE company_id = $1
  AND external_learner_id = $2
  AND operation = $3
  AND idempotency_key = $4
FOR UPDATE
`

type GetExternalMutationIdempotencyForUpdateParams struct {
	CompanyID         uuid.UUID `json:"company_id"`
	ExternalLearnerID uuid.UUID `json:"external_learner_id"`
	Operation         string    `json:"operation"`
	IdempotencyKey    string    `json:"idempotency_key"`
}

func (q *Queries) GetExternalMutationIdempotencyForUpdate(ctx context.Context, arg GetExternalMutationIdempotencyForUpdateParams) (ExternalMutationIdempotency, error) {
	row := q.db.QueryRow(ctx, getExternalMutationIdempotencyForUpdate,
		arg.CompanyID,
		arg.ExternalLearnerID,
		arg.Operation,
		arg.IdempotencyKey,
	)
	var i ExternalMutationIdempotency
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ExternalLearnerID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.AggregateID,
		&i.ResultID,
		&i.EnrollmentID,
		&i.ResultPayload,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getExternalSessionByTokenHash = `-- name: GetExternalSessionByTokenHash :one
SELECT session.id, session.company_id, session.external_learner_id,
    session.token_hash, session.expires_at, session.last_used_at,
    session.revoked_at, session.revocation_reason, session.created_at
FROM external_sessions AS session
JOIN external_learners AS learner
  ON learner.company_id = session.company_id
 AND learner.id = session.external_learner_id
WHERE session.company_id = $1
  AND session.token_hash = $2
  AND session.revoked_at IS NULL
  AND session.expires_at > $3
  AND learner.deleted_at IS NULL
`

type GetExternalSessionByTokenHashParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	TokenHash []byte    `json:"token_hash"`
	Now       time.Time `json:"now"`
}

func (q *Queries) GetExternalSessionByTokenHash(ctx context.Context, arg GetExternalSessionByTokenHashParams) (ExternalSession, error) {
	row := q.db.QueryRow(ctx, getExternalSessionByTokenHash, arg.CompanyID, arg.TokenHash, arg.Now)
	var i ExternalSession
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ExternalLearnerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
	)
	return i, err
}

const getExternalVerificationChallengeForUpdate = `-- name: GetExternalVerificationChallengeForUpdate :one
SELECT id, company_id, normalized_email, purpose, source_id,
    claimed_first_name, claimed_last_name, code_hash, request_ip_hash,
    expires_at, attempts, max_attempts, consumed_at, invalidated_at,
    invalidation_reason, created_at
FROM external_verification_challenges
WHERE company_id = $1
  AND id = $2
FOR UPDATE
`

type GetExternalVerificationChallengeForUpdateParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetExternalVerificationChallengeForUpdate(ctx context.Context, arg GetExternalVerificationChallengeForUpdateParams) (ExternalVerificationChallenge, error) {
	row := q.db.QueryRow(ctx, getExternalVerificationChallengeForUpdate, arg.CompanyID, arg.ID)
	var i ExternalVerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.NormalizedEmail,
		&i.Purpose,
		&i.SourceID,
		&i.ClaimedFirstName,
		&i.ClaimedLastName,
		&i.CodeHash,
		&i.RequestIpHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ConsumedAt,
		&i.InvalidatedAt,
		&i.InvalidationReason,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateOpenExternalChallenges = `-- name: InvalidateOpenExternalChallenges :execrows
UPDATE external_verification_challenges
SET invalidated_at = $1,
    invalidation_reason = $2
WHERE company_id = $3
  AND normalized_email = $4
  AND purpose = $5
  AND source_id IS NOT DISTINCT FROM $6::uuid
  AND consumed_at IS NULL
  AND invalidated_at IS NULL
  AND id <> $7
`

type InvalidateOpenExternalChallengesParams struct {
	InvalidatedAt      pgtype.Timestamptz `json:"invalidated_at"`
	InvalidationReason pgtype.Text        `json:"invalidation_reason"`
	CompanyID          uuid.UUID          `json:"company_id"`
	NormalizedEmail    string             `json:"normalized_email"`
	Purpose            string             `json:"purpose"`
	SourceID           uuid.NullUUID      `json:"source_id"`
	ExceptID           uuid.UUID          `json:"except_id"`
}

func (q *Queries) InvalidateOpenExternalChallenges(ctx context.Context, arg InvalidateOpenExternalChallengesParams) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateOpenExternalChallenges,
		arg.InvalidatedAt,
		arg.InvalidationReason,
		arg.CompanyID,
		arg.NormalizedEmail,
		arg.Purpose,
		arg.SourceID,
		arg.ExceptID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const materializeExpiredExternalChallenges = `-- name: MaterializeExpiredExternalChallenges :many
UPDATE external_verification_challenges AS challenge
SET invalidated_at = challenge.expires_at,
    invalidation_reason = 'expired'
WHERE challenge.id IN (
    SELECT candidate.id
    FROM external_verification_challenges AS candidate
    WHERE candidate.company_id = $1
      AND candidate.consumed_at IS NULL
      AND candidate.invalidated_at IS NULL
      AND candidate.expires_at <= $2
    ORDER BY candidate.expires_at, candidate.id
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING id, company_id, normalized_email, purpose, source_id,
    claimed_first_name, claimed_last_name, expires_at, attempts, max_attempts,
    consumed_at, invalidated_at, invalidation_reason, created_at
`

type MaterializeExpiredExternalChallengesParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Now       time.Time `json:"now"`
	BatchSize int32     `json:"batch_size"`
}

type MaterializeExpiredExternalChallengesRow struct {
	ID                 uuid.UUID          `json:"id"`
	CompanyID          uuid.UUID          `json:"company_id"`
	NormalizedEmail    string             `json:"normalized_email"`
	Purpose            string             `json:"purpose"`
	SourceID           uuid.NullUUID      `json:"source_id"`
	ClaimedFirstName   pgtype.Text        `json:"claimed_first_name"`
	ClaimedLastName    pgtype.Text        `json:"claimed_last_name"`
	ExpiresAt          time.Time          `json:"expires_at"`
	Attempts           int16              `json:"attempts"`
	MaxAttempts        int16              `json:"max_attempts"`
	ConsumedAt         pgtype.Timestamptz `json:"consumed_at"`
	InvalidatedAt      pgtype.Timestamptz `json:"invalidated_at"`
	InvalidationReason pgtype.Text        `json:"invalidation_reason"`
	CreatedAt          time.Time          `json:"created_at"`
}

func (q *Queries) MaterializeExpiredExternalChallenges(ctx context.Context, arg MaterializeExpiredExternalChallengesParams) ([]MaterializeExpiredExternalChallengesRow, error) {
	rows, err := q.db.Query(ctx, materializeExpiredExternalChallenges, arg.CompanyID, arg.Now, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaterializeExpiredExternalChallengesRow{}
	for rows.Next() {
		var i MaterializeExpiredExternalChallengesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.NormalizedEmail,
			&i.Purpose,
			&i.SourceID,
			&i.ClaimedFirstName,
			&i.ClaimedLastName,
			&i.ExpiresAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.ConsumedAt,
			&i.InvalidatedAt,
			&i.InvalidationReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordExternalVerificationFailure = `-- name: RecordExternalVerificationFailure :one
UPDATE external_verification_challenges
SET attempts = attempts + 1,
    invalidated_at = CASE
        WHEN attempts + 1 >= max_attempts THEN $1
        ELSE invalidated_at
    END,
    invalidation_reason = CASE
        WHEN attempts + 1 >= max_attempts THEN 'attempts_exhausted'
        ELSE invalidation_reason
    END
WHERE company_id = $2
  AND id = $3
  AND consumed_at IS NULL
  AND invalidated_at IS NULL
  AND expires_at > $1
  AND attempts < max_attempts
RETURNING id, company_id, normalized_email, purpose, source_id,
    claimed_first_name, claimed_last_name, code_hash, request_ip_hash,
    expires_at, attempts, max_attempts, consumed_at, invalidated_at,
    invalidation_reason, created_at
`

type RecordExternalVerificationFailureParams struct {
	AttemptedAt pgtype.Timestamptz `json:"attempted_at"`
	CompanyID   uuid.UUID          `json:"company_id"`
	ID          uuid.UUID          `json:"id"`
}

func (q *Queries) RecordExternalVerificationFailure(ctx context.Context, arg RecordExternalVerificationFailureParams) (ExternalVerificationChallenge, error) {
	row := q.db.QueryRow(ctx, recordExternalVerificationFailure, arg.AttemptedAt, arg.CompanyID, arg.ID)
	var i ExternalVerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.NormalizedEmail,
		&i.Purpose,
		&i.SourceID,
		&i.ClaimedFirstName,
		&i.ClaimedLastName,
		&i.CodeHash,
		&i.RequestIpHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ConsumedAt,
		&i.InvalidatedAt,
		&i.InvalidationReason,
		&i.CreatedAt,
	)
	return i, err
}

const reserveExternalMutationIdempotency = `-- name: ReserveExternalMutationIdempotency :one
INSERT INTO external_mutation_idempotency (
    id, company_id, external_learner_id, operation, idempotency_key,
    request_hash, aggregate_id, created_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
ON CONFLICT (company_id, external_learner_id, operation, idempotency_key)
DO UPDATE SET id = external_mutation_idempotency.id
RETURNING id, company_id, external_learner_id, operation, idempotency_key,
    request_hash, aggregate_id, result_id, enrollment_id, result_payload,
    completed_at, created_at
`

type ReserveExternalMutationIdempotencyParams struct {
	ID                uuid.UUID `json:"id"`
	CompanyID         uuid.UUID `json:"company_id"`
	ExternalLearnerID uuid.UUID `json:"external_learner_id"`
	Operation         string    `json:"operation"`
	IdempotencyKey    string    `json:"idempotency_key"`
	RequestHash       string    `json:"request_hash"`
	AggregateID       uuid.UUID `json:"aggregate_id"`
	CreatedAt         time.Time `json:"created_at"`
}

func (q *Queries) ReserveExternalMutationIdempotency(ctx context.Context, arg ReserveExternalMutationIdempotencyParams) (ExternalMutationIdempotency, error) {
	row := q.db.QueryRow(ctx, reserveExternalMutationIdempotency,
		arg.ID,
		arg.CompanyID,
		arg.ExternalLearnerID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.AggregateID,
		arg.CreatedAt,
	)
	var i ExternalMutationIdempotency
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ExternalLearnerID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.AggregateID,
		&i.ResultID,
		&i.EnrollmentID,
		&i.ResultPayload,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const resolveExternalSessionByTokenHash = `-- name: ResolveExternalSessionByTokenHash :one
SELECT session.id, session.company_id, session.external_learner_id,
    session.token_hash, session.expires_at, session.last_used_at,
    session.revoked_at, session.revocation_reason, session.created_at
FROM external_sessions AS session
JOIN external_learners AS learner
  ON learner.company_id = session.company_id
 AND learner.id = session.external_learner_id
WHERE session.token_hash = $1
  AND session.revoked_at IS NULL
  AND session.expires_at > $2
  AND learner.deleted_at IS NULL
`

type ResolveExternalSessionByTokenHashParams struct {
	TokenHash []byte    `json:"token_hash"`
	Now       time.Time `json:"now"`
}

// Resolve is the only tenant-bootstrap query. token_hash is globally unique;
// every operation after this lookup must use the returned company_id.
func (q *Queries) ResolveExternalSessionByTokenHash(ctx context.Context, arg ResolveExternalSessionByTokenHashParams) (ExternalSession, error) {
	row := q.db.QueryRow(ctx, resolveExternalSessionByTokenHash, arg.TokenHash, arg.Now)
	var i ExternalSession
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ExternalLearnerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
	)
	return i, err
}

const resolveExternalVerificationChallengeForUpdate = `-- name: ResolveExternalVerificationChallengeForUpdate :one
SELECT id, company_id, normalized_email, purpose, source_id,
    claimed_first_name, claimed_last_name, code_hash, request_ip_hash,
    expires_at, attempts, max_attempts, consumed_at, invalidated_at,
    invalidation_reason, created_at
FROM external_verification_challenges
WHERE id = $1
FOR UPDATE
`

// Challenge UUID is returned by the public request-verification endpoint and
// is the tenant bootstrap for confirm. The code still has to be verified in
// constant time by the application before the row can be consumed.
func (q *Queries) ResolveExternalVerificationChallengeForUpdate(ctx context.Context, id uuid.UUID) (ExternalVerificationChallenge, error) {
	row := q.db.QueryRow(ctx, resolveExternalVerificationChallengeForUpdate, id)
	var i ExternalVerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.NormalizedEmail,
		&i.Purpose,
		&i.SourceID,
		&i.ClaimedFirstName,
		&i.ClaimedLastName,
		&i.CodeHash,
		&i.RequestIpHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ConsumedAt,
		&i.InvalidatedAt,
		&i.InvalidationReason,
		&i.CreatedAt,
	)
	return i, err
}

const revokeExpiredExternalSessions = `-- name: RevokeExpiredExternalSessions :many
UPDATE external_sessions AS session
SET revoked_at = session.expires_at,
    revocation_reason = 'expired'
WHERE session.id IN (
    SELECT candidate.id
    FROM external_sessions AS candidate
    WHERE candidate.company_id = $1
      AND candidate.revoked_at IS NULL
      AND candidate.expires_at <= $2
    ORDER BY candidate.expires_at, candidate.id
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING id, company_id, external_learner_id, expires_at, revoked_at,
    revocation_reason, created_at
`

type RevokeExpiredExternalSessionsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Now       time.Time `json:"now"`
	BatchSize int32     `json:"batch_size"`
}

type RevokeExpiredExternalSessionsRow struct {
	ID                uuid.UUID          `json:"id"`
	CompanyID         uuid.UUID          `json:"company_id"`
	ExternalLearnerID uuid.UUID          `json:"external_learner_id"`
	ExpiresAt         time.Time          `json:"expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	RevocationReason  pgtype.Text        `json:"revocation_reason"`
	CreatedAt         time.Time          `json:"created_at"`
}

func (q *Queries) RevokeExpiredExternalSessions(ctx context.Context, arg RevokeExpiredExternalSessionsParams) ([]RevokeExpiredExternalSessionsRow, error) {
	rows, err := q.db.Query(ctx, revokeExpiredExternalSessions, arg.CompanyID, arg.Now, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevokeExpiredExternalSessionsRow{}
	for rows.Next() {
		var i RevokeExpiredExternalSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ExternalLearnerID,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevocationReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeExternalSession = `-- name: RevokeExternalSession :one
UPDATE external_sessions
SET revoked_at = $1,
    revocation_reason = $2
WHERE company_id = $3
  AND id = $4
  AND revoked_at IS NULL
RETURNING id, company_id, external_learner_id, token_hash, expires_at,
    last_used_at, revoked_at, revocation_reason, created_at
`

type RevokeExternalSessionParams struct {
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	RevocationReason pgtype.Text        `json:"revocation_reason"`
	CompanyID        uuid.UUID          `json:"company_id"`
	ID               uuid.UUID          `json:"id"`
}

func (q *Queries) RevokeExternalSession(ctx context.Context, arg RevokeExternalSessionParams) (ExternalSession, error) {
	row := q.db.QueryRow(ctx, revokeExternalSession,
		arg.RevokedAt,
		arg.RevocationReason,
		arg.CompanyID,
		arg.ID,
	)
	var i ExternalSession
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ExternalLearnerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
	)
	return i, err
}

const softDeleteExternalLearner = `-- name: SoftDeleteExternalLearner :execrows
UPDATE external_learners
SET deleted_at = $1,
    updated_at = $1
WHERE company_id = $2
  AND id = $3
  AND deleted_at IS NULL
`

type SoftDeleteExternalLearnerParams struct {
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CompanyID uuid.UUID          `json:"company_id"`
	ID        uuid.UUID          `json:"id"`
}

func (q *Queries) SoftDeleteExternalLearner(ctx context.Context, arg SoftDeleteExternalLearnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteExternalLearner, arg.DeletedAt, arg.CompanyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchExternalSession = `-- name: TouchExternalSession :one
UPDATE external_sessions
SET last_used_at = GREATEST(
        COALESCE(last_used_at, created_at), $1
    )
WHERE company_id = $2
  AND id = $3
  AND revoked_at IS NULL
  AND expires_at > $1
RETURNING id, company_id, external_learner_id, token_hash, expires_at,
    last_used_at, revoked_at, revocation_reason, created_at
`

type TouchExternalSessionParams struct {
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CompanyID  uuid.UUID          `json:"company_id"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) TouchExternalSession(ctx context.Context, arg TouchExternalSessionParams) (ExternalSession, error) {
	row := q.db.QueryRow(ctx, touchExternalSession, arg.LastUsedAt, arg.CompanyID, arg.ID)
	var i ExternalSession
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ExternalLearnerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
	)
	return i, err
}

const upsertExternalLearner = `-- name: UpsertExternalLearner :one
INSERT INTO external_learners (
    id, company_id, email, normalized_email, first_name, last_name, phone,
    email_verified_at, created_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8,
    $9, $10
)
ON CONFLICT (company_id, normalized_email) DO UPDATE
SET email = EXCLUDED.email,
    first_name = EXCLUDED.first_name,
    last_name = COALESCE(EXCLUDED.last_name, external_learners.last_name),
    phone = COALESCE(EXCLUDED.phone, external_learners.phone),
    email_verified_at = COALESCE(
        external_learners.email_verified_at, EXCLUDED.email_verified_at
    ),
    updated_at = EXCLUDED.updated_at,
    deleted_at = NULL
RETURNING id, company_id, email, normalized_email, first_name, last_name,
    phone, email_verified_at, created_at, updated_at, deleted_at
`

type UpsertExternalLearnerParams struct {
	ID              uuid.UUID          `json:"id"`
	CompanyID       uuid.UUID          `json:"company_id"`
	Email           string             `json:"email"`
	NormalizedEmail string             `json:"normalized_email"`
	FirstName       pgtype.Text        `json:"first_name"`
	LastName        pgtype.Text        `json:"last_name"`
	Phone           pgtype.Text        `json:"phone"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) UpsertExternalLearner(ctx context.Context, arg UpsertExternalLearnerParams) (ExternalLearner, error) {
	row := q.db.QueryRow(ctx, upsertExternalLearner,
		arg.ID,
		arg.CompanyID,
		arg.Email,
		arg.NormalizedEmail,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.EmailVerifiedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ExternalLearner
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.NormalizedEmail,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const verifyExternalLearnerEmail = `-- name: VerifyExternalLearnerEmail :one
UPDATE external_learners
SET email_verified_at = COALESCE(email_verified_at, $1),
    updated_at = $1,
    deleted_at = NULL
WHERE company_id = $2
  AND id = $3
RETURNING id, company_id, email, normalized_email, first_name, last_name,
    phone, email_verified_at, created_at, updated_at, deleted_at
`

type VerifyExternalLearnerEmailParams struct {
	VerifiedAt time.Time `json:"verified_at"`
	CompanyID  uuid.UUID `json:"company_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) VerifyExternalLearnerEmail(ctx context.Context, arg VerifyExternalLearnerEmailParams) (ExternalLearner, error) {
	row := q.db.QueryRow(ctx, verifyExternalLearnerEmail, arg.VerifiedAt, arg.CompanyID, arg.ID)
	var i ExternalLearner
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.NormalizedEmail,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
