// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: external_campaign_analytics.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentCampaignAnalyticsByRequestIPHash = `-- name: CountRecentCampaignAnalyticsByRequestIPHash :one
SELECT count(*)::integer
FROM analytics_events
WHERE request_ip_hash_key_id = $1
  AND request_ip_hash = $2
  AND occurred_at >= $3
`

type CountRecentCampaignAnalyticsByRequestIPHashParams struct {
	RequestIpHashKeyID pgtype.Text `json:"request_ip_hash_key_id"`
	RequestIpHash      []byte      `json:"request_ip_hash"`
	Since              time.Time   `json:"since"`
}

func (q *Queries) CountRecentCampaignAnalyticsByRequestIPHash(ctx context.Context, arg CountRecentCampaignAnalyticsByRequestIPHashParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRecentCampaignAnalyticsByRequestIPHash, arg.RequestIpHashKeyID, arg.RequestIpHash, arg.Since)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getExternalCampaignAttributionByEnrollment = `-- name: GetExternalCampaignAttributionByEnrollment :one
SELECT visitor_hash, utm_source, utm_medium, utm_campaign, utm_term,
    utm_content, referrer
FROM analytics_events
WHERE company_id = $1
  AND campaign_id = $2
  AND enrollment_id = $3
  AND (visitor_hash IS NOT NULL OR utm_source IS NOT NULL
       OR utm_medium IS NOT NULL OR utm_campaign IS NOT NULL
       OR utm_term IS NOT NULL OR utm_content IS NOT NULL
       OR referrer IS NOT NULL)
ORDER BY occurred_at DESC, id DESC
LIMIT 1
`

type GetExternalCampaignAttributionByEnrollmentParams struct {
	CompanyID    uuid.UUID     `json:"company_id"`
	CampaignID   uuid.UUID     `json:"campaign_id"`
	EnrollmentID uuid.NullUUID `json:"enrollment_id"`
}

type GetExternalCampaignAttributionByEnrollmentRow struct {
	VisitorHash []byte      `json:"visitor_hash"`
	UtmSource   pgtype.Text `json:"utm_source"`
	UtmMedium   pgtype.Text `json:"utm_medium"`
	UtmCampaign pgtype.Text `json:"utm_campaign"`
	UtmTerm     pgtype.Text `json:"utm_term"`
	UtmContent  pgtype.Text `json:"utm_content"`
	Referrer    pgtype.Text `json:"referrer"`
}

func (q *Queries) GetExternalCampaignAttributionByEnrollment(ctx context.Context, arg GetExternalCampaignAttributionByEnrollmentParams) (GetExternalCampaignAttributionByEnrollmentRow, error) {
	row := q.db.QueryRow(ctx, getExternalCampaignAttributionByEnrollment, arg.CompanyID, arg.CampaignID, arg.EnrollmentID)
	var i GetExternalCampaignAttributionByEnrollmentRow
	err := row.Scan(
		&i.VisitorHash,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.UtmTerm,
		&i.UtmContent,
		&i.Referrer,
	)
	return i, err
}

const getExternalCampaignAttributionByVisitorHash = `-- name: GetExternalCampaignAttributionByVisitorHash :one
SELECT utm_source, utm_medium, utm_campaign, utm_term, utm_content,
    referrer
FROM analytics_events
WHERE company_id = $1
  AND campaign_id = $2
  AND visitor_hash = $3
  AND event_type IN ('landing_viewed', 'return_visit')
ORDER BY occurred_at DESC, id DESC
LIMIT 1
`

type GetExternalCampaignAttributionByVisitorHashParams struct {
	CompanyID   uuid.UUID `json:"company_id"`
	CampaignID  uuid.UUID `json:"campaign_id"`
	VisitorHash []byte    `json:"visitor_hash"`
}

type GetExternalCampaignAttributionByVisitorHashRow struct {
	UtmSource   pgtype.Text `json:"utm_source"`
	UtmMedium   pgtype.Text `json:"utm_medium"`
	UtmCampaign pgtype.Text `json:"utm_campaign"`
	UtmTerm     pgtype.Text `json:"utm_term"`
	UtmContent  pgtype.Text `json:"utm_content"`
	Referrer    pgtype.Text `json:"referrer"`
}

func (q *Queries) GetExternalCampaignAttributionByVisitorHash(ctx context.Context, arg GetExternalCampaignAttributionByVisitorHashParams) (GetExternalCampaignAttributionByVisitorHashRow, error) {
	row := q.db.QueryRow(ctx, getExternalCampaignAttributionByVisitorHash, arg.CompanyID, arg.CampaignID, arg.VisitorHash)
	var i GetExternalCampaignAttributionByVisitorHashRow
	err := row.Scan(
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.UtmTerm,
		&i.UtmContent,
		&i.Referrer,
	)
	return i, err
}

const insertExternalCampaignAnalyticsEvent = `-- name: InsertExternalCampaignAnalyticsEvent :one
INSERT INTO analytics_events (
    id, company_id, campaign_id, enrollment_id, external_learner_id,
    event_type, event_idempotency_key, request_hash,
    visitor_hash, visitor_hash_key_id,
    request_ip_hash, request_ip_hash_key_id,
    utm_source, utm_medium, utm_campaign, utm_term, utm_content,
    referrer, lesson_version_id, progress_percent, completion_seconds,
    metadata, occurred_at, received_at
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9,
    $10, $11,
    $12, $13,
    $14, $15, $16,
    $17, $18,
    $19, $20,
    $21, $22,
    $23, $24
)
ON CONFLICT (company_id, campaign_id, event_idempotency_key)
DO UPDATE SET id = analytics_events.id
RETURNING id, company_id, campaign_id, enrollment_id,
    external_learner_id, event_type, event_idempotency_key, request_hash,
    visitor_hash, visitor_hash_key_id, request_ip_hash,
    request_ip_hash_key_id, utm_source, utm_medium, utm_campaign,
    utm_term, utm_content, referrer, lesson_version_id,
    progress_percent, completion_seconds, metadata, occurred_at,
    received_at
`

type InsertExternalCampaignAnalyticsEventParams struct {
	ID                  uuid.UUID     `json:"id"`
	CompanyID           uuid.UUID     `json:"company_id"`
	CampaignID          uuid.UUID     `json:"campaign_id"`
	EnrollmentID        uuid.NullUUID `json:"enrollment_id"`
	ExternalLearnerID   uuid.NullUUID `json:"external_learner_id"`
	EventType           string        `json:"event_type"`
	EventIdempotencyKey string        `json:"event_idempotency_key"`
	RequestHash         string        `json:"request_hash"`
	VisitorHash         []byte        `json:"visitor_hash"`
	VisitorHashKeyID    pgtype.Text   `json:"visitor_hash_key_id"`
	RequestIpHash       []byte        `json:"request_ip_hash"`
	RequestIpHashKeyID  pgtype.Text   `json:"request_ip_hash_key_id"`
	UtmSource           pgtype.Text   `json:"utm_source"`
	UtmMedium           pgtype.Text   `json:"utm_medium"`
	UtmCampaign         pgtype.Text   `json:"utm_campaign"`
	UtmTerm             pgtype.Text   `json:"utm_term"`
	UtmContent          pgtype.Text   `json:"utm_content"`
	Referrer            pgtype.Text   `json:"referrer"`
	LessonVersionID     uuid.NullUUID `json:"lesson_version_id"`
	ProgressPercent     pgtype.Int2   `json:"progress_percent"`
	CompletionSeconds   pgtype.Int8   `json:"completion_seconds"`
	Metadata            []byte        `json:"metadata"`
	OccurredAt          time.Time     `json:"occurred_at"`
	ReceivedAt          time.Time     `json:"received_at"`
}

func (q *Queries) InsertExternalCampaignAnalyticsEvent(ctx context.Context, arg InsertExternalCampaignAnalyticsEventParams) (AnalyticsEvent, error) {
	row := q.db.QueryRow(ctx, insertExternalCampaignAnalyticsEvent,
		arg.ID,
		arg.CompanyID,
		arg.CampaignID,
		arg.EnrollmentID,
		arg.ExternalLearnerID,
		arg.EventType,
		arg.EventIdempotencyKey,
		arg.RequestHash,
		arg.VisitorHash,
		arg.VisitorHashKeyID,
		arg.RequestIpHash,
		arg.RequestIpHashKeyID,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
		arg.UtmTerm,
		arg.UtmContent,
		arg.Referrer,
		arg.LessonVersionID,
		arg.ProgressPercent,
		arg.CompletionSeconds,
		arg.Metadata,
		arg.OccurredAt,
		arg.ReceivedAt,
	)
	var i AnalyticsEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CampaignID,
		&i.EnrollmentID,
		&i.ExternalLearnerID,
		&i.EventType,
		&i.EventIdempotencyKey,
		&i.RequestHash,
		&i.VisitorHash,
		&i.VisitorHashKeyID,
		&i.RequestIpHash,
		&i.RequestIpHashKeyID,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.UtmTerm,
		&i.UtmContent,
		&i.Referrer,
		&i.LessonVersionID,
		&i.ProgressPercent,
		&i.CompletionSeconds,
		&i.Metadata,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}

const listExternalCampaignAnalyticsEvents = `-- name: ListExternalCampaignAnalyticsEvents :many
SELECT id, company_id, campaign_id, enrollment_id,
    external_learner_id, event_type, event_idempotency_key,
    visitor_hash, visitor_hash_key_id, utm_source, utm_medium,
    utm_campaign, utm_term, utm_content, referrer,
    lesson_version_id, progress_percent, completion_seconds,
    metadata, occurred_at, received_at
FROM analytics_events
WHERE company_id = $1
  AND campaign_id = $2
  AND occurred_at >= $3
  AND occurred_at < $4
ORDER BY occurred_at, id
`

type ListExternalCampaignAnalyticsEventsParams struct {
	CompanyID  uuid.UUID `json:"company_id"`
	CampaignID uuid.UUID `json:"campaign_id"`
	FromTime   time.Time `json:"from_time"`
	ToTime     time.Time `json:"to_time"`
}

type ListExternalCampaignAnalyticsEventsRow struct {
	ID                  uuid.UUID     `json:"id"`
	CompanyID           uuid.UUID     `json:"company_id"`
	CampaignID          uuid.UUID     `json:"campaign_id"`
	EnrollmentID        uuid.NullUUID `json:"enrollment_id"`
	ExternalLearnerID   uuid.NullUUID `json:"external_learner_id"`
	EventType           string        `json:"event_type"`
	EventIdempotencyKey string        `json:"event_idempotency_key"`
	VisitorHash         []byte        `json:"visitor_hash"`
	VisitorHashKeyID    pgtype.Text   `json:"visitor_hash_key_id"`
	UtmSource           pgtype.Text   `json:"utm_source"`
	UtmMedium           pgtype.Text   `json:"utm_medium"`
	UtmCampaign         pgtype.Text   `json:"utm_campaign"`
	UtmTerm             pgtype.Text   `json:"utm_term"`
	UtmContent          pgtype.Text   `json:"utm_content"`
	Referrer            pgtype.Text   `json:"referrer"`
	LessonVersionID     uuid.NullUUID `json:"lesson_version_id"`
	ProgressPercent     pgtype.Int2   `json:"progress_percent"`
	CompletionSeconds   pgtype.Int8   `json:"completion_seconds"`
	Metadata            []byte        `json:"metadata"`
	OccurredAt          time.Time     `json:"occurred_at"`
	ReceivedAt          time.Time     `json:"received_at"`
}

func (q *Queries) ListExternalCampaignAnalyticsEvents(ctx context.Context, arg ListExternalCampaignAnalyticsEventsParams) ([]ListExternalCampaignAnalyticsEventsRow, error) {
	rows, err := q.db.Query(ctx, listExternalCampaignAnalyticsEvents,
		arg.CompanyID,
		arg.CampaignID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExternalCampaignAnalyticsEventsRow{}
	for rows.Next() {
		var i ListExternalCampaignAnalyticsEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CampaignID,
			&i.EnrollmentID,
			&i.ExternalLearnerID,
			&i.EventType,
			&i.EventIdempotencyKey,
			&i.VisitorHash,
			&i.VisitorHashKeyID,
			&i.UtmSource,
			&i.UtmMedium,
			&i.UtmCampaign,
			&i.UtmTerm,
			&i.UtmContent,
			&i.Referrer,
			&i.LessonVersionID,
			&i.ProgressPercent,
			&i.CompletionSeconds,
			&i.Metadata,
			&i.OccurredAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalCampaignFunnelDaily = `-- name: ListExternalCampaignFunnelDaily :many
SELECT company_id, campaign_id, bucket_date,
    utm_source, utm_medium, utm_campaign,
    landing_views, unique_visitors, form_submits,
    verification_requests, verified_emails, activations,
    first_lesson_starts, lesson_completions, quiz_submissions,
    course_completions, deadline_expirations, return_visits,
    progress_sum, progress_samples, completion_seconds_sum,
    completion_samples, source_event_count, last_event_at, aggregated_at
FROM external_campaign_funnel_daily
WHERE company_id = $1
  AND campaign_id = $2
  AND bucket_date >= $3
  AND bucket_date <= $4
ORDER BY bucket_date, utm_source, utm_medium, utm_campaign
`

type ListExternalCampaignFunnelDailyParams struct {
	CompanyID  uuid.UUID   `json:"company_id"`
	CampaignID uuid.UUID   `json:"campaign_id"`
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
}

func (q *Queries) ListExternalCampaignFunnelDaily(ctx context.Context, arg ListExternalCampaignFunnelDailyParams) ([]ExternalCampaignFunnelDaily, error) {
	rows, err := q.db.Query(ctx, listExternalCampaignFunnelDaily,
		arg.CompanyID,
		arg.CampaignID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalCampaignFunnelDaily{}
	for rows.Next() {
		var i ExternalCampaignFunnelDaily
		if err := rows.Scan(
			&i.CompanyID,
			&i.CampaignID,
			&i.BucketDate,
			&i.UtmSource,
			&i.UtmMedium,
			&i.UtmCampaign,
			&i.LandingViews,
			&i.UniqueVisitors,
			&i.FormSubmits,
			&i.VerificationRequests,
			&i.VerifiedEmails,
			&i.Activations,
			&i.FirstLessonStarts,
			&i.LessonCompletions,
			&i.QuizSubmissions,
			&i.CourseCompletions,
			&i.DeadlineExpirations,
			&i.ReturnVisits,
			&i.ProgressSum,
			&i.ProgressSamples,
			&i.CompletionSecondsSum,
			&i.CompletionSamples,
			&i.SourceEventCount,
			&i.LastEventAt,
			&i.AggregatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalCampaignIDsForAnalyticsMaintenance = `-- name: ListExternalCampaignIDsForAnalyticsMaintenance :many
SELECT company_id, id AS campaign_id
FROM external_campaigns
ORDER BY company_id, id
`

type ListExternalCampaignIDsForAnalyticsMaintenanceRow struct {
	CompanyID  uuid.UUID `json:"company_id"`
	CampaignID uuid.UUID `json:"campaign_id"`
}

func (q *Queries) ListExternalCampaignIDsForAnalyticsMaintenance(ctx context.Context) ([]ListExternalCampaignIDsForAnalyticsMaintenanceRow, error) {
	rows, err := q.db.Query(ctx, listExternalCampaignIDsForAnalyticsMaintenance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExternalCampaignIDsForAnalyticsMaintenanceRow{}
	for rows.Next() {
		var i ListExternalCampaignIDsForAnalyticsMaintenanceRow
		if err := rows.Scan(&i.CompanyID, &i.CampaignID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalMaintenanceCompanyIDs = `-- name: ListExternalMaintenanceCompanyIDs :many
SELECT company_id
FROM (
    SELECT company_id FROM course_enrollments WHERE learner_type = 'external'
    UNION
    SELECT company_id FROM external_verification_challenges
) AS companies
ORDER BY company_id
`

func (q *Queries) ListExternalMaintenanceCompanyIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listExternalMaintenanceCompanyIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var company_id uuid.UUID
		if err := rows.Scan(&company_id); err != nil {
			return nil, err
		}
		items = append(items, company_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebuildExternalCampaignFunnelDaily = `-- name: RebuildExternalCampaignFunnelDaily :many
WITH dimensions AS (
    SELECT event.company_id, event.campaign_id,
           (event.occurred_at AT TIME ZONE 'UTC')::date AS bucket_date,
           COALESCE(event.utm_source, '') AS utm_source,
           COALESCE(event.utm_medium, '') AS utm_medium,
           COALESCE(event.utm_campaign, '') AS utm_campaign,
           count(*) FILTER (WHERE event.event_type = 'landing_viewed')::bigint
               AS landing_views,
           count(DISTINCT event.visitor_hash) FILTER (
               WHERE event.visitor_hash IS NOT NULL
           )::bigint AS unique_visitors,
           count(*) FILTER (WHERE event.event_type = 'form_submitted')::bigint
               AS form_submits,
           count(*) FILTER (
               WHERE event.event_type = 'verification_requested'
           )::bigint AS verification_requests,
           count(*) FILTER (WHERE event.event_type = 'email_verified')::bigint
               AS verified_emails,
           count(*) FILTER (WHERE event.event_type = 'course_activated')::bigint
               AS activations,
           count(*) FILTER (
               WHERE event.event_type = 'first_lesson_started'
           )::bigint AS first_lesson_starts,
           count(*) FILTER (WHERE event.event_type = 'lesson_completed')::bigint
               AS lesson_completions,
           count(*) FILTER (WHERE event.event_type = 'quiz_submitted')::bigint
               AS quiz_submissions,
           count(*) FILTER (WHERE event.event_type = 'course_completed')::bigint
               AS course_completions,
           count(*) FILTER (WHERE event.event_type = 'deadline_expired')::bigint
               AS deadline_expirations,
           count(*) FILTER (WHERE event.event_type = 'return_visit')::bigint
               AS return_visits,
           COALESCE(sum(event.progress_percent), 0)::bigint AS progress_sum,
           count(event.progress_percent)::bigint AS progress_samples,
           COALESCE(sum(event.completion_seconds), 0)::numeric(30, 0)
               AS completion_seconds_sum,
           count(event.completion_seconds)::bigint AS completion_samples,
           count(*)::bigint AS source_event_count,
           max(event.occurred_at) AS last_event_at
    FROM analytics_events AS event
    WHERE event.company_id = $1
      AND event.campaign_id = $2
      AND event.occurred_at >= $3
      AND event.occurred_at < $4
    GROUP BY event.company_id, event.campaign_id,
        (event.occurred_at AT TIME ZONE 'UTC')::date,
        COALESCE(event.utm_source, ''), COALESCE(event.utm_medium, ''),
        COALESCE(event.utm_campaign, '')
), upserted AS (
    INSERT INTO external_campaign_funnel_daily (
        company_id, campaign_id, bucket_date,
        utm_source, utm_medium, utm_campaign,
        landing_views, unique_visitors, form_submits,
        verification_requests, verified_emails, activations,
        first_lesson_starts, lesson_completions, quiz_submissions,
        course_completions, deadline_expirations, return_visits,
        progress_sum, progress_samples,
        completion_seconds_sum, completion_samples,
        source_event_count, last_event_at, aggregated_at
    )
    SELECT dimensions.company_id, dimensions.campaign_id,
           dimensions.bucket_date, dimensions.utm_source,
           dimensions.utm_medium, dimensions.utm_campaign,
           dimensions.landing_views, dimensions.unique_visitors,
           dimensions.form_submits, dimensions.verification_requests,
           dimensions.verified_emails, dimensions.activations,
           dimensions.first_lesson_starts, dimensions.lesson_completions,
           dimensions.quiz_submissions, dimensions.course_completions,
           dimensions.deadline_expirations, dimensions.return_visits,
           dimensions.progress_sum, dimensions.progress_samples,
           dimensions.completion_seconds_sum,
           dimensions.completion_samples, dimensions.source_event_count,
           dimensions.last_event_at, $5
    FROM dimensions
    ON CONFLICT (
        company_id, campaign_id, bucket_date,
        utm_source, utm_medium, utm_campaign
    ) DO UPDATE SET
        landing_views = EXCLUDED.landing_views,
        unique_visitors = EXCLUDED.unique_visitors,
        form_submits = EXCLUDED.form_submits,
        verification_requests = EXCLUDED.verification_requests,
        verified_emails = EXCLUDED.verified_emails,
        activations = EXCLUDED.activations,
        first_lesson_starts = EXCLUDED.first_lesson_starts,
        lesson_completions = EXCLUDED.lesson_completions,
        quiz_submissions = EXCLUDED.quiz_submissions,
        course_completions = EXCLUDED.course_completions,
        deadline_expirations = EXCLUDED.deadline_expirations,
        return_visits = EXCLUDED.return_visits,
        progress_sum = EXCLUDED.progress_sum,
        progress_samples = EXCLUDED.progress_samples,
        completion_seconds_sum = EXCLUDED.completion_seconds_sum,
        completion_samples = EXCLUDED.completion_samples,
        source_event_count = EXCLUDED.source_event_count,
        last_event_at = EXCLUDED.last_event_at,
        aggregated_at = EXCLUDED.aggregated_at
    RETURNING company_id, campaign_id, bucket_date,
        utm_source, utm_medium, utm_campaign,
        landing_views, unique_visitors, form_submits,
        verification_requests, verified_emails, activations,
        first_lesson_starts, lesson_completions, quiz_submissions,
        course_completions, deadline_expirations, return_visits,
        progress_sum, progress_samples, completion_seconds_sum,
        completion_samples, source_event_count, last_event_at, aggregated_at
)
SELECT company_id, campaign_id, bucket_date, utm_source, utm_medium, utm_campaign, landing_views, unique_visitors, form_submits, verification_requests, verified_emails, activations, first_lesson_starts, lesson_completions, quiz_submissions, course_completions, deadline_expirations, return_visits, progress_sum, progress_samples, completion_seconds_sum, completion_samples, source_event_count, last_event_at, aggregated_at FROM upserted
ORDER BY bucket_date, utm_source, utm_medium, utm_campaign
`

type RebuildExternalCampaignFunnelDailyParams struct {
	CompanyID    uuid.UUID `json:"company_id"`
	CampaignID   uuid.UUID `json:"campaign_id"`
	FromTime     time.Time `json:"from_time"`
	ToTime       time.Time `json:"to_time"`
	AggregatedAt time.Time `json:"aggregated_at"`
}

type RebuildExternalCampaignFunnelDailyRow struct {
	CompanyID            uuid.UUID          `json:"company_id"`
	CampaignID           uuid.UUID          `json:"campaign_id"`
	BucketDate           pgtype.Date        `json:"bucket_date"`
	UtmSource            string             `json:"utm_source"`
	UtmMedium            string             `json:"utm_medium"`
	UtmCampaign          string             `json:"utm_campaign"`
	LandingViews         int64              `json:"landing_views"`
	UniqueVisitors       int64              `json:"unique_visitors"`
	FormSubmits          int64              `json:"form_submits"`
	VerificationRequests int64              `json:"verification_requests"`
	VerifiedEmails       int64              `json:"verified_emails"`
	Activations          int64              `json:"activations"`
	FirstLessonStarts    int64              `json:"first_lesson_starts"`
	LessonCompletions    int64              `json:"lesson_completions"`
	QuizSubmissions      int64              `json:"quiz_submissions"`
	CourseCompletions    int64              `json:"course_completions"`
	DeadlineExpirations  int64              `json:"deadline_expirations"`
	ReturnVisits         int64              `json:"return_visits"`
	ProgressSum          int64              `json:"progress_sum"`
	ProgressSamples      int64              `json:"progress_samples"`
	CompletionSecondsSum pgtype.Numeric     `json:"completion_seconds_sum"`
	CompletionSamples    int64              `json:"completion_samples"`
	SourceEventCount     int64              `json:"source_event_count"`
	LastEventAt          pgtype.Timestamptz `json:"last_event_at"`
	AggregatedAt         time.Time          `json:"aggregated_at"`
}

func (q *Queries) RebuildExternalCampaignFunnelDaily(ctx context.Context, arg RebuildExternalCampaignFunnelDailyParams) ([]RebuildExternalCampaignFunnelDailyRow, error) {
	rows, err := q.db.Query(ctx, rebuildExternalCampaignFunnelDaily,
		arg.CompanyID,
		arg.CampaignID,
		arg.FromTime,
		arg.ToTime,
		arg.AggregatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RebuildExternalCampaignFunnelDailyRow{}
	for rows.Next() {
		var i RebuildExternalCampaignFunnelDailyRow
		if err := rows.Scan(
			&i.CompanyID,
			&i.CampaignID,
			&i.BucketDate,
			&i.UtmSource,
			&i.UtmMedium,
			&i.UtmCampaign,
			&i.LandingViews,
			&i.UniqueVisitors,
			&i.FormSubmits,
			&i.VerificationRequests,
			&i.VerifiedEmails,
			&i.Activations,
			&i.FirstLessonStarts,
			&i.LessonCompletions,
			&i.QuizSubmissions,
			&i.CourseCompletions,
			&i.DeadlineExpirations,
			&i.ReturnVisits,
			&i.ProgressSum,
			&i.ProgressSamples,
			&i.CompletionSecondsSum,
			&i.CompletionSamples,
			&i.SourceEventCount,
			&i.LastEventAt,
			&i.AggregatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExternalCampaignFunnelDaily = `-- name: UpsertExternalCampaignFunnelDaily :one
INSERT INTO external_campaign_funnel_daily (
    company_id, campaign_id, bucket_date,
    utm_source, utm_medium, utm_campaign,
    landing_views, unique_visitors, form_submits,
    verification_requests, verified_emails, activations,
    first_lesson_starts, lesson_completions, quiz_submissions,
    course_completions, deadline_expirations, return_visits,
    progress_sum, progress_samples,
    completion_seconds_sum, completion_samples,
    source_event_count, last_event_at, aggregated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8,
    $9, $10,
    $11, $12,
    $13, $14,
    $15, $16,
    $17, $18,
    $19, $20,
    $21, $22,
    $23, $24,
    $25
)
ON CONFLICT (
    company_id, campaign_id, bucket_date,
    utm_source, utm_medium, utm_campaign
) DO UPDATE SET
    landing_views = EXCLUDED.landing_views,
    unique_visitors = EXCLUDED.unique_visitors,
    form_submits = EXCLUDED.form_submits,
    verification_requests = EXCLUDED.verification_requests,
    verified_emails = EXCLUDED.verified_emails,
    activations = EXCLUDED.activations,
    first_lesson_starts = EXCLUDED.first_lesson_starts,
    lesson_completions = EXCLUDED.lesson_completions,
    quiz_submissions = EXCLUDED.quiz_submissions,
    course_completions = EXCLUDED.course_completions,
    deadline_expirations = EXCLUDED.deadline_expirations,
    return_visits = EXCLUDED.return_visits,
    progress_sum = EXCLUDED.progress_sum,
    progress_samples = EXCLUDED.progress_samples,
    completion_seconds_sum = EXCLUDED.completion_seconds_sum,
    completion_samples = EXCLUDED.completion_samples,
    source_event_count = EXCLUDED.source_event_count,
    last_event_at = EXCLUDED.last_event_at,
    aggregated_at = EXCLUDED.aggregated_at
RETURNING company_id, campaign_id, bucket_date,
    utm_source, utm_medium, utm_campaign,
    landing_views, unique_visitors, form_submits,
    verification_requests, verified_emails, activations,
    first_lesson_starts, lesson_completions, quiz_submissions,
    course_completions, deadline_expirations, return_visits,
    progress_sum, progress_samples, completion_seconds_sum,
    completion_samples, source_event_count, last_event_at, aggregated_at
`

type UpsertExternalCampaignFunnelDailyParams struct {
	CompanyID            uuid.UUID          `json:"company_id"`
	CampaignID           uuid.UUID          `json:"campaign_id"`
	BucketDate           pgtype.Date        `json:"bucket_date"`
	UtmSource            string             `json:"utm_source"`
	UtmMedium            string             `json:"utm_medium"`
	UtmCampaign          string             `json:"utm_campaign"`
	LandingViews         int64              `json:"landing_views"`
	UniqueVisitors       int64              `json:"unique_visitors"`
	FormSubmits          int64              `json:"form_submits"`
	VerificationRequests int64              `json:"verification_requests"`
	VerifiedEmails       int64              `json:"verified_emails"`
	Activations          int64              `json:"activations"`
	FirstLessonStarts    int64              `json:"first_lesson_starts"`
	LessonCompletions    int64              `json:"lesson_completions"`
	QuizSubmissions      int64              `json:"quiz_submissions"`
	CourseCompletions    int64              `json:"course_completions"`
	DeadlineExpirations  int64              `json:"deadline_expirations"`
	ReturnVisits         int64              `json:"return_visits"`
	ProgressSum          int64              `json:"progress_sum"`
	ProgressSamples      int64              `json:"progress_samples"`
	CompletionSecondsSum pgtype.Numeric     `json:"completion_seconds_sum"`
	CompletionSamples    int64              `json:"completion_samples"`
	SourceEventCount     int64              `json:"source_event_count"`
	LastEventAt          pgtype.Timestamptz `json:"last_event_at"`
	AggregatedAt         time.Time          `json:"aggregated_at"`
}

// Worker-owned exact replacement/upsert for one day and UTM slice. The
// source_event_count lets the worker cheaply detect stale aggregates.
func (q *Queries) UpsertExternalCampaignFunnelDaily(ctx context.Context, arg UpsertExternalCampaignFunnelDailyParams) (ExternalCampaignFunnelDaily, error) {
	row := q.db.QueryRow(ctx, upsertExternalCampaignFunnelDaily,
		arg.CompanyID,
		arg.CampaignID,
		arg.BucketDate,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
		arg.LandingViews,
		arg.UniqueVisitors,
		arg.FormSubmits,
		arg.VerificationRequests,
		arg.VerifiedEmails,
		arg.Activations,
		arg.FirstLessonStarts,
		arg.LessonCompletions,
		arg.QuizSubmissions,
		arg.CourseCompletions,
		arg.DeadlineExpirations,
		arg.ReturnVisits,
		arg.ProgressSum,
		arg.ProgressSamples,
		arg.CompletionSecondsSum,
		arg.CompletionSamples,
		arg.SourceEventCount,
		arg.LastEventAt,
		arg.AggregatedAt,
	)
	var i ExternalCampaignFunnelDaily
	err := row.Scan(
		&i.CompanyID,
		&i.CampaignID,
		&i.BucketDate,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.LandingViews,
		&i.UniqueVisitors,
		&i.FormSubmits,
		&i.VerificationRequests,
		&i.VerifiedEmails,
		&i.Activations,
		&i.FirstLessonStarts,
		&i.LessonCompletions,
		&i.QuizSubmissions,
		&i.CourseCompletions,
		&i.DeadlineExpirations,
		&i.ReturnVisits,
		&i.ProgressSum,
		&i.ProgressSamples,
		&i.CompletionSecondsSum,
		&i.CompletionSamples,
		&i.SourceEventCount,
		&i.LastEventAt,
		&i.AggregatedAt,
	)
	return i, err
}
