// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kb_snapshots.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createKBArticleSnapshot = `-- name: CreateKBArticleSnapshot :one
INSERT INTO kb_article_snapshots (
    id, company_id, source_article_id, source_article_version_id,
    source_article_version_number, reuse_grant_id, requested_by_id,
    requested_by_partner_id, request_key, title, content, source_file_ids,
    content_hash, created_at
) VALUES (
    $1, $2, $3,
    $4,
    $5, $6,
    $7, $8,
    $9, $10, $11,
    $12, $13, $14
)
ON CONFLICT (company_id, request_key) DO NOTHING
RETURNING id, company_id, source_article_id, source_article_version_id,
    source_article_version_number, reuse_grant_id, requested_by_id,
    requested_by_partner_id, request_key, title, content, source_file_ids,
    content_hash, created_at
`

type CreateKBArticleSnapshotParams struct {
	ID                         uuid.UUID     `json:"id"`
	CompanyID                  uuid.UUID     `json:"company_id"`
	SourceArticleID            uuid.UUID     `json:"source_article_id"`
	SourceArticleVersionID     uuid.NullUUID `json:"source_article_version_id"`
	SourceArticleVersionNumber pgtype.Int4   `json:"source_article_version_number"`
	ReuseGrantID               uuid.NullUUID `json:"reuse_grant_id"`
	RequestedByID              uuid.UUID     `json:"requested_by_id"`
	RequestedByPartnerID       uuid.NullUUID `json:"requested_by_partner_id"`
	RequestKey                 string        `json:"request_key"`
	Title                      string        `json:"title"`
	Content                    []byte        `json:"content"`
	SourceFileIds              []uuid.UUID   `json:"source_file_ids"`
	ContentHash                string        `json:"content_hash"`
	CreatedAt                  time.Time     `json:"created_at"`
}

func (q *Queries) CreateKBArticleSnapshot(ctx context.Context, arg CreateKBArticleSnapshotParams) (KbArticleSnapshot, error) {
	row := q.db.QueryRow(ctx, createKBArticleSnapshot,
		arg.ID,
		arg.CompanyID,
		arg.SourceArticleID,
		arg.SourceArticleVersionID,
		arg.SourceArticleVersionNumber,
		arg.ReuseGrantID,
		arg.RequestedByID,
		arg.RequestedByPartnerID,
		arg.RequestKey,
		arg.Title,
		arg.Content,
		arg.SourceFileIds,
		arg.ContentHash,
		arg.CreatedAt,
	)
	var i KbArticleSnapshot
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SourceArticleID,
		&i.SourceArticleVersionID,
		&i.SourceArticleVersionNumber,
		&i.ReuseGrantID,
		&i.RequestedByID,
		&i.RequestedByPartnerID,
		&i.RequestKey,
		&i.Title,
		&i.Content,
		&i.SourceFileIds,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const getKBArticleSnapshot = `-- name: GetKBArticleSnapshot :one
SELECT id, company_id, source_article_id, source_article_version_id,
    source_article_version_number, reuse_grant_id, requested_by_id,
    requested_by_partner_id, request_key, title, content, source_file_ids,
    content_hash, created_at
FROM kb_article_snapshots
WHERE company_id = $1 AND id = $2
`

type GetKBArticleSnapshotParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetKBArticleSnapshot(ctx context.Context, arg GetKBArticleSnapshotParams) (KbArticleSnapshot, error) {
	row := q.db.QueryRow(ctx, getKBArticleSnapshot, arg.CompanyID, arg.ID)
	var i KbArticleSnapshot
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SourceArticleID,
		&i.SourceArticleVersionID,
		&i.SourceArticleVersionNumber,
		&i.ReuseGrantID,
		&i.RequestedByID,
		&i.RequestedByPartnerID,
		&i.RequestKey,
		&i.Title,
		&i.Content,
		&i.SourceFileIds,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const getKBArticleSnapshotByRequestKey = `-- name: GetKBArticleSnapshotByRequestKey :one
SELECT id, company_id, source_article_id, source_article_version_id,
    source_article_version_number, reuse_grant_id, requested_by_id,
    requested_by_partner_id, request_key, title, content, source_file_ids,
    content_hash, created_at
FROM kb_article_snapshots
WHERE company_id = $1
  AND request_key = $2
`

type GetKBArticleSnapshotByRequestKeyParams struct {
	CompanyID  uuid.UUID `json:"company_id"`
	RequestKey string    `json:"request_key"`
}

func (q *Queries) GetKBArticleSnapshotByRequestKey(ctx context.Context, arg GetKBArticleSnapshotByRequestKeyParams) (KbArticleSnapshot, error) {
	row := q.db.QueryRow(ctx, getKBArticleSnapshotByRequestKey, arg.CompanyID, arg.RequestKey)
	var i KbArticleSnapshot
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SourceArticleID,
		&i.SourceArticleVersionID,
		&i.SourceArticleVersionNumber,
		&i.ReuseGrantID,
		&i.RequestedByID,
		&i.RequestedByPartnerID,
		&i.RequestKey,
		&i.Title,
		&i.Content,
		&i.SourceFileIds,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const listKBArticleSnapshotsBySource = `-- name: ListKBArticleSnapshotsBySource :many
SELECT id, company_id, source_article_id, source_article_version_id,
    source_article_version_number, reuse_grant_id, requested_by_id,
    requested_by_partner_id, request_key, title, content, source_file_ids,
    content_hash, created_at
FROM kb_article_snapshots
WHERE company_id = $1
  AND source_article_id = $2
ORDER BY created_at DESC, id
`

type ListKBArticleSnapshotsBySourceParams struct {
	CompanyID       uuid.UUID `json:"company_id"`
	SourceArticleID uuid.UUID `json:"source_article_id"`
}

func (q *Queries) ListKBArticleSnapshotsBySource(ctx context.Context, arg ListKBArticleSnapshotsBySourceParams) ([]KbArticleSnapshot, error) {
	rows, err := q.db.Query(ctx, listKBArticleSnapshotsBySource, arg.CompanyID, arg.SourceArticleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbArticleSnapshot{}
	for rows.Next() {
		var i KbArticleSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SourceArticleID,
			&i.SourceArticleVersionID,
			&i.SourceArticleVersionNumber,
			&i.ReuseGrantID,
			&i.RequestedByID,
			&i.RequestedByPartnerID,
			&i.RequestKey,
			&i.Title,
			&i.Content,
			&i.SourceFileIds,
			&i.ContentHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
