// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Assignment struct {
	ID              uuid.UUID          `json:"id"`
	CompanyID       uuid.UUID          `json:"company_id"`
	CourseID        uuid.UUID          `json:"course_id"`
	AssigneeType    string             `json:"assignee_type"`
	AssigneeID      uuid.NullUUID      `json:"assignee_id"`
	InviteToken     pgtype.Text        `json:"invite_token"`
	DueDate         pgtype.Timestamptz `json:"due_date"`
	ResolvedUserIds []uuid.UUID        `json:"resolved_user_ids"`
	DueSoonSentAt   pgtype.Timestamptz `json:"due_soon_sent_at"`
	AssignedByID    uuid.UUID          `json:"assigned_by_id"`
	CreatedAt       time.Time          `json:"created_at"`
}

type Course struct {
	ID           uuid.UUID   `json:"id"`
	CompanyID    uuid.UUID   `json:"company_id"`
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	CoverUrl     pgtype.Text `json:"cover_url"`
	Status       string      `json:"status"`
	AuthorID     uuid.UUID   `json:"author_id"`
	Sequential   bool        `json:"sequential"`
	DeadlineDays pgtype.Int4 `json:"deadline_days"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type CourseSection struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	CourseID  uuid.UUID `json:"course_id"`
	Title     string    `json:"title"`
	Order     int32     `json:"order"`
}

type Lesson struct {
	ID                 uuid.UUID     `json:"id"`
	CompanyID          uuid.UUID     `json:"company_id"`
	CourseID           uuid.UUID     `json:"course_id"`
	SectionID          uuid.UUID     `json:"section_id"`
	Title              string        `json:"title"`
	Order              int32         `json:"order"`
	Content            []byte        `json:"content"`
	SourceArticleID    uuid.NullUUID `json:"source_article_id"`
	SourceArticleTitle pgtype.Text   `json:"source_article_title"`
	SourceMode         pgtype.Text   `json:"source_mode"`
	QuizID             uuid.NullUUID `json:"quiz_id"`
}

type Outbox struct {
	ID            uuid.UUID          `json:"id"`
	CompanyID     uuid.UUID          `json:"company_id"`
	Subject       string             `json:"subject"`
	Payload       []byte             `json:"payload"`
	Headers       []byte             `json:"headers"`
	OccurredAt    time.Time          `json:"occurred_at"`
	NextAttemptAt time.Time          `json:"next_attempt_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	Attempts      int32              `json:"attempts"`
	LastError     pgtype.Text        `json:"last_error"`
}

type ProcessedEvent struct {
	EventID     uuid.UUID `json:"event_id"`
	CompanyID   uuid.UUID `json:"company_id"`
	ProcessedAt time.Time `json:"processed_at"`
}

type Progress struct {
	CompanyID          uuid.UUID          `json:"company_id"`
	UserID             uuid.UUID          `json:"user_id"`
	CourseID           uuid.UUID          `json:"course_id"`
	Status             string             `json:"status"`
	CompletedLessonIds []uuid.UUID        `json:"completed_lesson_ids"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}

type Quiz struct {
	ID           uuid.UUID   `json:"id"`
	CompanyID    uuid.UUID   `json:"company_id"`
	LessonID     uuid.UUID   `json:"lesson_id"`
	Questions    []byte      `json:"questions"`
	PassingScore int32       `json:"passing_score"`
	MaxAttempts  pgtype.Int4 `json:"max_attempts"`
}

type QuizAttempt struct {
	ID            uuid.UUID `json:"id"`
	CompanyID     uuid.UUID `json:"company_id"`
	QuizID        uuid.UUID `json:"quiz_id"`
	UserID        uuid.UUID `json:"user_id"`
	Score         int32     `json:"score"`
	Passed        bool      `json:"passed"`
	PendingReview bool      `json:"pending_review"`
	CreatedAt     time.Time `json:"created_at"`
}
