// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quizzes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quizzes (id, company_id, lesson_id, questions, passing_score, max_attempts)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, lesson_id, questions, passing_score, max_attempts
`

type CreateQuizParams struct {
	ID           uuid.UUID   `json:"id"`
	CompanyID    uuid.UUID   `json:"company_id"`
	LessonID     uuid.UUID   `json:"lesson_id"`
	Questions    []byte      `json:"questions"`
	PassingScore int32       `json:"passing_score"`
	MaxAttempts  pgtype.Int4 `json:"max_attempts"`
}

func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, createQuiz,
		arg.ID,
		arg.CompanyID,
		arg.LessonID,
		arg.Questions,
		arg.PassingScore,
		arg.MaxAttempts,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.LessonID,
		&i.Questions,
		&i.PassingScore,
		&i.MaxAttempts,
	)
	return i, err
}

const getLessonQuizzes = `-- name: GetLessonQuizzes :many
SELECT id, company_id, lesson_id, questions, passing_score, max_attempts
FROM quizzes
WHERE company_id = $1 AND lesson_id = $2
ORDER BY id
`

type GetLessonQuizzesParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	LessonID  uuid.UUID `json:"lesson_id"`
}

func (q *Queries) GetLessonQuizzes(ctx context.Context, arg GetLessonQuizzesParams) ([]Quiz, error) {
	rows, err := q.db.Query(ctx, getLessonQuizzes, arg.CompanyID, arg.LessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quiz{}
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.LessonID,
			&i.Questions,
			&i.PassingScore,
			&i.MaxAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuiz = `-- name: GetQuiz :one
SELECT id, company_id, lesson_id, questions, passing_score, max_attempts
FROM quizzes
WHERE company_id = $1 AND id = $2
`

type GetQuizParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetQuiz(ctx context.Context, arg GetQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, getQuiz, arg.CompanyID, arg.ID)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.LessonID,
		&i.Questions,
		&i.PassingScore,
		&i.MaxAttempts,
	)
	return i, err
}

const getQuizAttempts = `-- name: GetQuizAttempts :many
SELECT id, company_id, quiz_id, user_id, score, passed, pending_review, created_at
FROM quiz_attempts
WHERE company_id = $1
ORDER BY created_at, id
`

func (q *Queries) GetQuizAttempts(ctx context.Context, companyID uuid.UUID) ([]QuizAttempt, error) {
	rows, err := q.db.Query(ctx, getQuizAttempts, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuizAttempt{}
	for rows.Next() {
		var i QuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.QuizID,
			&i.UserID,
			&i.Score,
			&i.Passed,
			&i.PendingReview,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuizAttemptsWithCourse = `-- name: GetQuizAttemptsWithCourse :many
SELECT qa.id, qa.company_id, qa.quiz_id, qa.user_id, qa.score, qa.passed,
    qa.pending_review, qa.created_at, l.course_id
FROM quiz_attempts qa
JOIN quizzes q ON q.id = qa.quiz_id
JOIN lessons l ON l.id = q.lesson_id
WHERE qa.company_id = $1
ORDER BY qa.created_at, qa.id
`

type GetQuizAttemptsWithCourseRow struct {
	ID            uuid.UUID `json:"id"`
	CompanyID     uuid.UUID `json:"company_id"`
	QuizID        uuid.UUID `json:"quiz_id"`
	UserID        uuid.UUID `json:"user_id"`
	Score         int32     `json:"score"`
	Passed        bool      `json:"passed"`
	PendingReview bool      `json:"pending_review"`
	CreatedAt     time.Time `json:"created_at"`
	CourseID      uuid.UUID `json:"course_id"`
}

func (q *Queries) GetQuizAttemptsWithCourse(ctx context.Context, companyID uuid.UUID) ([]GetQuizAttemptsWithCourseRow, error) {
	rows, err := q.db.Query(ctx, getQuizAttemptsWithCourse, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetQuizAttemptsWithCourseRow{}
	for rows.Next() {
		var i GetQuizAttemptsWithCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.QuizID,
			&i.UserID,
			&i.Score,
			&i.Passed,
			&i.PendingReview,
			&i.CreatedAt,
			&i.CourseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuizzes = `-- name: GetQuizzes :many
SELECT id, company_id, lesson_id, questions, passing_score, max_attempts
FROM quizzes
WHERE company_id = $1
ORDER BY id
`

func (q *Queries) GetQuizzes(ctx context.Context, companyID uuid.UUID) ([]Quiz, error) {
	rows, err := q.db.Query(ctx, getQuizzes, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quiz{}
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.LessonID,
			&i.Questions,
			&i.PassingScore,
			&i.MaxAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuizzesByCourseIds = `-- name: GetQuizzesByCourseIds :many
SELECT q.id, q.company_id, q.lesson_id, q.questions, q.passing_score, q.max_attempts
FROM quizzes q
JOIN lessons l ON l.id = q.lesson_id AND l.company_id = q.company_id
WHERE q.company_id = $1 AND l.course_id = ANY($2::uuid[])
ORDER BY l.course_id, q.id
`

type GetQuizzesByCourseIdsParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	CourseIds []uuid.UUID `json:"course_ids"`
}

func (q *Queries) GetQuizzesByCourseIds(ctx context.Context, arg GetQuizzesByCourseIdsParams) ([]Quiz, error) {
	rows, err := q.db.Query(ctx, getQuizzesByCourseIds, arg.CompanyID, arg.CourseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quiz{}
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.LessonID,
			&i.Questions,
			&i.PassingScore,
			&i.MaxAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuiz = `-- name: UpdateQuiz :one
UPDATE quizzes
SET questions = $3, passing_score = $4, max_attempts = $5
WHERE company_id = $1 AND id = $2
RETURNING id, company_id, lesson_id, questions, passing_score, max_attempts
`

type UpdateQuizParams struct {
	CompanyID    uuid.UUID   `json:"company_id"`
	ID           uuid.UUID   `json:"id"`
	Questions    []byte      `json:"questions"`
	PassingScore int32       `json:"passing_score"`
	MaxAttempts  pgtype.Int4 `json:"max_attempts"`
}

func (q *Queries) UpdateQuiz(ctx context.Context, arg UpdateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, updateQuiz,
		arg.CompanyID,
		arg.ID,
		arg.Questions,
		arg.PassingScore,
		arg.MaxAttempts,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.LessonID,
		&i.Questions,
		&i.PassingScore,
		&i.MaxAttempts,
	)
	return i, err
}
